### ISSUE TITLE
Is my host correct.

### ISSUE THREAD

**Issue by codypet** [moralmunky/Home-Assistant-Mail-And-Packages#1]
A couple of issues I seem to be having is I'm getting the sensors to come up, but I don't believe its logging in correctly.  I get notified that I have no packages even though I know there's a USPS package coming on June 4.  

My error looks like this:
`2019-06-02 04:22:37 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform mail_and_packages
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 400, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 85, in setup_platform
    add_devices([MailCheck(),USPS_Mail(),USPS_Delivering(),USPS_Delivered(),UPS_Delivering(),UPS_Delivered(),FEDEX_Delivering(),FEDEX_Delivered()])
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 137, in __init__
    self.update()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/util/__init__.py", line 224, in wrapper
    result = method(*args, **kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 159, in update
    account = login()
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 360, in login
    account = imaplib.IMAP4_SSL(host, port)
  File "/usr/lib/python3.5/imaplib.py", line 1269, in __init__
    IMAP4.__init__(self, host, port)
  File "/usr/lib/python3.5/imaplib.py", line 192, in __init__
    self._connect()
  File "/usr/lib/python3.5/imaplib.py", line 240, in _connect
    raise self.error(self.welcome)
imaplib.IMAP4.error: None`

My config currently as follows.  I've tried changing the path to the full path, that didn't work.  I went from my regular password which has two step authentication to an app password, that didn't work.   I tried the using imap instead of pop, and that didn't work either.  I'm running out of ideas.   
`mail_and_packages:
  host: pop.gmail.com
  port: 995
  username: XXXXXXX@gmail.com
  password: APP Password
  folder: 'Inbox'
  image_output_path: '/local/mail_and_packages/'`

Any information you may have would be a big help.

**Comment by codypet** [comment]
I upgraded to 0.94.3 and Python 3.7 and my errors look like this now.
`Error while setting up platform mail_and_packages
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 85, in setup_platform
    add_devices([MailCheck(),USPS_Mail(),USPS_Delivering(),USPS_Delivered(),UPS_Delivering(),UPS_Delivered(),FEDEX_Delivering(),FEDEX_Delivered()])
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 137, in __init__
    self.update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 224, in wrapper
    result = method(*args, **kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 159, in update
    account = login()
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 360, in login
    account = imaplib.IMAP4_SSL(host, port)
  File "/usr/lib/python3.7/imaplib.py", line 1288, in __init__
    IMAP4.__init__(self, host, port)
  File "/usr/lib/python3.7/imaplib.py", line 201, in __init__
    self._connect()
  File "/usr/lib/python3.7/imaplib.py", line 249, in _connect
    raise self.error(self.welcome)
imaplib.IMAP4.error: None`

Also I noticed the Lovelace resource points to that mail_card folder.  Should it be the mail_and_packages folder?

**Comment by moralmunky** [comment]
Double check that you have changed all of the required configuration information inside the sensor.py file as indicated in the instructions. Putting the settings in the configuration file are not implemented yet. Yes, the Lovelace resource should point to mail_and_packages, this instruction has been updated.

There is a known asyncio issue.

**Comment by codypet** [comment]
So this morning it started working for mail, but not packages from USPS.  I'm not sure if this is the case for everyone's email, but I get my "informed delivery daily digest" which states what mail is coming and a tracking number from whatever package is being delivered today from USPSInformedDelivery@usps.gov which is consistent with the documentation.   The package information itself (info about it actually being delivered, or what day its expected when it originates) comes from auto-reply@usps.com.  I didn't see that in the documentation.  Perhaps I'm missing it?  Is this common on everyone elses emails?

**Comment by moralmunky** [comment]
Are you referring to documentation as the readme in the repository? Does this answer your question? 

The only function that reads the content is the USPS Mail, only the image attachments. Everything else goes off of the subject lines, not the content. Below are the possible subject lines. I only have it set up to look for the current day notifications (if they are provided by the shipper) Out for Delivery and Delivered.

FedEx Subject Lines

- Package is received by FedeEx: Your delivery is scheduled for Tuesday, 07/09 by 10:30 am
- Morning of delivery: Your delivery is scheduled for today, 07/09 by 10:30 am
- Delivered: FedEx Shipment 106125175432: Your package has been delivered, date and time in email body
- Pickup Ready: Your package is ready for pickup at FedEx Office

UPS Subject Lines

- Package is received by UPS: UPS Ship Notification, Tracking number ##############, Scheduled Delivery Date in email body
- Day before notification: UPS Update: Package Scheduled for Delivery Tomorrow, estimated date and time in email body
- Morning of delivery: Your delivery is scheduled for today, 07/09 by 10:30 am
- Out for delivery: UPS Update: Follow Your Delivery on a Live Map
- Delivered: Your UPS Package was delivered, date and time in email body
- Pickup Ready: Your package is ready for pickup at FedEx Office

USPS Mail

- From the informed delivery, number of images = number of pieces to expect


USPS Packages

- Two days before: USPS® Expected Delivery on Monday, July 8, 2019 arriving by 8:00pm ###########
- Updated delivery day: USPS® Expected Delivery on Monday, July 8, 2019 arriving by 8:00pm ###########
- Day of delivery: USPS® Expected Delivery on Monday, July 8, 2019 arriving by 8:00pm ###########
- Out for delivery: USPS® Expected Delivery on Tuesday, May 14, 2019 arriving by 8:00pm 9361269903503785025706, email body specifies out for delivery
- Delivered: USPS® Item Delivered, Front Desk/Reception/Mail Room ##############
-

**Comment by codypet** [comment]
My mistake.   I'm still learning the lingo, but when I were referring to "documentation" I was referring to whats included in sensor.py.

I saw this in sensor.py and like you're saying it goes by subject line, but I wasn't sure if the email it has ahead of it made a difference.

`USPS_Email = 'USPSInformedDelivery@usps.gov'
USPS_Mail_Subject = 'Informed Delivery Daily Digest'
USPS_Delivering_Subject = 'Expected Delivery on'
USPS_Delivered_Subject = 'Item Delivered'
`
Since I was getting the mail portion working, but not the package portion I thought maybe it had something to do with the fact that they're coming from two different emails.  This image is a screengrab of the emails I received this morning from the post office related to it.
![email](https://user-images.githubusercontent.com/17790157/60915279-70d05000-a259-11e9-8083-fcd0c272ed9b.JPG)

**Comment by moralmunky** [comment]
I see what you are saying. Another USPS email address variable needs to be created for the packages. I had the following to mine.

`USPS_Mail_Email = 'USPSInformedDelivery@usps.gov'
USPS_Packages_Email = 'auto-reply@usps.com''

I am going to updated the code in my repository after I look through your add-config branch. This will include the changes I made to the functions where the email checking is pulled out of the entities into it's own separate function.

**Comment by moralmunky** [comment]
Adding the previous variable corrected the issue.
