### ISSUE TITLE
Slow start warnings

### ISSUE THREAD

**Issue by moralmunky** [moralmunky/Home-Assistant-Mail-And-Packages#10]
The component begins checking for email right away and appears to be causing a slowdown loading other components causing warnings.

**Comment by firstof9** [comment]
This will likely be fixed in the latest PR

**Comment by FuzzyMistborn** [comment]
Installed the patch and ran a reboot.  No more boatload of components failing to load in 10 seconds errors!  Will see if it spits out an image tomorrow (assuming I get mail).

**Comment by firstof9** [comment]
I'll be testing it on my Pi3 later this evening as well.

**Comment by firstof9** [comment]
So far so good on Pi3 far less "10 second" errors than before.
