### ISSUE TITLE
ISSUE: Could not read camera Mail Amazon Delivery Camera image from file

### ISSUE THREAD

**Issue by clowncracker** [moralmunky/Home-Assistant-Mail-And-Packages#1004]
**Describe the bug**
I'm getting this error of being unable to read the Amazon picture, even if nothing is being delivered today.  It tends to happen hundreds of times a day.

**Environment (please complete the following information):**
 - OS: [e.g. HassOS
 - Type of device: Unraid VM
 - Home Assistant version: 2024.11.2
 - Component version: 0.4.1

**Logs**
This error originated from a custom integration.

Logger: custom_components.mail_and_packages.camera
Source: custom_components/mail_and_packages/camera.py:128
integration: Mail and Packages (documentation, issues)
First occurred: 12:46:10 PM (1 occurrences)
Last logged: 12:46:10 PM

Could not read camera Mail Amazon Delivery Camera image from file: /config/custom_components/mail_and_packages/images/amazon/9c19849c-7386-4a01-8e96-608099fad1df.jpg

**Comment by clowncracker** [comment]
This is still happening.  Not sure when the merged change will be released.

**Comment by firstof9** [comment]
in the latest beta

**Comment by clowncracker** [comment]
I'm no longer getting the issue in 0.4.2-b6.

**Comment by firstof9** [comment]
Thanks.
