### ISSUE TITLE
ISSUE: DPD Parcel (Germany) not detected

### ISSUE THREAD

**Issue by SvenJ76** [moralmunky/Home-Assistant-Mail-And-Packages#1006]
**Describe the bug**
Obviously the Ttxt in the German DPD Annoucments has changed. I just a mail with the Topic "Zwischen 10:16 und 11:16 Uhr kommt Ihr DPD Paket".

**Environment (please complete the following information):**
 - OS: [e.g. HassOS/Raspbian/CentOS]
 - Type of device: [e.g. RPi3/NUC/Synology]
 - Home Assistant version: [e.g. 0.105.5]
 - Hassio/Docker/Core? 
 - Component version: [e.g. 0.1.2]

**Logs**
Paste your error logs here.

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment]
https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/blob/a98a75baaf1d8b0145ecaff3aaaf2596ea11fbf7/custom_components/mail_and_packages/const.py#L453-L471

What changes to these lines are you suggesting?

**Comment by SvenJ76** [comment]
Line 466: 
In my mail I received today, the subject was "Zwischen 10:16 und 11:16 Uhr kommt Ihr DPD Paket". So maybe a wildcard filter would be possible? Or maybe the second part "kommt Ihr DPD Paket" would be sufficient.
