### ISSUE TITLE
ISSUE: Many Logfile errors

### ISSUE THREAD

**Issue by bmf7777** [moralmunky/Home-Assistant-Mail-And-Packages#101]
**Describe the bug**
see logs ... many error messages in log file from fedex

**Environment (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - Type of device: [e.g. NUC]
 - Home Assistant version: [e.g. 0.108.5]
 - Core
 - Component version: [e.g. 0.1.5]

**Logs**
Paste your error logs here.

Logger: mailparser.utils
Source: custom_components/email/sensor.py:106
First occurred: 10:22:26 AM (192 occurrences)
Last logged: 2:18:11 PM

    More than one match found for (?:id\s+(?P<id>.+?)(?:\s*[(]?envelope-from|\s*[(]?envelope-sender|\s+from|\s+by|\s+with(?! cipher)|\s+for|\s+via|;)) in from pvma00011.prod.fedex.com pvma00011.prod.fedex.com 204.135.242.202 using TLS with cipher ECDHE-RSA-AES256-GCM-SHA384 256/256 bits Client did not present a certificate by mx29.infosec.fedex.com FedEx MX with SMTP id 79.93.08286.EF9D79E5; Wed, 15 Apr 2020 23:07:26 -0500 CDT
    More than one match found for (?:id\s+(?P<id>.+?)(?:\s*[(]?envelope-from|\s*[(]?envelope-sender|\s+from|\s+by|\s+with(?! cipher)|\s+for|\s+via|;)) in from prh15009.prod.fedex.com prh15009.prod.fedex.com 204.135.242.59 using TLS with cipher ECDHE-RSA-AES256-GCM-SHA384 256/256 bits Client did not present a certificate by mx27.infosec.fedex.com FedEx MX with SMTP id 34.E6.14450.E203A9E5; Fri, 17 Apr 2020 17:39:42 -0500 CDT

**Screenshots**

**Additional context**

**Comment by firstof9** [comment]
This isn't from the mail_and_packages component.
