### ISSUE TITLE
ISSUE: USPS packages not tracking

### ISSUE THREAD

**Issue by FuzzyMistborn** [moralmunky/Home-Assistant-Mail-And-Packages#102]
**Describe the bug**

Realized that I'm not getting USPS packages tracked.  There are packages listed in the USPS email with a tracking number but it doesn't get added to HASS.

**Environment (please complete the following information):**
 - OS: [e.g. HassOS/Raspbian/CentOS] Ubuntu 18.04
 - Type of device: [e.g. RPi3/NUC/Synology] x86 server
 - Home Assistant version: [e.g. 0.105.5] 108.x
 - Hassio/Docker/Core? Docker
 - Component version: [e.g. 0.1.2] 0.1.5

**Logs**
Paste your error logs here.
None

**Screenshots**
![image](https://user-images.githubusercontent.com/16689090/79750512-17fd1000-82df-11ea-9825-fc7187867c3a.png)
What's in my email

**Additional context**

Let me know what logging or anything else I can provide to figure this one out.

**Comment by moralmunky** [comment]
USPS package tracking doesn’t come from the informed delivery daily emails. Check that you are signed up for all the email notification that are listed in the read me. USPS will send out day of delivering and delivered email notifications that are package specific.

**Comment by FuzzyMistborn** [comment]
Huh, could have sworn I'd turned all that on, but I see now that I hadn't.  My bad.  Thanks!
