### ISSUE TITLE
ISSUE: Mail from Hermes Germany not detected

### ISSUE THREAD

**Issue by TheHawk588** [moralmunky/Home-Assistant-Mail-And-Packages#1021]
**Describe the bug**
I reveived an Hermes notifaction with the subject "Deine Hermes Sendung von OTTO ist auf dem Weg" This was not detected.
Delivery date is in the string

Voraussichtliche Zustellung am
 
Donnerstag, 28.11.2024

**Environment (please complete the following information):**
 - OS: [e.g. HassOS/Raspbian/CentOS]
 - Type of device: [e.g. RPi3/NUC/Synology]
 - Home Assistant version: [e.g. 0.105.5]
 - Hassio/Docker/Core? 
 - Component version: 0.4.2-b5

**Logs**
Paste your error logs here.

**Screenshots**
![image](https://github.com/user-attachments/assets/2935dff9-9207-4847-a6fb-1d0ba8a9f222)
![image](https://github.com/user-attachments/assets/d031c76b-044f-44f1-9514-9aa4732a6f87)

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment]
https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/blob/3611e966319d41dd6f50a399105c49166a8e69db/custom_components/mail_and_packages/const.py#L347-L349

Looks like the subject line has changed.

**Comment by firstof9** [comment]
Fixed in #1022
