### ISSUE TITLE
[Feature Request] Adding USPS Mail Delivered status into USPS Mail workflow

### ISSUE THREAD

**Issue by obhatti87** [moralmunky/Home-Assistant-Mail-And-Packages#1030]
**Is your feature request related to a problem? Please describe.**
Currently, the USPS mail workflow does not include the final status "USPS Mail is Delivered." This creates ambiguity for users tracking mail, as they cannot confirm when delivery has been completed. 

**Describe the solution you'd like**
Adding a "USPS Mail is Delivered" status to the USPS mail workflow. USPS has started sending notifications via email when the mail has been delivered to the mailbox. The email is sent from USPSInformeddelivery@email.informeddelivery.usps.com. This status should be triggered once the email is received to the recipient's email address. It should be visible in tracking updates to provide a clear end point in the mail delivery process. 

**Describe alternatives you've considered**
Reviewing the email sent by USPS regarding mail delivered. 

**Additional context**
Adding this status aligns with the package-tracking workflow provided by this integration. It would enhance the user experience by providing complete visibility into the mail delivery lifecycle.

![USPS Mail Delievered](https://github.com/user-attachments/assets/109871d6-8199-455d-a566-f7122b14f01f)

Thanks!

**Comment by firstof9** [comment]
There's already a `binary_sensor` for this.

Dupe #915
Implimented in #922

**Comment by obhatti87** [comment]
Thank you!
