### ISSUE TITLE
ISSUE: Amazon Packages Delivered sensor not being updated

### ISSUE THREAD

**Issue by chintito4ever** [moralmunky/Home-Assistant-Mail-And-Packages#1032]
**Describe the bug**
It can detect packages that are in transit from Amazon but doesn't update packages delivered sensor after delivery....all other sensors work fine.
**Environment (please complete the following information):**
 - OS: [e.g. HassOS/Raspbian/CentOS]
 - Type of device: [e.g. RPi3/NUC/Synology]
 - Home Assistant version: [e.g. 0.105.5]
 - Hassio/Docker/Core? 
 - Component version: [e.g. 0.1.2]
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.12.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.13.0",
    "docker": true,
    "arch": "x86_64",
    "timezone": "America/New_York",
    "os_name": "Linux",
    "os_version": "6.6.63-haos",
    "supervisor": "2024.12.0",
    "host_os": "Home Assistant OS 14.0",
    "docker_version": "27.2.0",
    "chassis": "embedded",
    "run_as_root": true
  }
**Logs**
Paste your error logs here.

**Screenshots**
![image](https://github.com/user-attachments/assets/c80be872-29b8-462d-a4e6-09f76f863862)
![image](https://github.com/user-attachments/assets/b4ef9fba-456b-433f-a9ec-90a547011b2a)
![image](https://github.com/user-attachments/assets/0acb7006-851e-4505-83c8-ff3a2b835570)

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by Audielite** [comment]
I am having the same exact issue as well.

**Comment by firstof9** [comment]
Enable debug logging and post logs, please scrub order numbers/tracking numbers.

**Comment by chintito4ever** [comment]
[home-assistant_mail_and_packages_2024-12-17T23-20-58.519Z.log](https://github.com/user-attachments/files/18172471/home-assistant_mail_and_packages_2024-12-17T23-20-58.519Z.log)

**Comment by chintito4ever** [comment]
[home-assistant_mail_and_packages_2024-12-17T23-20-58.519Z.log](https://github.com/user-attachments/files/18172480/home-assistant_mail_and_packages_2024-12-17T23-20-58.519Z.log)

**Comment by firstof9** [comment]
```
2024-12-17 18:20:44.519 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] DEBUG subject: Delivered: Your
2024-12-17 18:20:44.519 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (OR OR OR OR OR OR FROM "shipment-tracking@amazon.com" FROM "conferma-spedizione@amazon.com" FROM "confirmar-envio@amazon.com" FROM "versandbestaetigung@amazon.com" FROM "confirmation-commande@amazon.com" FROM "verzending-volgen@amazon.com" FROM "update-bestelling@amazon.com" SUBJECT "Delivered: Your" SINCE 17-Dec-2024)
```

Based on your email looks like they changed the from address.

**Comment by firstof9** [comment]
I've dropped this into the `0.4.2` release. Let me know how it goes for you.

**Comment by chintito4ever** [comment]
Can report you tomorrow, I have something coming for tomorrow.

**Comment by chintito4ever** [comment]
![image](https://github.com/user-attachments/assets/c76c66ca-9150-4419-ba95-9946b8fd0da6)
It WORKED! thank you for the quick fix.

**Comment by Audielite** [comment]
Mine is as well! Sorry I never got around to sending in logs before it was resolved.
