### ISSUE TITLE
ISSUE: Home Assistant Beta 0.109.0b0 Translations Error

### ISSUE THREAD

**Issue by SeanPM5** [moralmunky/Home-Assistant-Mail-And-Packages#104]
**Describe the bug**
Hey guys, thanks for this awesome integration. It's been working great for me but just wanted to report this very minor log warning that I've got since upgrading to 0.109.0b0 about translations.

```
Log Details (WARNING)
Logger: homeassistant.helpers.translation
Source: helpers/translation.py:206
First occurred: 3:36:07 AM (7 occurrences)
Last logged: 10:42:35 AM

mail_and_packages: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this
```

Nothing urgent, there's like ~7 weeks until the 0.111 releases but just wanted to make aware.

**Environment (please complete the following information):**
 - Home Assistant version: 0.109.0b0
 - Component version: 0.1.5

**Comment by firstof9** [comment]
Thanks for the heads up.

**Comment by firstof9** [comment]
Latest beta should fix this up.
