### ISSUE TITLE
ISSUE: mail_none.gif is renamed to a random string value

### ISSUE THREAD

**Issue by gtdiehl** [moralmunky/Home-Assistant-Mail-And-Packages#107]
**Describe the bug**
mail_none.gif is renamed to 4938fcaa-9077-4f6f-a467-2764050871fe.gif

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Type of device: Intel Atom
 - Home Assistant version: [e.g. 0.105.5] 0.108.4
 - Hassio/Docker/Core? Docker
 - Component version: [e.g. 0.1.2] 0.1.5

**Logs**
No errors in the HA log

**Screenshots**
N/A

**Additional context**
I've been using this integration for a while now and has worked great!  Now after I updated HA as well as the Mail and Packages component, I noticed the `mail_none.gif` is getting renamed to some long string rather than what I have seen in the past of `mail_today.gif`

Would debug logs be helpful?  How would I enable debug?

**Comment by moralmunky** [comment]
The string revolving string is in support of privacy issues if the user stored the created image in the WWW folder, required for certain notification methods. It was identified in the release notes for one of the beta releases and can be turned off in the integration settings.

In step two, after clicking the gear icon in the upper right, there is a check box options named 'enable random image file name.'

This is not an official release and it is not fully documented.

**Comment by gtdiehl** [comment]
Great, thank you!  That fixed my problem. 

I installed the component through HACS, btw.

**Comment by firstof9** [comment]
Correct it's a beta release for testing, soon to be released once all the testing is done.
Thanks for testing. 👍
