### ISSUE TITLE
ISSUE: Duplicate counts for USPS packages

### ISSUE THREAD

**Issue by elardner** [moralmunky/Home-Assistant-Mail-And-Packages#108]
Currently, the add-on is counting all emails that I receive from USPS. With only "Day of Delivery" checked in Informed Delivery, USPS usually sends a morning email with a broad ETA for the package. An hour or two later, they send an update with a tighter delivery window. This results in, usually, a double count of the packages predicted to arrive from USPS. 

Is there a change to USPS emails that would solve this issue, or can we add functionality to ignore duplicate shipping numbers or only check USPS packages during a certain window (There's usually an hour or two between email updates)?

![image](https://user-images.githubusercontent.com/6210769/80622235-86944900-8a16-11ea-9619-2822f3bbef63.png)

![image](https://user-images.githubusercontent.com/6210769/80622706-2f42a880-8a17-11ea-82f4-37ae54adcfa6.png)

**Comment by firstof9** [comment]
Currently we're not tracking the tracking numbers, this is planned so help with the delivery count.

**Comment by firstof9** [comment]
Please see #92
