### ISSUE TITLE
ISSUE: gif not being created

### ISSUE THREAD

**Issue by ikrowni** [moralmunky/Home-Assistant-Mail-And-Packages#111]
gif not being created

 - OS: HassOS
 - Type of device: NUC
 - Home Assistant version: 0.109.3
 - Hassio/Docker/Core?  Hassio
 - Component version: 0.1.5

**Additional context**
I created the folder "images" within my config folder. Then i created the folder "mail_and_packages" within the images folder

is this the path that should be used?

`/images/mail_and_packages/`

or am i supposed to use 

`/home/homeassistant/.homeassistant/images/mail_and_packages/`

neither one seems to be working properly. everything seems to work fine except the gif being created in the images folder.

**Comment by firstof9** [comment]
The path should be configured as ```/config/images/mail_and_packages/``` for HassIO/Docker.
