### ISSUE TITLE
Configuration issue

### ISSUE THREAD

**Issue by jasonkelly214** [moralmunky/Home-Assistant-Mail-And-Packages#116]
I'm unsure if I'm configuring this wrong. I'm trying to connect my gmail so I am using imap.gmail.com, along with my full xxx@gmail.com address. It's telling me it could not connect to the mail server. If it remove imap and use gmail.com, it hangs hassio.

**Comment by jasonkelly214** [comment]
I received an email saying the login was blocked by gmail but it's not allowing me to unblock it. Thoughts?

**Comment by firstof9** [comment]
You will need to setup an app password in order to use gmail's IMAP server with this. Please see the following link for details on how to set that up.

https://support.google.com/accounts/answer/185833?hl=en

**Comment by jasonkelly214** [comment]
Great thanks!
