### ISSUE TITLE
ISSUE: not reading any new packages from usps

### ISSUE THREAD

**Issue by gbdavidx** [moralmunky/Home-Assistant-Mail-And-Packages#117]
**Describe the bug**
I am able to connect to my gmail account (it can see my folders) but not picking up any new packages though it is is being sent to my gmail from usps

**Environment (please complete the following information):**
 - OS: [Unraid / Docker
 - Home Assistant version: [Home Assistant 0.109.6]
 - Hassio/Docker/Core? 
 - Component version: [e.g. 0.1.2]

**Logs**
No errors

**Screenshots**

**Additional context**

**Comment by firstof9** [comment]
Do you have  your USPS email's filter into another folder/label?
If not what folder did you select?

**Comment by gbdavidx** [comment]
I changed it to ALL, it goes straight into my inbox no filter

**Comment by firstof9** [comment]
Use the folder called "INBOX".

**Comment by gbdavidx** [comment]
tried that first

**Comment by firstof9** [comment]
This package is out for delivery today or in the future?

**Comment by gbdavidx** [comment]
<img width="779" alt="Screen Shot 2020-05-12 at 11 39 49 AM" src="https://user-images.githubusercontent.com/26369204/81732398-4cc73780-9445-11ea-918c-09405a2255fd.png">

**Comment by firstof9** [comment]
Can you check in your email if it states "out for delivery" ?

**Comment by gbdavidx** [comment]
i dont see an email for "out for delivery" i had usps mail package delivered and all options check in informed delivery, so far the regular mail seemed to work however

**Comment by gbdavidx** [comment]
<img width="654" alt="Screen Shot 2020-05-14 at 12 37 06 PM" src="https://user-images.githubusercontent.com/26369204/81977945-a19eb580-95df-11ea-89cb-23b680df1260.png">

**Comment by firstof9** [comment]
You have an email with a subject line along these lines: "USPS® Expected Delivery on..." then in the body it would say something like: "Your item is out for delivery on ..."

If you are only getting the email that says "USPS expects to deliver your package by ..." please let me know.

**Comment by gbdavidx** [comment]
i only got 1 email from usps and that was for MIAL only, packages were included but were not sent in additional email

**Comment by gbdavidx** [comment]
<img width="1064" alt="Screen Shot 2020-05-14 at 2 31 21 PM" src="https://user-images.githubusercontent.com/26369204/81988018-96ec1c80-95ef-11ea-80bd-f861cfb4b171.png">

**Comment by gbdavidx** [comment]
<img width="1094" alt="Screen Shot 2020-05-14 at 2 33 23 PM" src="https://user-images.githubusercontent.com/26369204/81988185-e0d50280-95ef-11ea-8d35-ac50b261287d.png">
some more relevant information

**Comment by firstof9** [comment]
The email that says "Expected Delivery on ... " if you look at the body of the message does it have a line that says "out for delivery" in the body?

**Comment by gbdavidx** [comment]
<img width="805" alt="Screen Shot 2020-05-14 at 3 01 46 PM" src="https://user-images.githubusercontent.com/26369204/81990349-d74d9980-95f3-11ea-82df-002d675fded3.png">
only email for "out for deliver" :(

**Comment by firstof9** [comment]
So on the 13th your USPS packages (if you are using the latest beta) would have shown 1 package in transit. You can test this by adjusting the "today" variable to the 13th in the script.

Keep in mind for USPS packages only the day of your delivery will the sensor trigger and if the email has "out for delivery" in the body like that one.

**Comment by FuzzyMistborn** [comment]
I haven't been getting package notifications either because USPS seems to waffle between sending the "out for delivery" notification or not (I have the alert on in my USPS settings).  I got one today like this instead:

![image](https://user-images.githubusercontent.com/16689090/82055965-40ceb600-968f-11ea-9804-a65265434ef8.png)

Is there any way to look in the body of the message for the "today" message?

**Comment by firstof9** [comment]
"Today" is the current date. So that email should show up as "In Transit".

If you do these steps [in this post](https://community.home-assistant.io/t/mail-and-packages-custom-component-for-ups-fedex-and-usps/118081/173?u=firstof9) you'll get debug messages this will help see what's going on better.

**Comment by FuzzyMistborn** [comment]
Yesterday it actually had the date though when I got the "expected delivery" email for the same package.  I have one package "in transit" but that's FedEx, nothing from USPS.

I'll turn on debugging.

**Comment by firstof9** [comment]
@FuzzyMistborn @gbdavidx I just pushed a potential fix:

https://raw.githubusercontent.com/firstof9/Home-Assistant-Mail-And-Packages/condense-sensor/custom_components/mail_and_packages/sensor.py

I tested it as working on my end with an "out for delivery" email from USPS.

**Comment by gbdavidx** [comment]
I think it’s working now. You can close it!  Thank you

**Comment by firstof9** [comment]
Pushed it into a beta release, the issue will close once we release, no worries.

**Comment by FuzzyMistborn** [comment]
Working here thanks!

**Comment by gbdavidx** [comment]
USPS® Item Delivered, In/At Mailbox 92748999937433543484340113
any chance these can be added to the "mail" for usps? this would probably be a feature request, the package is now in the "mailbox" but doesnt show up as mail

**Comment by firstof9** [comment]
It just gets counted as a delivered package.
