### ISSUE TITLE
Removed configuration support

### ISSUE THREAD

**Issue by robert-alfaro** [moralmunky/Home-Assistant-Mail-And-Packages#12]
Why not preserve configuration support and support new config entry flow too? Removing this functionality is cumbersome to some users... Power users

**Comment by firstof9** [comment]
@moralmunky I'm feeling this would be a step backwards from the progress we've made so far, what's your opinion on this?

**Comment by firstof9** [comment]
moralmunky's comments posted to #53:
> Short answer, we don't need it.
> 
> Long answer for anyone that wants to understand why.
> 
> As someone who has resisted moving away from yaml configuration and heavily organized my configuration into drop in packages, I understand the want to keep this.
> 
> The HASS team appears to be moving away from external yaml and creating methods to store settings to without yaml. Most of the components that have become official integrations loose their yaml settings. There are also recommended way to migrate a system so you don't have to set up each individual integration by hand. This integration is not complicated and does not have extensive set up options. I also thing the ability you added to reconfigure the Integration is also a case against reinstating yaml configuration.
