### ISSUE TITLE
ISSUE: component deletes mail_none.gif

### ISSUE THREAD

**Issue by blkpanther5** [moralmunky/Home-Assistant-Mail-And-Packages#120]
When running this custom component, I see that the Python script attempts to delete mail_none.gif, and then complains when it's missing and complains again when it attempts to copy mail_none.gif to mail_today.gif.

**Environment (please complete the following information):**
 - OS: CentOS 7.5
 - Type of device: PC
 - Home Assistant version: 0.109.6
 - Docker
 - Component version: Latest: 0.1.5

**Logs**
Could not read camera mail_usps image from file: custom_components/mail_and_packages/mail_today.gif
Error attempting to copy image: [Errno 2] No such file or directory: '/config/custom_components/mail_and_packages/mail_none.gif'

**Additional context**
So after installing the component, I noticed mail_none.gif went missing. That's fine I think, I'll just copy it back in there. 5 minutes later after the component runs, the file is missing again.

When I comment out line #1092 of sensor.py, the mail_none.gif doesn't get deleted. When I attempt to lock that file in place, by making it so that HA can't delete the file; the entire component fails.

**Comment by firstof9** [comment]
What do you have the image output directory configured as?

**Comment by blkpanther5** [comment]
> What do you have the image output directory configured as?

/config/custom_components/mail_and_packages/

Ha, is that the problem? I could put it elsewhere.

**Comment by firstof9** [comment]
Yes please store the images elsewhere, the component cleans up the images after itself.

You did help highlight a potential issue which I've now added a check to the configuration to disallow the component directory from being used for image storage.
