### ISSUE TITLE
ISSUE: Not generating gif from USPS emails 

### ISSUE THREAD

**Issue by jasonkelly214** [moralmunky/Home-Assistant-Mail-And-Packages#122]
**Describe the bug**
I am getting notified of packages and letters but it is not creating a gif. I even created the appropriate folder in case that was the issue.

**Environment (please complete the following information):**
 - OS: Hass.io installed in a docker
 - Type of device: NUC
 - Home Assistant version: 0.109.6
 - Hassio/Docker/Core? hassio in docker
 - Component version: 0.1.5

**Logs**
Paste your error logs here.

**Screenshots**

**Additional context**

**Comment by firstof9** [comment]
What do you have the image path set to?

**Comment by jasonkelly214** [comment]
I have the camera set as in the example. I didn't see any way in the add on to change or modify it.

`camera:
  - platform: local_file
    file_path: /config/images/mail_and_packages/mail_today.gif
    name: mail_usps`

**Comment by firstof9** [comment]
No in the integration configuration.

**Comment by jasonkelly214** [comment]
Ok I see. I’m using hassio so I hd to remove the “random” checkbox as well as changing the path.

**Comment by firstof9** [comment]
You can keep the "random" option checked, but you'll need an automation to update the camera image. I posted that automation [here](https://community.home-assistant.io/t/mail-and-packages-custom-component-for-ups-fedex-and-usps/118081/400?u=firstof9).
