### ISSUE TITLE
ISSUE: usps_mail.camera in lovelace card not showing correctly.

### ISSUE THREAD

**Issue by liamrpowell** [moralmunky/Home-Assistant-Mail-And-Packages#123]
**Describe the bug**
I have 
camera:
  - platform: local_file
    file_path: /config/images/mail_and_packages/mail_today.gif
    name: mail_usps

In configuration.yaml but when creating a card with camera.mail_usps it seems to not to be able to find the file. Just has a blue square with a question mark in it.

I set /config/images/mail_and_packages/ when adding the integration, and it is showing mail from USPS count correctly. Just the image is not working. 

/config/images/mail_and_packages/ does have the GIf in it as well.
    

**Environment (please complete the following information):**
 - OS: Ubuntu Server
 - Type of device: NUC
 - Home Assistant version: [e.g. 0.105.5]
 - Hassio/Docker/Core?  DOCKER
 - Component version: 0.1.5

**Logs**
Paste your error logs here.

**Screenshots**

**Additional context**

**Comment by firstof9** [comment]
The entity should be ```camera.mail_usps```

**Comment by liamrpowell** [comment]
> The entity should be `camera.mail_usps`

Sorry it is camera.mail.usps

**Comment by firstof9** [comment]
The gif in ```/config/images/mail_and_packages/``` is it called ```mail_today.gif``` ?

**Comment by firstof9** [comment]
If the gif is a random jumble of letters and numbers, you'll need [this automation](https://community.home-assistant.io/t/mail-and-packages-custom-component-for-ups-fedex-and-usps/118081/400?u=firstof9) posted on the Home Assistant forums.

**Comment by liamrpowell** [comment]
> The gif in `/config/images/mail_and_packages/` is it called `mail_today.gif` ?

Yes it is.

**Comment by liamrpowell** [comment]
Ok update. Found out it is Safari causing the problem.  Works on the IOS app and Chrome, but not safari.
Thought maybe it was my content blocker, but turned it off and the problem persisted.
