### ISSUE TITLE
[Feature Request] Canada Post

### ISSUE THREAD

**Issue by Deekerman** [moralmunky/Home-Assistant-Mail-And-Packages#124]
Looks like a great system, would be great if Canada Post was available

**Comment by moralmunky** [comment]
You would need to provide the notification emails that indicate out for delivery and delivered. Sender email address, subject lines, and body copy.

**Comment by Deekerman** [comment]
Sorry, new to all of this still. 

Do these help? Do you need any information from the app?

![Delivered](https://user-images.githubusercontent.com/33733383/81976148-18df4400-95f6-11ea-949b-86276ffe4e37.PNG)
![Notification](https://user-images.githubusercontent.com/33733383/81976152-18df4400-95f6-11ea-8b15-f8bb4529f8f7.PNG)
![Confirmation](https://user-images.githubusercontent.com/33733383/81976153-18df4400-95f6-11ea-8c3d-c4e9dc262ae5.PNG)

**Comment by firstof9** [comment]
So is the "Confirmation of Shipment" the same as "Out for delivery" ?

**Comment by Deekerman** [comment]
Confirmation of shipment is the first thing you will receive (should they set you up for notifications). Then I don't know  how well they keep you up to date (via email) until delivered. Those 3 emails are all i received from them for that shipment.

**Comment by firstof9** [comment]
I think the only thing we would be able to derive from this, without additional research, is going to be a "Delivered" sensor. I'll poke around the ca post site for some info.

**Comment by firstof9** [comment]
This is in ```0.2.1-b1``` feedback would be great. Thanks.

**Comment by kaylak4520** [comment]
I know this is a while too late, however, maybe this will be useful?  https://www.canadapost-postescanada.ca/info/mc/business/productsservices/developers/services/tracking/default.jsf
