### ISSUE TITLE
ISSUE: Same-day deliveries can result in negative USPS sensors

### ISSUE THREAD

**Issue by ronaldheft** [moralmunky/Home-Assistant-Mail-And-Packages#127]
**Describe the bug**
I have a package that was sent from Amazon for same day delivery by USPS that resulted in negative sensor values.

Amazon sent the package around 2pm, after USPS sends the normal expected delivery emails. The package was then delivered at 6pm without USPS ever sending a expected delivery email (but they sent the package delivered email).

After the package was delivered, my sensors looked like this:

USPS Packages: 0
USPS Delivering: -1
USPS Delivered: 1

This issue looks to be occurring because the logic for the USPS delivery sensor takes the delivering emails - delivered emails:

https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/blob/d9f7fe161ea3ed9f2148c1a4ea165faa2d69a734/custom_components/mail_and_packages/sensor.py#L212

Since I never received the delivering email from USPS, that logic put the sensor at a negative value (0 delivering - 1 delivered = -1).

Under this circumstance, I would expect the sensor values to look like so:

USPS Packages: 1
USPS Delivering: 0
USPS Delivered: 1

I think this could be resolved by using the max value of 0 and the sensor calculation, so the delivering value never goes negative. Looking at the code, I think the packages count would then be fixed with that change alone, but additional testing may be required.

Also, even though this is a USPS issue, I think it makes sensor to apply that logic for all carriers, so in the event they don’t send their delivering email, sensors never go negative.

**Comment by firstof9** [comment]
I've added math to resolve this
https://github.com/firstof9/Home-Assistant-Mail-And-Packages/blob/72ea936fb97664a96203cb71ccd5a1d10d429a5a/custom_components/mail_and_packages/sensor.py#L219

**Comment by ronaldheft** [comment]
Awesome! Thanks for the quick fix.

**Comment by firstof9** [comment]
Resolved in 0.2.0 - Release
