### ISSUE TITLE
Can't fully remove Mail and Packages from HA

### ISSUE THREAD

**Issue by eoren1** [moralmunky/Home-Assistant-Mail-And-Packages#128]
I installed this package but my wife didn't find it as exciting as I did so decided to remove it.

I went into HACS and uninstalled and removed the sensor info from configuration.yaml. Restarted the HA but am getting notifications after each restart of:
Invalid config
The following integrations and platforms could not be set up:
  mail and packages

If I go to Configuration - Integrations, I see mail and packages there. I clicked the 3 dots and was able to delete the 14 entries individually but cannot delete the package itself.

Appreciate some advice.

**Comment by firstof9** [comment]
You'll have to dig around in the ```.storage``` directory for the ```config_entries``` to remove.
If I recall the file is called ```core.config_entries```.

**Comment by firstof9** [comment]
For future reference the proper way to uninstall 3rd party integrations is the following:

1. Remove Integration from Integration menu
2. Uninstall via HACS
3. Restart Home Assistant

**Comment by eoren1** [comment]
Thank you very much - right on both counts. I was scared to edit the entries file so I simply reinstalled Mail and Packages via HACS, went to Configuration - Integrations and deleted then uninstalled from HACS
Appreciate the really quick reply!
