### ISSUE TITLE
ISSUE: image not displaying correctly

### ISSUE THREAD

**Issue by XmemphistoX** [moralmunky/Home-Assistant-Mail-And-Packages#134]
**Describe the bug**
Gif file that shows the various images of mail is stuck to the one that says "No Mail" despite email with images.  Where does it generate the gif file with the images at?

**Environment (please complete the following information):**
 - OS: Windows/Docker
 - Type of device: PC
 - Home Assistant version: 0.110.3
 - Hassio/Docker/Core? Docker
 - Component version: 18.09.6

**Logs**
Paste your error logs here.

**Screenshots**
https://photos.app.goo.gl/ik2SnCUD5GJEqWAi7

**Additional context**
Installed using HACS.

**Comment by firstof9** [comment]
Screen shot the step 2 of your settings.
Need to know what you have set the image output path to.

**Comment by XmemphistoX** [comment]
Not sure exactly what is step 2.  Here is my card and the camera sensor information.  I realized that its pulling the unedited mail_today.gif but im not sure exactly what creates it everyday  or where it places it at after pulling images from the email.

![Mail 1](https://user-images.githubusercontent.com/5236235/83464371-8d531900-a425-11ea-83c3-8a4270ae302a.PNG)

![Mail 2](https://user-images.githubusercontent.com/5236235/83464377-9217cd00-a425-11ea-9b40-19085c32a95f.PNG)

**Comment by XmemphistoX** [comment]
I've also created the /config/images/mail_and_packages folder and placed image-no-mailpieces700.jpg and mail_none.gif in there.

I don't see a mail_today.gif in that folder

**Comment by thisisbenwoo** [comment]
I'm experiencing the same.
I'm finding that when the automation runs, the outputting file looks like this:
f72c7bb9-b0fc-47c6-8869-f50b37aa92d5.gif

The letters and numbers change over time, but it is never named mail_today.gif

**Comment by firstof9** [comment]
Please see the [wiki for updated information](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Example-Automations-and-Templates#automations), we have updated automation examples and sensors to help with these.

To explain the filename changes due to a security issue that was brought to our attention, so the file name changes, otherwise your privacy could be compromised (ie: someone could get your home address).

**Comment by XmemphistoX** [comment]
Thanks.  I'm not sure how I missed the wiki

**Comment by thisisbenwoo** [comment]
same here. Thanks.. it works, and it's awesome!!!


*Ben Woo*
(212) 724-1188
*this*is*ben*woo*@gmail.com <http://gmail.com/>*
