### ISSUE TITLE
Delivery notices that come to different email addresses

### ISSUE THREAD

**Issue by thisisbenwoo** [moralmunky/Home-Assistant-Mail-And-Packages#136]
Chris, I'm not sure if you have seen this before, but for us, we use an email alias (eg. all@family.com) for notices that impact both my wife and I. So, when we received today's UPS My Choice email, it went to that alias. 

However, despite being in my mailbox, it's not being picked up. I'm suspecting that you are reading the actual email addressee.

So my question is this, it is possible for the integration to (a) ignore the To: field since you're reading a specific person's email box anyway; or (b) to list multiple email addresses to scan?

Thanks .. I've redacted the email, but I'm not sure it will actually help!

<img width="634" alt="Annotation 2020-06-03 101704" src="https://user-images.githubusercontent.com/45885373/83667581-7aeef180-a583-11ea-8682-a9c25c0d9a3d.png">

**Comment by firstof9** [comment]
We're only looking at the subject and the from address. If the from address isn't 'mcinfo@ups.com' it won't be picked up. However, you can modify the ```const.py``` file and change the ```UPS_Email =``` if that's changed. Downside is every update you'd have to re-edit this file.

**Comment by thisisbenwoo** [comment]
I've deleted and registered a new profile. I'll see if this resolves the issue.

**Comment by moralmunky** [comment]
@firstof9 instructions would be the easiest but could pose problems in the future and will need to be manually updated each new version.

The FROM email address is important for us to keep intact. It's possible that two shippers could end up using the same language in their subject line. If we didn't include the email in our search the counts would be wrong.

The only other suggestion would be to create a dedicated email box for the shipping notifications that HA can check. Within that account, also create a rule to forward all the emails it receives to your family alias.

**Comment by thisisbenwoo** [comment]
Thanks for your advice.


*Ben Woo*
(212) 724-1188
*this*is*ben*woo*@gmail.com <http://gmail.com/>*
