### ISSUE TITLE
ISSUE: UPS packages are not getting counted.  I do have email confirmations

### ISSUE THREAD

**Issue by XmemphistoX** [moralmunky/Home-Assistant-Mail-And-Packages#144]
**Describe the bug**
UPS packages are not getting counted.  I do have email confirmations

**Environment (please complete the following information):**
 - OS: [e.g. CentOS]
 - Type of device: [e.g.VMworkstation]
 - Home Assistant version: [e.g. 0.110.3]
 - Hassio/Docker/Core? Docker
 - Component version: [e.g. 0.2.0]

**Logs**
Paste your error logs here.

**Screenshots**
![UPS](https://user-images.githubusercontent.com/5236235/84526391-1114cd00-ac92-11ea-8480-6ff2c015cf74.PNG)

**Additional context**
UPS Update: Package Scheduled for Delivery Tomorrow

UPS My Choice <mcinfo@ups.com> | UPS My Choice <mcinfo@ups.com>
-- | --
UPS My Choice <mcinfo@ups.com>

Hi Hai Doan, you have a package coming tomorrow. | Hi Hai Doan, you have a package coming tomorrow. | Hi Hai Doan, you have a package coming tomorrow.
-- | -- | --
Hi Hai Doan, you have a package coming tomorrow. | Hi Hai Doan, you have a package coming tomorrow.
Hi Hai Doan, you have a package coming tomorrow.
Scheduled Delivery Date:Friday, 06/12/2020Estimated Delivery Time:09:30 AM - 01:30 PM | Scheduled Delivery Date:Friday, 06/12/2020Estimated Delivery Time:09:30 AM - 01:30 PM | Scheduled Delivery Date:Friday, 06/12/2020Estimated Delivery Time:09:30 AM - 01:30 PM | Scheduled Delivery Date: | Friday, 06/12/2020 | Estimated Delivery Time: | 09:30 AM - 01:30 PM
Scheduled Delivery Date:Friday, 06/12/2020Estimated Delivery Time:09:30 AM - 01:30 PM | Scheduled Delivery Date:Friday, 06/12/2020Estimated Delivery Time:09:30 AM - 01:30 PM | Scheduled Delivery Date: | Friday, 06/12/2020 | Estimated Delivery Time: | 09:30 AM - 01:30 PM
Scheduled Delivery Date:Friday, 06/12/2020Estimated Delivery Time:09:30 AM - 01:30 PM | Scheduled Delivery Date: | Friday, 06/12/2020 | Estimated Delivery Time: | 09:30 AM - 01:30 PM
Scheduled Delivery Date: | Friday, 06/12/2020
Estimated Delivery Time: | 09:30 AM - 01:30 PM

**Comment by firstof9** [comment]
Did you receive an email today stating the package is out for delivery?

**Comment by moralmunky** [comment]
The integration does not monitor emails about future deliveries. The current implementation does not display future deliveries. It only provides a snapshot of what is in transit to be delivered today and what was delivered today.

UPS should send you notifications today about the deliveries they informed you would happen today.

You can see a list of emails and subject line being monitored [here](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/blob/master/info.md).

**Comment by XmemphistoX** [comment]
> The current implementation does not monitor future deliveries. It only provides a snapshot of what is in transit to be delivered today and what was delivered today.
> UPS should send you notifications today about the deliveries they informed you would happen today.
> You can see a list of emails and subject line being monitored here.

Thanks, you are correct - I don't get delivery day notices just future.  Not sure why as I have it checked to get them.  I'll look around.
