### ISSUE TITLE
ISSUE: Custom repo link broken

### ISSUE THREAD

**Issue by smugleafdev** [moralmunky/Home-Assistant-Mail-And-Packages#147]
In the README, in this part:

> Add https://github.com/moralmunky/Home-Assistant-Mail-And-Packages as a custom repository and Type: Integration

"custom repository" link is broken and leads to a 404. As a note, you can have your repo added to the default HACS repo list, as detailed here: https://hacs.xyz/docs/publish/include

**Comment by firstof9** [comment]
Going to need to see a screen shot of this error you are getting.

**Comment by calvinwankhede** [comment]
Simple fix, added a PR.
