### ISSUE TITLE
[Feature Request] Tracking numbers as attributes

### ISSUE THREAD

**Issue by firstof9** [moralmunky/Home-Assistant-Mail-And-Packages#158]
**Is your feature request related to a problem? Please describe.**
Tracking numbers would be great as attributes.

**Describe the solution you'd like**
Tracking numbers as attributes

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by FuzzyMistborn** [comment]
So instead of separate sensors?  Not sure I'm a fan because I'd probably still break out a lot of the information into individual sensors to drive automations.

**Comment by firstof9** [comment]
@FuzzyMistborn the sensors are still separate, just a tracking number attribute added to them.

**Comment by HunterKingNola** [comment]
I'd second this. I really like this add-on, but it does feel like it's odd that there's no quick way to access tracking -- like it gives you a lot of information but just shy of the juicy details. However, I figure this project is still pretty young and I'm very pleased with it where it is, just hope tracking is on the roadmap.

**Comment by firstof9** [comment]
Still testing this.

**Comment by firstof9** [comment]
Looks like I have it working:
![image](https://user-images.githubusercontent.com/1105672/87580803-e355e600-c68c-11ea-98f7-0c5169252c50.png)

**Comment by firstof9** [comment]
Confirmed working.
