### ISSUE TITLE
Integration does not load in 0.102.x

### ISSUE THREAD

**Issue by firstof9** [moralmunky/Home-Assistant-Mail-And-Packages#16]
Integration does not load in 0.102.x, likely some behind the scene changes.

**Comment by jseidl** [comment]
Same, I'm getting the following on the logs:

`Thu Dec 05 2019 14:47:41 GMT-0800 (Pacific Standard Time)
Error while setting up platform mail_and_packages
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 148, in _async_setup_platform
    task = async_create_setup_task()
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 104, in async_create_setup_task
    platform.setup_platform,
AttributeError: module 'custom_components.mail_and_packages.sensor' has no attribute 'setup_platform'
`

**Comment by firstof9** [comment]
@jseidl This is due to having configuration entries in your config files, I'm working on allowing that as well as the integration configuration.

**Comment by jseidl** [comment]
I've added the `mail_package.yaml` from `includes/packages/` file into my `packages` folder. Isn't supposed to add that?

**Comment by firstof9** [comment]
No the instructions need adjusting as well, sorry, all you need is the custom_component directory.

**Comment by jseidl** [comment]
Where should the configuration for the email server be entered?

**Comment by firstof9** [comment]
> I've found the integration, took a while because the strings are not showing up for me.

This should be fixed in PR #17
