### ISSUE TITLE
ISSUE: 0.2.1-b9 Error while setting up mail_and_packages platform for sensor

### ISSUE THREAD

**Issue by mbaran5** [moralmunky/Home-Assistant-Mail-And-Packages#160]
**Describe the bug**
Integration is not correctly working, throwing this error on launch. 

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/mail_and_packages/sensor.py", line 130, in async_setup_entry
    CONF_GENERATE_MP4: entry.data[CONF_GENERATE_MP4],
KeyError: 'generate_mp4' `

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: VM
 - Home Assistant version: 0.111.4 
 - Component version: 0.2.1-b9

**Logs**
Pasted above with error

**Comment by moralmunky** [comment]
A new configuration option was added. Navigate to Configuration > Integrations > Mail and Pakckages Options. Step through the two confit screens. You may need to toggle the new mp4 option on then off, or just on if you would like to use it.

**Comment by mbaran5** [comment]
That worked, thank you. I notice that the mp4 it creates is 0kb, is that intentional?

**Comment by firstof9** [comment]
No it should be some KBs big. Usually if it's 0KB that means an error occurred.
Can you post your system info box from Home Assistant?
Example:
![image](https://user-images.githubusercontent.com/1105672/85311900-f5b47980-b46a-11ea-94e6-107607c554af.png)

**Comment by mbaran5** [comment]
I can close this now. After the first check of mail it created an mp4 that could be played.
