### ISSUE TITLE
[Feature Request] Add shipper: DHL

### ISSUE THREAD

**Issue by ttaidapos** [moralmunky/Home-Assistant-Mail-And-Packages#164]
**Is your feature request related to a problem? Please describe.**
Enable support for DHL shipping service?

**Describe the solution you'd like**
Love to have option like we have with Fedex/UPS etc.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by firstof9** [comment]
Can you provide the from address and subject lines of emails from DHL?

**Comment by ttaidapos** [comment]
> Can you provide the from address and subject lines of emails from DHL?

From Address:  donotreply_odd@dhl.com, support@dhl.com
Subject:  DHL On Demand Delivery, DHL Shipment Notification : ########## (Where ########### is the tracking number)

**Comment by moralmunky** [comment]
At the moment the integration only tracks activity the day of delivery. Is this email sent the day of delivery? Do they provided notice that a package will be delivered and the. Has been delivered?

You can see example of what is triggering the integration in the read me for the other carriers.

**Comment by ttaidapos** [comment]
> At the moment the integration only tracks activity the day of delivery. Is this email sent the day of delivery? Do they provided notice that a package will be delivered and the. Has been delivered?
> 
> You can see example of what is triggering the integration in the read me for the other carriers.

Checked a few shipments the last few months.  You get two email notifications, one on day of delivery and another when it's delivered.

**Comment by moralmunky** [comment]
Is the subject line the same for both emails? If so, can you provide the language in the email body for each that indicates what the notification is for?

**Comment by ttaidapos** [comment]
> > Can you provide the from address and subject lines of emails from DHL?
> 
> From Address: [donotreply_odd@dhl.com](mailto:donotreply_odd@dhl.com), [support@dhl.com](mailto:support@dhl.com)
> Subject: DHL On Demand Delivery, DHL Shipment Notification : ########## (Where ########### is the tracking number)

Ok these are the corrected ones, apparently for this shippment I not only had email notifications by explicitely setup "extra" notifications for the same shippment.  Below is all you need.

From Address: donotreply_odd@dhl.com
Subject: DHL On Demand Delivery

**Comment by ttaidapos** [comment]
> Is the subject line the same for both emails? If so, can you provide the language in the email body for each that indicates what the notification is for?

**Delivery Notification**
From Address: donotreply_odd@dhl.com
Subject: DHL On Demand Delivery
```YOUR DELIVERY IS TODAY
 	
Hello fname lname,
 
Your DHL Express shipment with waybill number [tracking#] from [supplier] is scheduled for delivery TODAY by End of Day.

If you need to make a change or track your shipment, click here.

DELIVERY INFORMATION
Waybill No.
[tracking#]
Delivery Address
[address]
 
Thank you for using On Demand Delivery.

DHL Express - Excellence. Simply delivered.
 
Deutsche Post DHL Group	 	
DHL Express | Contact DHL | Privacy Policy | Unsubscribe

2018 © DHL International GmbH. All rights reserved.
```

**Delivered Notification**
From Address: donotreply_odd@dhl.com
Subject: DHL On Demand Delivery
```
DELIVERED!
 	
Hello fname lname,
 
Your DHL Express shipment with waybill number [tracking#] from [supplier] has been delivered on Thu Sep 19 at 09:56. For more details, click here.

Thank you for using On Demand Delivery.
 
DELIVERY INFORMATION
Waybill No.
[tracking#]
Delivery Address
[address]

DHL Express - Excellence. Simply delivered.
 
Deutsche Post DHL Group	 	
DHL Express | Contact DHL | Privacy Policy | Unsubscribe

2019 © DHL International GmbH. All rights reserved.
```

**Comment by moralmunky** [comment]
Do you have to sign up for MyDHL+ to receive these notifications? If not, how do you get notifications?

**Comment by ttaidapos** [comment]
> Do you have to sign up for MyDHL+ to receive these notifications? If not, how do you get notifications?

All you need to do is sign up using the site below.  No extra settings in your account etc.   As long as you physical address matches the delivery destination, you will receive an email notifications to the email address setup in DHL.

Sign up here:  https://delivery.dhl.com/login.xhtml

**Comment by firstof9** [comment]
Should have a beta for this available in the morning.

**Comment by ttaidapos** [comment]
Unfortunately counts are not being updated for delivering/delivered.

![image](https://user-images.githubusercontent.com/27898709/94826820-55f17a80-03cd-11eb-94d6-8514be5b279a.png)

![image](https://user-images.githubusercontent.com/27898709/94827032-95b86200-03cd-11eb-8b66-2d1c5017f543.png)

![image](https://user-images.githubusercontent.com/27898709/94827071-a072f700-03cd-11eb-8f6d-a9a2ebb9db8b.png)

![image](https://user-images.githubusercontent.com/27898709/94827154-b84a7b00-03cd-11eb-8570-47e040ef38c0.png)

**Comment by ttaidapos** [comment]
tracking number populated.

Email sent.  Thank you!

**Comment by firstof9** [comment]
Looks like they changed the `from` address.

**Comment by ttaidapos** [comment]
> Looks like they changed the `from` address.

I should have caught that!  Sorry

**Comment by firstof9** [comment]
No problem, more emails for the unit tests are super helpful either way.
b32 released.
