### ISSUE TITLE
Allow for more than one email to be checked for deliveries [Feature Request] 

### ISSUE THREAD

**Issue by brad5874** [moralmunky/Home-Assistant-Mail-And-Packages#169]
I have a couple of email addresses that I utilize for these services

It would be great to be able to configure this customization to check more than one email address.

I tried forwarding the emails from the various services to one email address but that doesn't work due to the email not being from the service directly.  Just a friendly suggestion.  Great work on this!!

**Comment by firstof9** [comment]
You can add multiple instances of the integration to check other mailboxes.

**Comment by firstof9** [comment]
Let me know if this resolves the issue for you. Thanks.
