### ISSUE TITLE
ISSUE: Installation not working via HACS or Manual 

### ISSUE THREAD

**Issue by ryanlocey** [moralmunky/Home-Assistant-Mail-And-Packages#173]
**Describe the bug**
i have attempted to install via HACS and manually and the integration does not show up under Configuration -> Integrations.  i have validated that the folder mail_and_packages is installed under custom components.

**Environment (please complete the following information):**
 - Type of device: RPi4
 - Component version: v0.2.1-1

arch | armv7l
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.8
hassio | true
host_os | HassOS 4.11
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v7l
python_version | 3.7.7
supervisor | 228
timezone | America/Chicago
version | 0.112.3
virtualenv | false

**Logs**
Paste your error logs here.

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment]
Refreshing the integrations page fixes this issue. I believe you've already posted on the forum that this resolved it for you?
