### ISSUE TITLE
Scan interval not running

### ISSUE THREAD

**Issue by starguy24** [moralmunky/Home-Assistant-Mail-And-Packages#174]
Everything is set up as directed and was running fine until about 2 days ago. The scan interval is set for every 10 minutes, but I'm having to change it manually every day to push it to scan. Once I do that, it picks up whatever is in the designated email. When I look up how often it scans, in one case it was up to 37 hours.

Not sure if I need to empty the cache or if it's a bigger problem developing.

**Comment by moralmunky** [comment]
Are you not seeing the sensor.mail_updated update the time? Have you turned on debug in the logs to see if the scripts is running through the steps?

**Comment by moralmunky** [comment]
Also, what version of Hass and version of mail and packages are you running?

**Comment by starguy24** [comment]
"Are you not seeing the sensor.mail_updated update the time?"

So I went back and added the Mail updated sensor to the card I have my sensors grouped on. That's showing it updating at the scan interval. It was the other sensors that weren't updating; like the other day the Amazon sensor picked up an incoming package only after I'd manually triggered it with a scan interval change and then I had to do it the next day to clear that package. But even with the sensor.mail_updated, it doesn't necessarily seem to actually be updating (like an hour after midnight local, it'll still show the previous day's mail information).

The mail_today.gif updated today on its own after the USPS email came in and I had added the sensor.mail_updated to the UI earlier this morning. But the last two days it required a manual trigger to change/update.

"Have you turned on debug in the logs to see if the scripts is running through the steps?"

I am ashamed to admit this, I'm still fairly new to HA and am learning how to do things like that. I haven't done that yet as I'm not sure where to do that, but it would be good to do to get some more clarity.

"Also, what version of Hass and version of mail and packages are you running?"

HassOS 4.11 and core 111.4; Mail and Packages 0.2.1-1...it was running fine on the core up until just a couple days ago.

**Comment by firstof9** [comment]
> "Have you turned on debug in the logs to see if the scripts is running through the steps?"
> 
> I am ashamed to admit this, I'm still fairly new to HA and am learning how to do things like that. I haven't done that yet as I'm not sure where to do that, but it would be good to do to get some more clarity.

We have a [wiki section](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Troubleshooting#enable-debugging) for how to do this.



> It was the other sensors that weren't updating; like the other day the Amazon sensor picked up an incoming package only after I'd manually triggered it with a scan interval change and then I had to do it the next day to clear that package. But even with the sensor.mail_updated, it doesn't necessarily seem to actually be updating (like an hour after midnight local, it'll still show the previous day's mail information).

The debuging info will help figure this out. Also check your Home Assistant log for errors from `Mail And Packages` as well.

**Comment by starguy24** [comment]
Thanks for the clarification and the wiki link; I was having trouble finding thag. Not sure if I'll be able to get into the system tonight. If I can, I'll get the debug set up.

I had checked the HA log for some other things yesterday and this morning. No errors were showing up in that feed for Mail and Packages.

**Comment by starguy24** [comment]
So, I have the debug running in the config and nothing is showing an error. The one change that seemed (for unexplained reasons) is that I added the Updater to the Lovelace GUI card that I have for right now. When I put that on there, things seemed to start updating again yesterday with the Mail gif. When I click on the icons though, the Updater is the only one that will show a recent check and anything else (i.e. the gif and USPS packages, Amazon, etc) will only show a change to the update time if something has changed.

So for right now I'll close this, but will reopen it if anything new comes up.

![Screenshot 2020-07-12 14 18 48](https://user-images.githubusercontent.com/63473539/87255771-ebbede80-c44a-11ea-8b67-2d80f84d6af8.png)
