### ISSUE TITLE
[Feature Request] Enable Shippers as a configuration option set

### ISSUE THREAD

**Issue by ryanlocey** [moralmunky/Home-Assistant-Mail-And-Packages#178]
**Is your feature request related to a problem? Please describe.**
Would like to be able to enable/disable shippers that i do not care about.  ex: (i live in the US and do not need to track CA Post)

**Describe the solution you'd like**
Would like to have a page to toggle on and off shippers

**Describe alternatives you've considered**
manually going into the code and commenting out the shippers

**Comment by firstof9** [comment]
I don't see why we wouldn't be able to do this.

**Comment by firstof9** [comment]
Work in progress:
![image](https://user-images.githubusercontent.com/1105672/87484468-1a73bb00-c5eb-11ea-9fb4-2811eb76526d.png)

**Comment by firstof9** [comment]
Feature implemented in 0.2.2-b7, give it a test go.

**Comment by ryanlocey** [comment]
Awesome. I’ll load it now.

**Comment by ryanlocey** [comment]
Appears to be working perfectly. Thanks for the quick turnaround
