### ISSUE TITLE
[Feature Request] configure time for email polling

### ISSUE THREAD

**Issue by ryanlocey** [moralmunky/Home-Assistant-Mail-And-Packages#180]
not an issue, but would be a good feature to implement to save on machine resources

**Describe the solution you'd like**
Would like to see a way to configure a time range for the polling of the email box that way there is no unnecessary polls around the clock.

**Comment by firstof9** [comment]
Problem is shippers do not always send their emails "from 9 to 5".
Is there a problem with it checking your email at regular intervals? You could always increase the interval as well.

**Comment by ryanlocey** [comment]
no issue, was just noticing it updating the time all day and thought it was unnecessary

**Comment by firstof9** [comment]
Based on exploring multiple components in Home Assistant, it doesn't seem like there's a way to implement this. All components poll at XX frequency. Feel free to adjust your polling to longer times if you like.
