### ISSUE TITLE
Not Recognizing Packages  

### ISSUE THREAD

**Issue by akcamperdude** [moralmunky/Home-Assistant-Mail-And-Packages#184]
**Describe the bug**
Packages aren't showing up.

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: RPi4B+
 - Home Assistant version: 0.112.4
 - Hassio
 - Component version: 0.2.1

**Logs**
None I can't find related to this addon

**Screenshots**
NA

**Additional context**
Email attached to the system correctly, sensors operational, but emails that seem to meet all the requirements never show up. In fact I have not been able to get a single package to show up: Amazon, USPS, etc.

**Comment by moralmunky** [comment]
If you have not already, please turn on debug for the integrations logs. See if some details or refer to Hass documentation.


https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Troubleshooting

Just to check. The email address you are using for the integration is receiving the original messages from the carriers or are they forwarded from a other account? Are the messages in the folder that you chose in the integration setting and not getting deleted?

**Comment by akcamperdude** [comment]
Added the additional debugging with no additional information (still no logs). The email address is definitely getting the updates directly and everything is set to INBOX. I have mostly received Amazon packages since getting this up and running, and I wonder if it's due to how Amazon sends their emails? I am realizing that I do not ever receive an "out for delivery email", only an email when it ships with tracking information. I got one UPS that said "scheduled for delivery tomorrow" but it looks like that might not meet the requirements if it's not "today".

**Comment by firstof9** [comment]
Packages only show up on the day of delivery.
Please see the [how it works](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki#how-it-works) section of the wiki and the [shippers configuration](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Configuration-and-Email-Settings#supported-shippers-and-requirements) section.

**Comment by akcamperdude** [comment]
My configuration may be the issue for UPS, but I don't see a configuration guide for Amazon.

**Comment by moralmunky** [comment]
I don't believe amazon provides options to modify their email notifications settings.

Turning on debug provides several lines of information each time the integrations checks email. If you are not seeing anything at all, turning debug on was not correct or the integration is not installed correctly.

Please provide more information.

**Comment by firstof9** [comment]
Feel free to reopen if the issue persists.
