### ISSUE TITLE
[Feature Request] Add more robustness to Amazon sensors

### ISSUE THREAD

**Issue by firstof9** [moralmunky/Home-Assistant-Mail-And-Packages#186]
**Is your feature request related to a problem? Please describe.**
More Amazon robustness

**Describe the solution you'd like**
Track the 'delivered' email for amazon, maybe even include the image from the email?

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by firstof9** [comment]
From: order-update@amazon.com
Subject: Delivered: Your Amazon.com order #xxx-xxxxxxx-xxxxxxx

Image embeded in text/html:
<img class="largeImage" src="https://us-prod-temp.s3.amazonaws.com/imageId-[redacted]" alt="A photo of your delivery location" style="border: 0" />

**Comment by firstof9** [comment]
This works for my test case, but will need wider testing to make sure it's working as expected.

**Comment by moralmunky** [comment]
Will the amazon delivery email need to be internationalized like the shipment-tracking?

https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/blob/e5593902ed866db0c26a77917725e4cc4a8c2624/custom_components/mail_and_packages/const.py#L70

**Comment by firstof9** [comment]
> Will the amazon delivery email need to be internationalized like the shipment-tracking?
> 
> https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/blob/e5593902ed866db0c26a77917725e4cc4a8c2624/custom_components/mail_and_packages/const.py#L70

Oops, knew I forgot something lol ya I'll have it loop with the domains.

**Comment by moralmunky** [comment]
I've added this to the wiki. Please make any adjustments as needed. It appears the delivered notification is working the same as the other shippers on the current day only.

> Amazon uses a several of the shippers listed above a long with their own contractor delivery crew. When amazon ships through an outside carrier the integration will pick those emails and display the count through that shippers sensors. When Amazon ships through an internal contractor they provide a shipping notification with the body text "will arrive:" about 2 or 3 days before they expect it to be delivered.
> 
> The integration scans for these emails the current day and previous 2 days. If the "deliver by:" date matches the current day the value is increased by 1. Amazon now provides a delivered notification* for internal contractor deliveries. These emails are searched for in the current day only the same way the other shipper delivered emails are counted.

**Comment by firstof9** [comment]
Latest PR/beta should cover the international emails now.

**Comment by firstof9** [comment]
ToDo: Need a "no packages" placeholder.

**Comment by FuzzyMistborn** [comment]
As an addition to this, I think the Amazon image should be converted to a GIF.  Having my second day of multiple Amazon deliveries.  May be slightly more complicated than the USPS one because sometimes multiple orders are delivered at the same time and use the same image.  Honestly I'd even take the same image showing up for longer.

**Comment by firstof9** [comment]
So like an animated gif like the USPS mail?

**Comment by FuzzyMistborn** [comment]
Yeah I think so.  I find it hilarious that Amazon isn't more efficient with putting all the deliveries on the same truck (maybe it's just growing pains, this is only the first month they've been operating in my area) but it's happened at least twice now.

**Comment by FuzzyMistborn** [comment]
Actually, I just had the second delivery and it sent a different image.  So I guess the normal jpg will work.

**Comment by firstof9** [comment]
Considering this as working.
