### ISSUE TITLE
Can't Import Amazon Emails

### ISSUE THREAD

**Issue by dmintz7** [moralmunky/Home-Assistant-Mail-And-Packages#189]
Receiving the below error after Amazon email is successfully found. 
` Error while attempting to parse Amazon email: 'utf-8' codec can't decode byte 0xdb in position 402: inalid continuation byte`

Email is received via gmail in Plain Text format

**Comment by firstof9** [comment]
It's safe to ignore this message, it doesn't cause any problems.

**Comment by dmintz7** [comment]
The email is failing to be processed. Why is it safe to ignore?

**Comment by firstof9** [comment]
Did you get a "items have shipped" email?
