### ISSUE TITLE
Mail hooked up but images not showing

### ISSUE THREAD

**Issue by FunPsycho** [moralmunky/Home-Assistant-Mail-And-Packages#19]
I know the add-on is working because it says I am getting mail, but the images do not show up.  I am using HassOS and installed imageMagick by following the advice here: https://community.home-assistant.io/t/imagemagick/68390/4

I also have an email from UPS saying a package is going to be delivered tomorrow, but the text on the card says I don't have any upcoming packages.  Is that supposed to catch those emails as well?

I don't see anything in the logs, but I am assuming I don't have imagemagic installed or configured correctly. I assume I got the integration with outlook correct because the add-on knows I have mail.  

Just don't know where to check for an error or check to see if everything is installed correctly.

Thanks for the help.

**Comment by FunPsycho** [comment]
So I think I found the source of one of the problems, but cannot find where the value is being set.

It says in my log that it cannot find a file at this location:
Error attempting to remove image: [Errno 2] No such file or directory: '/config/www/mail_and_packagesmail_today.gif'

Now it should be '/config/www/mail_and_packages/mail_today.gif' it is missing that last '/'

it is coming from sensor.py but that doesn't have a hard coded path in it.  And that was a path I had changed during installation, but cannot find where it is at.

**Comment by firstof9** [comment]
That's in the integration configuration. Delete the integration and re-add it to reconfigure it.

**Comment by FunPsycho** [comment]
OK. I'll try that and update the issue with the resolution. Thanks

**Comment by FunPsycho** [comment]
reinstalled the entire plugin and now it gives this error:

/config/www/mail_and_packages/image-no-mailpieces700.jpg
I cannot find this path either.

I am going to try to just reinitialize the integration and see if that fixes it or not this time.

**Comment by moralmunky** [comment]
That file exists in the github repository. Does that file exist in your file system at that path?

**Comment by FunPsycho** [comment]
No. I'll look at the directory on GitHub and compare. I guess if it deletes the file though it will be gone after I copy it over though right? Or does it replace it after it deletes it with a new gif?

**Comment by FunPsycho** [comment]
I added the file from the repo and it did what I expected it to do. It just deleted the file and now I am getting that error again.

**Comment by FunPsycho** [comment]
So now I am not getting any errors and it is still not working.  My Today.gif never actually gets made even though my email shows images. Could I have installed imagemagick incorrectly?  I just used apk add --update imagemagick and it just installed it somewhere.  I am running HASS OS on RBP4

I might try to reinstall it again

**Comment by FunPsycho** [comment]
Tried reinstalling it again and now it's just not showing the images.  I also have 4 ups packages in transit and it still says there are zero. Should I even open bugs for these?

**Comment by FunPsycho** [comment]
Meaning I don't know how to read the logs and have no way to trace where the error is coming

**Comment by firstof9** [comment]
> Meaning I don't know how to read the logs and have no way to trace where the error is coming
Create a new issue, and provide the subject line of the UPS email(s) in the issue.

> Could I have installed imagemagick incorrectly? I just used apk add --update imagemagick and it just installed it somewhere. I am running HASS OS on RBP4

Have you checked the thread on the forum about how to install imagemagick in to the docker image?

**Comment by FunPsycho** [comment]
> Have you checked the thread on the forum about how to install imagemagick in to the docker image?

The thread I mentioned above? Yeah I SSH into my Hassio instance and ran the command mentioned.  

i reinstalled the addon again and now nothing is working correctly. I'm going to have to start over again and I might reinstall hassio>

I don't think it should be this hard, it seems pretty straight forward.

**Comment by FunPsycho** [comment]
I don't know why but when i looked again imagemagick was not installed. I'll close this for now because I am having other issues and cannot load the integration.  I'll reopen if I see this behavior again.
