### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by TZombiEd** [moralmunky/Home-Assistant-Mail-And-Packages#192]
Add option for tracking Amazon packages similar to other carriers.  This request includes changes to the integration, the custom card and the text sensor template

If option selected include Amazon package deliveries in the way implemented for the other carriers.  Since Amazon normally only sends email notifications if items are shipped by Amazon, there should not be duplication if items are shipped by an other carrier such as UPS, USPS, or FedEx.  
In transit sensor should include amazon shipments.  The sensor.mail_deliveries_message already includes Amazon in transit notifications but doesn't include estimated delivery date.  If possible include the delivery dates in the summary message.

If, though there are no shipments from a carrier, the summary message text really does not need to include “No xxx packages are in transit.  For example, if In Transit is 0,  the summary doesn't need to list all the carriers saying the don't have packages in transit.  However, the total number reported in the summary should match the in-transit sensor. 

Out for Delivery: Amazon and some of the carriers do send an out for deliver notification, Perhaps include a separate sensor for this as well as adding text for the sensor.mail_deliveries_message.  

Once a delivered email is received, the both the sensor and message should reflect that.
Finally provide a space for Amazon delivered sensor, perhaps by leaving the mail sensor on the current line and moving the package delivered sensors to the next line along with the Amazon package sensor.

The custom card is key to having a nice compact summary of my packages and mail deliveries.  Without the card, the alternative is to use existing cards to replicate as much as possible the format of the custom card.

**Comment by firstof9** [comment]
Please keep in mind the custom card repo is: https://github.com/moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card
