### ISSUE TITLE
Amazon Deliveries are not included in sensors.mail_pacakges_delivered or sensors.mail_packages_in_transit

### ISSUE THREAD

**Issue by badi95** [moralmunky/Home-Assistant-Mail-And-Packages#197]
Deliveries from Amazon are not showing up in the sensors.mail_packages_delivered or sensors.mail_packages_in_transit.

Environment
 - OS: Ubuntu 20.04 [hassio supervisior container]
 - Type of device: RPi4
 - Home Assistant version: 0.113.2
 - Docker
 - Component version: 0.2.2-b15

Digging around in the code a bit, it seems like amazon isn't included in the "shipper" variable or "SHIPPERS" list which is iterated through to populate the zpackages_delivered and zpackages_transit

**Comment by firstof9** [comment]
This is because Amazon is anomalous and doesn't send "out for delivery" emails like the other shippers, so they are basically handled separately, similar to the CAPost.
