### ISSUE TITLE
[Feature Request] Add support for Amazon Hub package locker codes.

### ISSUE THREAD

**Issue by bransjr** [moralmunky/Home-Assistant-Mail-And-Packages#206]
Is your feature request related to a problem? Please describe.

When I receive a package to my apartment building, amazon puts them in a package locker and emails me a code. The email they send has the code in the subject line. 

Describe the solution you'd like

It would be nice to have a sensor that puts those codes into a comma separated list that I can then interact with in automations or Node red, such as triggering an automation to send those codes via notification when I arrive home, or trigger them to be sent to my SO when she arrives home. The subject line is "You have a package to pick up at the Apartment Building Name Hub - ######" and the email comes from thehub@amazon.com
This portion could be setup as an option by entering you apartment building name into an optional field during set-up.

**Comment by firstof9** [comment]
Is it always a 6 digit combo?

**Comment by bransjr** [comment]
Obviously I am only one person, but for me it always has been.

**Comment by bransjr** [comment]
And I to clarify "Apartment Building Name" was a placeholder

**Comment by firstof9** [comment]
I figured it was lol
I'll see what I can do.

**Comment by bransjr** [comment]
You're amazing

**Comment by firstof9** [comment]
Notes:
SUBJECT: "You have a package to pick up at the Apartment Building Name Hub - ######"
FROM: thehub@amazon.com
REGEX: "(You have a package to pick up)(.*)\- (\d{6})"

**Comment by firstof9** [comment]
This is still on my list, I haven't forgotten about it.

**Comment by firstof9** [comment]
Should be handled by b26 now. Let me know.

**Comment by bransjr** [comment]
Sorry, I would live to test this but how do I get it installed?

**Comment by firstof9** [comment]
Update to beta 26 via HACS

**Comment by bransjr** [comment]
Will do tonight. Thanks

**Comment by bransjr** [comment]
Its installed and the integration is working. I have no packages coming. What are the constraints on the forwarded email? Can I forward an old hub email and it should work? I tried that and no luck. I did set up that address as "Amazon forwarded email addresses" in settings and no luck. 

Other than forwarding, I have packeges coming Friday.

**Comment by firstof9** [comment]
You should be able to add the email address it was forwarded from to the "Amazon forwarded email addresses", example if you fwd it to yourself, you'd put your email address in the field.

That's how it's supposed to work at least, no one's reported any issues with it so far.

**Comment by bransjr** [comment]
OK, I have not received any emails directly to my mail tracking email yet, but had one forwarded. It is not working. Let me know what you need from me for troubleshooting and I will happily provide it.

**Comment by firstof9** [comment]
Ya I think I narrowed down a bug in the fowarding bit, I have it fixed in 0.3.x branch (added unit tests to find issues before hand 🎉 )

I could use a email dump of the Amazon Hub email when you get one so I can add tests for it. If you're willing let me know I can walk you through how to get the dump

**Comment by bransjr** [comment]
Absolutely. I got one directly today. Let me know where to send it. The sensor didn't work, I dont think.

**Comment by bransjr** [comment]
let me know how to do the dump

**Comment by firstof9** [comment]
Are you using Gmail?

**Comment by bransjr** [comment]
Yes

**Comment by bransjr** [comment]
This is waht I see in ha, with 1 forwarded and two direct hub codes
![Screenshot_20200925-204812_Home Assistant](https://user-images.githubusercontent.com/61677635/94327420-90dc5400-ff70-11ea-9f1f-10675c658215.jpg)

**Comment by firstof9** [comment]
Ok so hit the 3 dots on the right:
![image](https://user-images.githubusercontent.com/1105672/94327693-9e3e1200-ff61-11ea-9765-49357b77e70b.png)
Click `Show Original`
Then `Download Original`
![image](https://user-images.githubusercontent.com/1105672/94327714-b746c300-ff61-11ea-8fe2-d56971023e9a.png)

Once you have the `.eml` file feel free to sanitize your order number and such (please replace with XXXX but keep the format).
Ie (Order number: #XXX-XXXXXXX)

Then attach the file here.

**Comment by bransjr** [comment]
Apologies for the delay. They should be in your inbox now

**Comment by bransjr** [comment]
One of them is a "final reminder" which isn't important to my use case. I didnt realize it until I had already sent. The other two are normal.

**Comment by firstof9** [comment]
I'll take a look and get hub support in soon as I can, thanks for the data!

**Comment by firstof9** [comment]
Alright this should be in b31, I've tested it against the email you provided and it seemed to work as expected.
Let me know when you get a chance.

**Comment by bransjr** [comment]
Updating now

**Comment by bransjr** [comment]
Got my first Amazon package in a while and it is working great. Thanks!!

**Comment by firstof9** [comment]
Thanks for the feedback.
