### ISSUE TITLE
[Feature Request] Does this integration support Amazon Canada, UPS, etc?

### ISSUE THREAD

**Issue by jayscovill** [moralmunky/Home-Assistant-Mail-And-Packages#209]
I don't see it specifically mentioned and I have tested in the past and it didn't at that time.

Thanks!

**Comment by firstof9** [comment]
Amazon Canada is in the code:
https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/blob/5906bffa83a41600ea098a8a5f458cc446e5278a/custom_components/mail_and_packages/const.py#L45
