### ISSUE TITLE
[Feature Request] Add support for Fedex Canada

### ISSUE THREAD

**Issue by jayscovill** [moralmunky/Home-Assistant-Mail-And-Packages#215]
**Is your feature request related to a problem? Please describe.**
Can you add support for Fedex Canada delivery notices?

Email address: fedexcanada@fedex.com

Example email:

![image](https://user-images.githubusercontent.com/30603659/92780502-456f5680-f371-11ea-9b8f-0d6724e520d2.png)

**Comment by jayscovill** [comment]
![image](https://user-images.githubusercontent.com/30603659/92781077-cb8b9d00-f371-11ea-8169-757acb8cdcce.png)

**Comment by firstof9** [comment]
I'll see what I can do to fix that.

**Comment by jayscovill** [comment]
Awesome! Cheers!

**Comment by firstof9** [comment]
b25 should grab these now, give it a shot.
