### ISSUE TITLE
ISSUE: Not counting FedEx email 'delivering tomorrow' in FedEx Delivering sensor

### ISSUE THREAD

**Issue by rpitera** [moralmunky/Home-Assistant-Mail-And-Packages#218]
**Describe the bug**
My expectation of the "delivering" sensors is that it would count emails that state 'your package is being delivered tomorrow' or 'your package is scheduled for delivery tomorrow' as in transit packages at the least.  But I'm not seeing this behavior and instead counts only show up when something is being delivered TODAY.  Is my understanding incorrect or is this actually unexpected behavior?  I've included an example of a FedEx delivery that will be delivered tomorrow, though nothing is showing in my mail_fedex_delivering sensor.

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: Ubuntu VM running in Virtual Box
 - Home Assistant version: 0.114.4
 - Hassio
 - Component version: 0.2.2-b25

**Logs**
No errors

**Screenshots**
![FedExTomorrow](https://user-images.githubusercontent.com/19910294/93225363-217c8e00-f740-11ea-8bb0-55714fae13b5.png)

**Additional context**
PlainText email provided, personal info redacted or altered

[FedEx Shipment 9177448XXXXX_ Your package is scheduled for delivery tomorrow.txt](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/files/5225773/FedEx.Shipment.9177448XXXXX_.Your.package.is.scheduled.for.delivery.tomorrow.txt)

**Comment by firstof9** [comment]
Nope, per [the wiki](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki#how-it-works) only the current day's deliveries. You can review the [search terms](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki#search-terms) as well in the wiki.

**Comment by rpitera** [comment]
Thanks, Chris.  I figured as much but wanted to be sure otherwise what's the point of me testing all these betas! LOL

Search terms table is a really nice addition to the docs!  Thanks for pointing me to it. And I appreciate the quick response!

(BTW, it says something that this is the first time in a while that I even found something worth asking about.  Betas have been pretty solid for me and development is coming along nicely. )
