### ISSUE TITLE
setter is defined without getter

### ISSUE THREAD

**Issue by zarurc** [moralmunky/Home-Assistant-Mail-And-Packages#22]
Getting this when Hassio boots up: 
> mail_and_packages/mail_and_packages.js?v=.01:1:1 Uncaught SyntaxError: Unexpected token '<'

then in mail_and_packages.js the error is on line 2:

> setter is defined without getter

**Comment by firstof9** [comment]
Can you paste line 2 from your ```mail_and_packages.js``` file?

**Comment by moralmunky** [comment]
Creating a new custom card. Will publish the repository when it. is ready.
