### ISSUE TITLE
ISSUE: Unable to set up multiple instances if both are same email provider

### ISSUE THREAD

**Issue by singhj0910** [moralmunky/Home-Assistant-Mail-And-Packages#220]
**Describe the bug**
Trying to create two Amazon sensors from sperate accounts to eventually combine into one sensor but only allows for one or the other. When adding sensors from the new account, the same sensors from the old account are completely removed and replaced instead of keeping both with different names. 

**Logs**
Platform mail_and_packages does not generate unique IDs. ID imap.gmail.com_Mail Amazon Packages already exists - ignoring sensor.mail_amazon_packages
Platform mail_and_packages does not generate unique IDs. ID imap.gmail.com_Mail Amazon Packages Delivered already exists - ignoring sensor.mail_amazon_packages_delivered
Platform mail_and_packages does not generate unique IDs. ID imap.gmail.com_Mail Amazon Hub Packages already exists - ignoring sensor.mail_amazon_hub_packages

**Additional context**
The emails are sent to two separate accounts, but both are Gmail.

**Comment by firstof9** [comment]
b27 should resolve this, give it a spin.

**Comment by firstof9** [comment]
Looks like we're up to b30, let me know how it goes @singhj0910

**Comment by singhj0910** [comment]
Sorry for the late reply. The issue is completely solved now. Thank you for everything!
