### ISSUE TITLE
[Feature Request] Add Support for DHL Germany

### ISSUE THREAD

**Issue by LooneyN** [moralmunky/Home-Assistant-Mail-And-Packages#227]
Can you add support for DHL Germany notices?

Email address: noreply@dhl.de

Example email:
Will Arrive soon E-Mail
Title: Ihr Amazon Paket kommt bald. Wann und wo möchten Sie es empfangen? Jetzt festlegen
![Will Arrive soon](https://user-images.githubusercontent.com/30878831/94362882-caff4000-00ad-11eb-880a-21d58aad83ea.jpg)

Will Arrive today E-Mail
Title: Ihr Amazon Paket kommt heute. Jetzt Ablageort buchen
![Will Arrive today](https://user-images.githubusercontent.com/30878831/94362992-82945200-00ae-11eb-8d62-891729d52eb5.jpg)

**Comment by LooneyN** [comment]
Black/Green stuff are my rough translations :3

**Comment by firstof9** [comment]
Would you be ok with sending the raw email to me so I can test with it?

You can remove your name from the email contents, but it'd be best to keep the tracking number intact, I'd only need the 2nd email.

**Comment by LooneyN** [comment]
Yes, sure! What mail address should I send it to?

**Comment by firstof9** [comment]
firstof9@gmail.com

**Comment by firstof9** [comment]
I'll see what I can get done.
