### ISSUE TITLE
Install Imagemagick as a requirement

### ISSUE THREAD

**Issue by FuzzyMistborn** [moralmunky/Home-Assistant-Mail-And-Packages#23]
Feature request to add imagemagick as a dependency/requirement when using the custom component.  Every time I update HASS (running in Docker) i need to build a custom image to include imagemagick which is annoying.  I've found a fairly painless solution but it would be nice to not have to do (and it seems like one of the main issue folks have getting this to work).

**Comment by firstof9** [comment]
Going to look into potential other python libraries that wouldn't require external libraries to be installed.

**Comment by firstof9** [comment]
@FuzzyMistborn I've tinkered and uploaded some tweaks, yet haven't tested them yet, on my repo.
If you'd like you can pop over there and give them a whirl, it should install a new python library.

I'll try testing it out later today.

**Comment by FuzzyMistborn** [comment]
Cool, i'll try to get it set up tonight to test in the next few days on my dev instance.

**Comment by FuzzyMistborn** [comment]
Didn't have a ton of time tonight but tried to install and got this error on boot:
`2020-02-11 20:25:56 ERROR (MainThread) [custom_components.mail_and_packages.sensor] Error attempting to generate image: Image is not numeric, but str.
`

**Comment by firstof9** [comment]
Ya I made some changes and keep getting a ```Error attempting to generate image: can only concatenate str (not "list") to str```

I'll keep plugging away when I have time.

**Comment by firstof9** [comment]
@FuzzyMistborn I just pushed new files to the branch, give them a go. I confirmed they worked in my Home Assistant Docker image and generated the animated gif properly.
