### ISSUE TITLE
Issue: extra keys not allowed @ data['platform']

### ISSUE THREAD

**Issue by hermy65** [moralmunky/Home-Assistant-Mail-And-Packages#236]
New HA user here so maybe im just missing something. Ive added everything to my configuration.yaml but every time i restart my server i get an error that says: **extra keys not allowed @ data['platform']**

If i remove the camera: portion then it restarts without issue so it has to be something to do with that but i copied it directly from here so im not sure what else to do.
![Config](https://user-images.githubusercontent.com/321989/95886784-a7422800-0d44-11eb-817c-cb92f57f1b8d.PNG)

**Comment by firstof9** [comment]
Please do not screen shot text.

You missed the first line of that template:

"Use the following to create a sensor with summary text describing the state of your deliveries that can be used in your Lovelace cards or in notifications. Add to the `sensor:` portion of the `configuartion.yaml`."

So before `platform: template` you need `sensor:`
