### ISSUE TITLE
HACS

### ISSUE THREAD

**Issue by FuzzyMistborn** [moralmunky/Home-Assistant-Mail-And-Packages#24]
Would be great if this was added to HACS to allow easy updates/installs.

**Comment by moralmunky** [comment]
As we are both donating time to this, an impressive amount from @firstof9 than myself recently, feel free to contribute the necessary code.

**Comment by FuzzyMistborn** [comment]
Sure thing, appreciate all you've done!

**Comment by FuzzyMistborn** [comment]
Hmm, looks like this might be tricky as I don't know if HACS can add anything to the www folder.  Will need to investigate.  For now I've added it as a custom repo so that should help.
