### ISSUE TITLE
ISSUE: nontype object not scriptable

### ISSUE THREAD

**Issue by avd706** [moralmunky/Home-Assistant-Mail-And-Packages#240]
mail and packages version 0.3.0
installed manually for troubleshooting
homeassistant 0.117.0b3

####################################################
Logger: homeassistant.components.sensor
Source: custom_components/mail_and_packages/sensor.py:45
Integration: Sensor (documentation, issues)
First occurred: 3:07:46 PM (1 occurrences)
Last logged: 3:07:46 PM

Error while setting up mail_and_packages platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/mail_and_packages/sensor.py", line 29, in async_setup_entry
    sensors.append(PackagesSensor(entry, variable, coordinator, unique_id))
  File "/config/custom_components/mail_and_packages/sensor.py", line 45, in __init__
    self._state = self.coordinator.data[self.type]
TypeError: 'NoneType' object is not subscriptable

**Comment by firstof9** [comment]
Just FYI the 0.3.0 branch isn't ready for use, but it's close. I haven't PR'ed my fixes for this error yet.
Stay tuned.

**Comment by firstof9** [comment]
The latest commit to 0.3.0 should resolve this.

**Comment by avd706** [comment]
Yes, error message is gone in the log.
