### ISSUE TITLE
Yahoo mail fails authentication

### ISSUE THREAD

**Issue by coharness** [moralmunky/Home-Assistant-Mail-And-Packages#242]
**Describe the bug**
Every time I try to set up with my Yahoo mail account it fails authentication. I have double checked that the address/password is correct multiple times by logging back in and I am positive I'm using the correct credentials. I'm using the IMAP settings as specified on [Yahoo's help page](https://help.yahoo.com/kb/sln4075.html), which is *imap.mail.yahoo.com* and port *993*.

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: Synology
 - Home Assistant version: 0.117.2 (and others before, I'm just currently on the most recent)
 - Hassio/Docker 
 - Component version: 0.2.1-1

**Logs**
Logger: custom_components.mail_and_packages.config_flow
Source: custom_components/mail_and_packages/config_flow.py:197
Integration: Mail and Packages (documentation, issues)
First occurred: 3:47:30 PM (1 occurrences)
Last logged: 3:47:30 PM

Error logging into IMAP Server: b'[AUTHENTICATIONFAILED] LOGIN Invalid credentials'

**Comment by firstof9** [comment]
Please [see the wiki for how to setup for Yahoo Mail](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Configuration-and-Email-Settings#yahoo-mail).

**Comment by coharness** [comment]
Yes, like I said that's what I'm doing. I've even copy/pasted from where I have them saved, I **know** my username and password are correct.

**Comment by firstof9** [comment]
You also need to generate an App password as outlined [here on their help pages](https://help.yahoo.com/kb/generate-manage-third-party-passwords-sln15241.html).

**Comment by firstof9** [comment]
In the meantime, I've updated the wiki with this information.

**Comment by coharness** [comment]
Aha, that was the issue. I've got it all up and running now, thanks.

**Comment by firstof9** [comment]
Thank you for helping pointing out where more documentation was needed. 👍
