### ISSUE TITLE
ISSUE: New USPS Informed Delivery email address

### ISSUE THREAD

**Issue by FuzzyMistborn** [moralmunky/Home-Assistant-Mail-And-Packages#244]
**Describe the bug**

Just noticed this morning that my email wasn't automatically filtered by Gmail.  Noticed that the email address is now `USPSInformeddelivery@informeddelivery.usps.com` instead of `USPSInformedDelivery@usps.gov`

**Environment (please complete the following information):**
 - OS: [e.g. HassOS/Raspbian/CentOS]
 - Type of device: [e.g. RPi3/NUC/Synology]
 - Home Assistant version: [e.g. 0.105.5]
 - Hassio/Docker/Core? 
 - Component version: [e.g. 0.1.2]

**Logs**
Paste your error logs here.

**Screenshots**
![image](https://user-images.githubusercontent.com/16689090/99148384-58462600-2655-11eb-9c17-c3ff457f11d5.png)

**Additional context**
Please add emails in plain/text format if possible and applicable.

Should be as simple as updating the cont.py

**Comment by firstof9** [comment]
Mine are still coming from .gov

![image](https://user-images.githubusercontent.com/1105672/99150453-ea4c2f80-2651-11eb-83b3-e5d84719ed25.png)

**Comment by FuzzyMistborn** [comment]
Was that today?

**Comment by ttaidapos** [comment]
This was today, I also received it from USPSInformeddelivery@informeddelivery.usps.com.  Wondering if this is a perm change or USPS hickup.

**Comment by firstof9** [comment]
My email was from yesterday, I haven't received a Informed Delivery yet today.

**Comment by FuzzyMistborn** [comment]
> My email was from yesterday, I haven't received a Informed Delivery yet today.

That's likely why. Mine was the old address yesterday and the new one today

**Comment by firstof9** [comment]
Note the new 0.3.x code base allows multiple email addresses 😝 
Just waiting on confirmation, my informed delivery email for today, so I can merge all 3 PRs.
