### ISSUE TITLE
ISSUE:  USPS Not updating, I believe due to search function

### ISSUE THREAD

**Issue by tek0011** [moralmunky/Home-Assistant-Mail-And-Packages#254]
**Describe the bug**
USPS does not update.  I believe it is due to the search terms being different.  This is Saturday email:
_Your Daily Digest for Sat, Nov 21_  instead of Fridays mail:  _Informed Delivery Daily Digest_

**Environment (please complete the following information):**
 - OS: HassOS 4.17
 - Type of device: UnRaid

Im not sure the above data is necessary, doesnt seem to be an environment issue.  Just looks like some search/grep/regex may have changed.

**Comment by tek0011** [comment]
`Subject: Your Daily Digest for Sat, Nov 21`

**Comment by firstof9** [comment]
Good catch, stupid USPS changing things. I'll get a update out shortly.

**Comment by tek0011** [comment]
Interestingly, I tried to manually change it to the subject title (same as your commit, but also I did exact title), and it seemed to not find anything new either.

**Comment by firstof9** [comment]
The changes worked for me running 0.2.2-b36 and passed tests on the 0.3.0 alpha branch.

**Comment by github-479** [comment]
Have not tried the 0.3.0 branch but changing the USPS_Mail_Subject var in const.py to match yesterday's subject worked as expected and imported the mail images.
