### ISSUE TITLE
ISSUE: Amazon not includd in `In Transit` or `Deliveries` sensors

### ISSUE THREAD

**Issue by bretterer** [moralmunky/Home-Assistant-Mail-And-Packages#259]
**Describe the bug**
`In Transit` and `Deliveries` does not include Amazon

**Environment (please complete the following information):**
 - OS:HassOS
 - Type of device: Proxmox
 - Home Assistant version: 0.118.2
 - Hassio/Docker/Core? Docker
 - Component version: 2.1.2-3

**Logs**
Paste your error logs here.

**Screenshots**
<img width="459" alt="Screen Shot 2020-11-22 at 11 35 48 PM" src="https://user-images.githubusercontent.com/1906920/99929504-7974d980-2d1b-11eb-9b1b-284195d3e991.png">

**Additional context**
You can see in the code at https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/blob/fd71762201a3e8e4465165ae96d5d90871284fcf/custom_components/mail_and_packages/sensor.py#L233-L237 that the count does not include Amazon.  This should be updated, and I am willing to submit a PR for this if you are open to it

**Comment by firstof9** [comment]
This is not a bug, it is by design.

[Please see the wiki.](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki#amazon)

**Comment by bretterer** [comment]
@firstof9 oops.  Not sure how I managed to miss this one.   So sorry for the bug report.  Thanks for the integration, it's working well!
