### ISSUE TITLE
ISSUE: Amazon Delivered Sensor Missing

### ISSUE THREAD

**Issue by ronaldheft** [moralmunky/Home-Assistant-Mail-And-Packages#260]
**Describe the bug**
The Amazon delivered sensor is no longer showing for me in the latest version.

**Environment (please complete the following information):**
 - OS: [e.g. HassOS/Raspbian/CentOS] Docker
 - Type of device: [e.g. RPi3/NUC/Synology] Synology
 - Home Assistant version: [e.g. 0.105.5] 0.118.2
 - Hassio/Docker/Core? Docker
 - Component version: [e.g. 0.1.2] 0.2.1-3

**Logs**
Paste your error logs here.

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment]
Sounds like you downgraded from the 0.2.2 beta version to 0.2.1 stable.

**Comment by ronaldheft** [comment]
Yes, that was the issue. Followed the HACS upgrade prompts and didn't realize it was doing a downgrade.
