### ISSUE TITLE
[Feature Request] Add support for Hermes (UK)

### ISSUE THREAD

**Issue by tomanderson2** [moralmunky/Home-Assistant-Mail-And-Packages#264]
I didn't want to hijack #262 but this relates to a UK courier, [hermes](https://www.myhermes.co.uk/). I will try adding additional tickets for other UK carriers as an when I can.

Email: Hermes <donotreply@myhermes.co.uk>

Out for delivery eml: https://gist.github.com/tomanderson2/11785519e57c2016aa714cd8f4e98142
Delivered eml: https://gist.github.com/tomanderson2/17e7811781a230e2ef4e84d613d08279

If the gists don't work I can send the file to your email.

I anonymised some of the data to the following;
my email address - > my_email_address@gmail.com
tracking number - > 8888888888888888 (the original is all digits and the same length ie 16 digits)
My address - > 123 My Address

If you need anything else let me know. When you have what you need from the gists let me know and I'll remove them.

Thanks

**Comment by firstof9** [comment]
I have pulled down the gists, thank you. I'll see what I can do.

**Comment by firstof9** [comment]
The mock tests come back as good in the 0.3.0 branch so it looks promising.

**Comment by moralmunky** [comment]
@tomanderson2 are you able to provide information similar to what is found in [supported shippers and requirements](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Configuration-and-Email-Settings#supported-shippers-and-requirements) that provides a link to the service to sign up and details any required settings to begin receiving the correct email messages?

**Comment by tomanderson2** [comment]
@moralmunky as with Royal Mail, I don't believe you can't sign up for this and its just when the retailer decides to pass on your email address....
