### ISSUE TITLE
[Feature Request] Add support for Royal Mail (UK)

### ISSUE THREAD

**Issue by tomanderson2** [moralmunky/Home-Assistant-Mail-And-Packages#269]
Another UK courier request; [Royal Mail](https://www.royalmail.com/)

Email: Royal Mail <no-reply@royalmail.com>

Out for delivery eml: https://gist.github.com/tomanderson2/672bf25120445e90a32f256bc197b389
Delivered eml: https://gist.github.com/tomanderson2/c9448bed8443f67b4b239ea97ae91c7f

I anonymised some of the data to the following;
my email address - > my_email_address@gmail.com
tracking number - > MA038501234GB (Similar to the original, just change some digits)

For the tracking number, they can vary pretty wildly according to the royal mail site (7 - 27 characters!), but there is some info around for the majority.

Found this on stackoverflow: https://stackoverflow.com/a/3537055
And 17track gives some details of the regex they use: https://carrierlist.17track.net/en/postal

If you need anything else let me know. As before, when you have what you need from the gists let me know and I'll remove them.

Thanks

**Comment by firstof9** [comment]
> tracking number - > MA038501234GB (Similar to the original, just change some digits)

Does it _always_ start MA and end GB?

**Comment by firstof9** [comment]
Note: Regex: '[A-Za-z]{2}[0-9]{9}+GB'

**Comment by firstof9** [comment]
I've grabbed the gists.

**Comment by firstof9** [comment]
Tests passed, should be working in the 0.3.0 branch.

**Comment by moralmunky** [comment]
@tomanderson2 are you able to provide information similar to what is found in [supported shippers and requirements](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Configuration-and-Email-Settings#supported-shippers-and-requirements) that provides a link to the service to sign up and details any required settings to begin receiving the correct email messages?

**Comment by tomanderson2** [comment]
@moralmunky RoyalMail is not something you can sign up for to get notifications afaict. It depends on the retailer and I guess they pass your email to royal mail to provide the updates. I do have an account with them, but that doesn't seem to affect things.
