### ISSUE TITLE
Not picking up USPS informed delivery emails

### ISSUE THREAD

**Issue by dima-ser** [moralmunky/Home-Assistant-Mail-And-Packages#279]
I have USPS informed delivery emails coming into my email and everything configured in HA correctly, however, the integration is not reporting any mail or showing any mail pictures. I noticed your readme file says it's looking for emails from USPSInformedDelivery@usps.gov, but these now come from USPSInformeddelivery@informeddelivery.usps.com. Could it be the reason why it's not picking them up? If so, is there a way to configure to change the email it's looking for? Also, the subject on these emails is "Your Daily Digest for [date]" as opposed to "Informed Delivery Daily Digest" like the readme suggests.

**Comment by moralmunky** [comment]
What version are you using? Release 0.2.2 was provided 2 days ago that officially addresses the address change.

**Comment by dima-ser** [comment]
Thanks, I was using an older release. I upgraded it, but it now made duplicates for all the entities. Is there a process I can follow for proper clean upgrade?

**Comment by moralmunky** [comment]
Depending on what version you came from there have been occasionally a breaking change that @firstof9 has implemented to improve the sensors that results in this duplication. Just remove the integration, restart, and add it again. Anything references these sensors will continue to work after it is reinstalled.

**Comment by firstof9** [comment]
To clean up the duplicate entities click here:
![image](https://user-images.githubusercontent.com/1105672/101228738-39d2b980-365a-11eb-91c1-9a8697d3f89a.png)


Then on the right hand side you'll see a red icon (circled in the image is where the icon will appear):
![image](https://user-images.githubusercontent.com/1105672/101228795-68e92b00-365a-11eb-81ed-78d2b86573e1.png)

Select these entities and then click "Remove Selected": 
![image](https://user-images.githubusercontent.com/1105672/101228815-8cac7100-365a-11eb-8085-4c4e326865d4.png)

The duplicates will be gone and you can then rename the entities in your list by clicking them and removing the "_2":
![image](https://user-images.githubusercontent.com/1105672/101228857-b5346b00-365a-11eb-9a57-e81b1dd53c6a.png)

**Comment by dima-ser** [comment]
> 
> 
> To clean up the duplicate entities click here:
> ![image](https://user-images.githubusercontent.com/1105672/101228738-39d2b980-365a-11eb-91c1-9a8697d3f89a.png)
> 
> Then on the right hand side you'll see a red icon (circled in the image is where the icon will appear):
> ![image](https://user-images.githubusercontent.com/1105672/101228795-68e92b00-365a-11eb-81ed-78d2b86573e1.png)
> 
> Select these entities and then click "Remove Selected":
> ![image](https://user-images.githubusercontent.com/1105672/101228815-8cac7100-365a-11eb-8085-4c4e326865d4.png)
> 
> The duplicates will be gone and you can then rename the entities in your list by clicking them and removing the "_2":
> ![image](https://user-images.githubusercontent.com/1105672/101228857-b5346b00-365a-11eb-9a57-e81b1dd53c6a.png)

Thank you!
