### ISSUE TITLE
ISSUE: Sensors are renamed after an integration update

### ISSUE THREAD

**Issue by jayscovill** [moralmunky/Home-Assistant-Mail-And-Packages#291]
**Describe the bug**
The sensors for the integration are being duplicated and resulting in a "_2" appended to them.  As a result it's necessary to go through and delete the old sensors and rename the new ones removing "_2".

This seems to be happening after an integration update but I haven't pinned that down for sure.

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: VM
 - Home Assistant version: .116
 - Hassio/Docker/Core? HassIO
 - Component version: 0.3.0-b6

**Comment by firstof9** [comment]
This was part of the breaking changes in 0.2.2.
https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/releases/tag/0.2.2

**Comment by jayscovill** [comment]
Ok, thanks for the confirm...Happened two or three times over the last upgrades so just wanted to confirm it was expected behaviour.
