### ISSUE TITLE
[Help] More details on mail_today.gif

### ISSUE THREAD

**Issue by bretterer** [moralmunky/Home-Assistant-Mail-And-Packages#307]
**Is your feature request related to a problem? Please describe.**
Its unclear on how to get the mail_today.gif set up and working correctly.  I have been working at getting it working for weeks now with no luck. The documentation makes reference to setting the path to the file during setup, which I did, but I can not access or find `mail_today.gif` anywhere on my server.

**Describe the solution you'd like**
It would be nice if this was just automated for you 

**Describe alternatives you've considered**
N/A

**Additional context**
Can provide screenshots of my setup if you would find them helpful

**Comment by firstof9** [comment]
> It would be nice if this was just automated for you

Not everyone has the same setup, so that's why you pick the path.

Normally you want this in the `www` directory somewhere. Example: `www/images/`

What install of Home Assistant do you have?
What is the current image output path you've selected?

**Comment by bretterer** [comment]
I used the Proxmox LXC Build from @whiskerz007 (https://github.com/whiskerz007/proxmox_hassio_lxc)

I am currently using `/config/custom_components/mail_and_packages` as stated in the wiki, but feel that is incorrect. 

However, when I do a `find / mail_today.gif` on the server itself, nothing is found at all (using mail_today.gif as the search based on https://github.com/moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card which is the card im trying to use)

**Comment by firstof9** [comment]
> I am currently using `/config/custom_components/mail_and_packages` as stated in the wiki, but feel that is incorrect.

Try using `/config/www/<what ever directory you like>` as the image output path. I plan to have the directory be auto detected in the 0.3.0 version at some point to make things easier.

**Comment by bretterer** [comment]
That resolved it, thank you! 

Now I just need to get the custom card to pick it up somehow.

Looking forward to the auto-detection

**Comment by moralmunky** [comment]
The wiki has been updated to reflect correct paths when using the local file camera or the custom card. If the image resides in the `/config/www/` the custom card's Mail GIF location should be set to `/local/mail_today.gif `. If you added a folder in www to put the image in, include that folder in your path. 
https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Configuration-and-Email-Settings
