### ISSUE TITLE
ISSUE: IMAP SENTON does not respect time zone, resulting in some mail being missed from search

### ISSUE THREAD

**Issue by mbaran5** [moralmunky/Home-Assistant-Mail-And-Packages#315]
**Describe the bug**
Microsoft Office365 (and possibly others) are using UTC for date/time regardless of the client timezone. This means that if mail is delivered late, such as during the holidays, packages will not be marked as delivered since the message will be received in the next day UTC. In PST, any email received after 4PM PST will not be counted as IMAP SEARCH "ON" or "SENTON" both count the mail as being received the next day. 

From the RFC from IMAP4v1, both commands ignore the time and time zone from the header. 

> ON <date>
         Messages whose internal date (disregarding time and timezone)
         is within the specified date.
> SENTON <date>
         Messages whose [RFC-2822] Date: header (disregarding time and
         timezone) is within the specified date.

It _seems_ to me that using "ON" should still return the INTERNAL DATE of the correct day, but it seems like when it wipes out the TZ it returns to UTC. 

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: VM
 - Home Assistant version: 2020.12.1
 - Hassio/Docker/Core? Hassio
 - Component version: 0.3.0b18

**Logs**

In the example below I am searching for a message from USPS like the code does, with the message header info below. You can see that the "SENTON" date would match 27-Dec-2020, even though that email was received at 8:17PM PST. 

```
a1 fetch 55619 all
* 55619 FETCH (FLAGS (\Seen) INTERNALDATE "26-Dec-2020 20:17:19 -0800" RFC822.SIZE 133504 ENVELOPE ("Sun, 27 Dec 2020 04:17:15 +0000" "=?UTF-8?Q?USPS=C2=AE_Item_Delivered,_In/At_Mailbox_9405803699300786656224?=" ((NIL NIL "auto-reply" "usps.com")) ((NIL NIL "auto-reply" "usps.com")) NIL ((NIL NIL "xxxx" "xxxxxxxxx.com")) NIL NIL NIL "<920190945.6521203.1609042635024.JavaMail.ppts2_b@eagnmnmep1fb8.usps.gov>"))
a1 OK FETCH completed.
```
```
a1 search FROM "auto-reply@usps.com" SUBJECT "Item Delivered" SENTON "26-Dec-2020"
* SEARCH
```
```
a1 search FROM "auto-reply@usps.com" SUBJECT "Item Delivered" SENTON "27-Dec-2020"
* SEARCH 55619
```

This results in the script not detecting the message until the next day, as seen below. 

```
2020-12-26 23:55:37 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Attempting to find mail from (['auto-reply@usps.com']) with subject (Item Delivered)
2020-12-26 23:55:37 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (FROM "auto-reply@usps.com" SUBJECT "Item Delivered" SENTON "26-Dec-2020")
2020-12-26 23:55:37 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Search for (['auto-reply@usps.com']) with subject 1 (Item Delivered) results: b'' count: 0
```
```
2020-12-27 00:00:47 DEBUG (SyncWorker_9) [custom_components.mail_and_packages.helpers] Attempting to find mail from (['auto-reply@usps.com']) with subject (Item Delivered)
2020-12-27 00:00:47 DEBUG (SyncWorker_9) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (FROM "auto-reply@usps.com" SUBJECT "Item Delivered" SENTON "27-Dec-2020")
2020-12-27 00:00:49 DEBUG (SyncWorker_9) [custom_components.mail_and_packages.helpers] Search for (['auto-reply@usps.com']) with subject 1 (Item Delivered) results: b'60770 60771' count: 2
2020-12-27 00:00:49 DEBUG (SyncWorker_9) [custom_components.mail_and_packages.helpers] Searching for tracking numbers...
2020-12-27 00:00:49 DEBUG (SyncWorker_9) [custom_components.mail_and_packages.helpers] Found tracking number in email subject: (XXXXXXXXXXXXXXXXX6224)
2020-12-27 00:00:49 DEBUG (SyncWorker_9) [custom_components.mail_and_packages.helpers] Found tracking number in email subject: (XXXXXXXXXXXXXXXXX6108)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/583865/103182493-83c94c80-4860-11eb-9292-ac4828c66d68.png)

**Additional context**

**I am wondering if it makes sense and still follows the same concept to use SENTSINCE instead of SENTON.** This would effectively do the same thing, it would be all mail sent since the start of a new day, i.e. if it was SENTSINCE 27-Dec-2020, it would catch all mail from 27-Dec-2020 until now, which is either the 28th by UTC time, or until the script moves to a new day. I wanted to see if that was agreeable as a way to deal with this. I tried to see if Office365 supported some of the newer IMAP extensions, such as "YOUNGER" but it does not. This is the only possible solution I could think of, unless the script had a way to configure the host IMAP UTC and flip the current date around based on that. Thoughts?

**Comment by firstof9** [comment]
Actually I'm thinking `SINCE` would be better since it utilizes the `INTERNALDATE`.

```txt
SINCE <date>: Messages whose internal date (disregarding time and timezone) is within or later than the specified date.
```

**Comment by mbaran5** [comment]
> Actually I'm thinking `SINCE` would be better since it utilizes the `INTERNALDATE`.
> 
> ```
> SINCE <date>: Messages whose internal date (disregarding time and timezone) is within or later than the specified date.
> ```

Awesome!  I wasn’t sure why SENTON was used instead of ON which I why I leaned towards SENTSINCE. I agree SINCE makes the most sense. 

I was really trying to figure out a way to accurately scope the search to the day with the correct time zone, but IMAP seems too inflexible to allow for it. The extensions would have worked, using YOUNGER but alas no support from Microsoft.

**Comment by firstof9** [comment]
Right but based on the response you got:
`INTERNALDATE "26-Dec-2020 20:17:19 -0800"`

SINCE should work as expected.

**Comment by mbaran5** [comment]
So here's where it's weird. Let's use "notifications@github.com" as an example. 

![image](https://user-images.githubusercontent.com/583865/103187224-715b0d00-4878-11eb-9c56-836195a3b339.png)

Using ON which uses the INTERNALDATE 

> ON
Messages whose internal date (disregarding time and timezone)
is within the specified date.

```
a1 search FROM "notifications@github.com" ON "27-Dec-2020"
* SEARCH
* 5340 FETCH (FLAGS (\Seen))
* 5341 FETCH (FLAGS (\Seen))
* 5343 FETCH (FLAGS (\Seen))
a1 OK SEARCH completed.
```
```
a1 search FROM "notifications@github.com" ON "28-Dec-2020"
* SEARCH 49256 49257
a1 OK SEARCH completed.
```

Header, notice the INTERNALDATE still shows 27, but the search won't find it.

```a1 fetch 49257 all
* 49257 FETCH (FLAGS () INTERNALDATE "27-Dec-2020 19:18:41 -0800" RFC822.SIZE 66153 ENVELOPE ("Mon, 28 Dec 2020 03:18:38 +0000" "Re: [moralmunky/Home-Assistant-Mail-And-Packages] ISSUE: IMAP SENTON does not respect time zone, resulting in some mail being missed from search (#315)" 
```

So with this, I would expect SINCE and SINCESENT to effectively return the same results, stripping all time data and returning the same UTC date.

**Comment by firstof9** [comment]
Lets see if b19 works as expected then.

**Comment by mbaran5** [comment]
I'm not seeing the fix as implemented, it looks like you had originally removed lines 250-253 in helpers.py but they still appear to be there in the merged branch. Here's my log still showing SENTON being used. 

```
2020-12-28 19:00:57 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (FROM "auto-reply@usps.com" SUBJECT "Item Delivered" SENTON "28-Dec-2020")
```

https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/blob/5bd87de352c6d9602afc50003c378be3c31fd8f3/custom_components/mail_and_packages/helpers.py#L230 shows Since=None

and 

https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/blob/5bd87de352c6d9602afc50003c378be3c31fd8f3/custom_components/mail_and_packages/helpers.py#L250-L253 would make it run as SENTON.

**Comment by firstof9** [comment]
Ya looks like my merge got messed up, fixing it now.

**Comment by firstof9** [comment]
b20 should now use `SINCE`

**Comment by mbaran5** [comment]
Looks good here. I'll report back after my next package arrives.

**Comment by mbaran5** [comment]
This is fixed, thank you!
