### ISSUE TITLE
[Feature Request] Extend timeout or allow as a configurable value

### ISSUE THREAD

**Issue by redjab** [moralmunky/Home-Assistant-Mail-And-Packages#328]
**Is your feature request related to a problem? Please describe.**
Last couple of days, yahoo mail has been timing out quite frequently for me. This led to multiple error messages in the logs, as well as duplicate notifications (due to a flow I have). 

**Describe the solution you'd like**
The current timeout is 30 seconds. If I edit the .py file manually and up that to 60 seconds, the problem seems to not occur. I understand that 60 seconds might be too long for some, that's why my alternate suggestion is to have that value be user-configurable and default it to the current value (30s)

**Comment by firstof9** [comment]
Shouldn't be too hard. I'll see what I can whip up.

**Comment by firstof9** [comment]
![image](https://user-images.githubusercontent.com/1105672/104328757-61167500-54a9-11eb-98b2-348ac6505985.png)
As of b31 👍

**Comment by redjab** [comment]
Works great, thanks!
