### ISSUE TITLE
GIF rotation is very slow

### ISSUE THREAD

**Issue by moralmunky** [moralmunky/Home-Assistant-Mail-And-Packages#33]
I find that 10 seconds is very slow rotation speed, especially if you have few mail pieces come through. It could be nice to add and option to adjust this speed when setting up the integration.

**Comment by firstof9** [comment]
I haven't received any mail in the past few days to verify my commits.

**Comment by firstof9** [comment]
Will add the gif speed as a setting after lowering the speed for now ;)

**Comment by moralmunky** [comment]
I don't see anything else on the file camera page. The GIF is constructed correctly with 4 images but when viewed in the camera entity it's not cycling through all the images. It is only displaying the first and second image. If I set the timing to 3 second I see all the images but the last doesn't display as long as the first three. Seems to be something to do with 10 seconds and the file camera entity.

Did you previously choose 10 second because of some constraint with the file camera entity?

**Comment by firstof9** [comment]
> Did you previously choose 10 second because of some constraint with the file camera entity?

Nope just randomly picking numbers that seemed lengthy enough.
