### ISSUE TITLE
setup with yahoo not working.

### ISSUE THREAD

**Issue by ggoodell2** [moralmunky/Home-Assistant-Mail-And-Packages#332]
i cant get yahoo mail to setup with this. no option to select security. pop.mail.yahoo.com port 995 ssl required

**Comment by firstof9** [comment]
Please [see the wiki](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Configuration-and-Email-Settings#yahoo-mail) for how to setup your yahoo mail to use this integration.
