### ISSUE TITLE
ISSUE: Delivery and In Transit sensors not updated

### ISSUE THREAD

**Issue by Madj42** [moralmunky/Home-Assistant-Mail-And-Packages#345]
**Describe the bug**
The delivery summary message and individual summary messages are updated correctly but the Deliveries and In Transit sensors are not.

**Environment (please complete the following information):**
 - OS: HASSOS
 - Type of device: Raspberry PI 4
 - Home Assistant version: 2021.1.4
 - Hassio/Docker/Core?  Hassio
 - Component version:  0.3-b35

**Logs**
No error logs after enabling debug logging.

**Screenshots**
This is of the official card.  The sensors also show a value of 0
![unnamed](https://user-images.githubusercontent.com/20431177/105101452-45e0d200-5a74-11eb-84d2-d7030d5f2d45.png)

**Comment by firstof9** [comment]
Going to need debug output to see what's happening.

**Comment by firstof9** [comment]
Note: package sensors dict isn't sorted correctly.

**Comment by riddledaxis** [comment]
I am running v0.3.0-b36 and I am having the issue with the In Transit sensor not updating. 

I had a package from the Royal Mail today but the sensors did not update after I received this email
![Screenshot 2021-01-22 202609](https://user-images.githubusercontent.com/47009467/105541894-674df200-5cf0-11eb-9d95-84844c2b5fe8.png)
![Screenshot 2021-01-22 202648](https://user-images.githubusercontent.com/47009467/105541942-7896fe80-5cf0-11eb-8e4b-6e1e092304d0.png)

But after it was delivered and I received this email, the deliveries and Royal Mail sensor changed to 1 and are currently still showing.
![Screenshot 2021-01-22 202638](https://user-images.githubusercontent.com/47009467/105542492-5487ed00-5cf1-11eb-8130-1aff86d6a21b.png)
![Screenshot 2021-01-22 202701](https://user-images.githubusercontent.com/47009467/105542044-a0866200-5cf0-11eb-89a2-72cc4b4a7833.png)

The In Transit sensor is not updating even though the text clearly states that "1 Royal Mail package is in transit" and deliveries is set to 1

I am running HA Supervisor: supervisor-2021.01.5, HA version: core-2021.1.4  HassOS: 5.10 and Mail and Packages: v0.3.0-b36

**Comment by firstof9** [comment]
Separate issue, but I see the error

**Comment by firstof9** [comment]
b37 should fix this for you @riddledaxis
