### ISSUE TITLE
ISSUE: Documentation does not describe how to use the new sensor.mail_image_url in place of the camera for 

### ISSUE THREAD

**Issue by quanturium** [moralmunky/Home-Assistant-Mail-And-Packages#347]
**Describe the bug**
The dedicated card for mail and packages https://github.com/moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card does not seem up to date with latest beta. Documentation is showing info for the latest release which is great but it's not easy for beta testers to actually help beta test without any info. I took a look at the code but was not able to figure out how to configure the new `sensor.mail_image_url` in place of the custom camera.

**Comment by firstof9** [comment]
That'd be an issue for moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card repo.

**Comment by moralmunky** [comment]
THe current version of the card is in step with the latest non-eta release of the integration. The card is not ready for release. Please continue using either the path to the gif.
