### ISSUE TITLE
Notification trigger

### ISSUE THREAD

**Issue by moralmunky** [moralmunky/Home-Assistant-Mail-And-Packages#35]
I previously had an entity sensor.mail_deliveries_today that counted all mail vendors in transit and already delivered packages to trigger the notification. The current notification example only triggers based on USPS mail and packages.

What are your thoughts on bringing that back? Or maybe creating a notification sensor to count all the mail and package sensors numbers so there is only one sensor a user need to add to the automation?

**Comment by firstof9** [comment]
The "in transit" packages is from USPS, UPS, and FedEx all combined.
Technically it triggers on mail and if any packages are enroute.

**Comment by moralmunky** [comment]
I can get behind having less sensors to manage and explain in documentation.  I like getting the notification when a package is delivered so it’s easy enough to just add the mail_packages_delivered in addition to the mail_usps_mail and mail_packages_in_transit to the automation trigger to also send an update summary when packages are delivered.
