### ISSUE TITLE
In transit shows the same amount after deliveries recorded

### ISSUE THREAD

**Issue by moralmunky** [moralmunky/Home-Assistant-Mail-And-Packages#36]
Today I received 2 in delivering today messages and 2 delivered messages from USPS. I would expect the delivering count to reduce as the delivered count increased and the total USPS package count to only be 2 packages.

<img width="511" alt="mailcard" src="https://user-images.githubusercontent.com/19318945/74593507-d196e680-4ff9-11ea-9e25-730f89a40efc.png">

**Comment by firstof9** [comment]
I have an idea to fix this.

**Comment by moralmunky** [comment]
Looking at the code I figured it would make most sense, and easier, to put in the efficiency patch branch in your repository. I’m not github savvy enough Right now to figure out how to add to your branch before it’s committed to the main branch under my account. Happy to listen if you care to explain.

**Comment by firstof9** [comment]
I'm think make a dev branch here that we can do PRs on then once the dev branch is read we merge it to master.
