### ISSUE TITLE
[Feature Request] Attribute for last sensor refresh date-time?

### ISSUE THREAD

**Issue by KairuByte** [moralmunky/Home-Assistant-Mail-And-Packages#361]
I've been trying to set up an automation to kick off whenever USPS Informed Delivery is updated. However, it doesn't seem there is any guaranteed way to ensure the sensor has updated? For instance, if Monday there was one incoming mail item, and Tuesday there were 2, things work. But if both days had a single package, there is no direct way to tell that the state has been "refreshed" with the state simply remaining the same.

It would be great if the date-time could be stored in an attribute, containing the most recent date-time an email was processed.

The closest I have come, is either forcing the state to be reset to 0 at midnight (hacky and non standard), or trying to trigger on last_updated or last_changed which are unreliable and unstable. Neither is an ideal solution.

**Comment by moralmunky** [comment]
Just one note, sensor.mail_usps_mail resets to zero after midnight when the first run happens according to what you have set your scanning interval 2.

**Comment by moralmunky** [comment]
What are you trying to accomplish with the informed delivery emails if they don't contain mail and only packages?

**Comment by KairuByte** [comment]
Actually, it seems there was an issue with the automation. Deleted it and re-created and it worked fine. I should have checked the yaml for issues. Sorry for the confusion!
