### ISSUE TITLE
Gif image not generating in a timely manner

### ISSUE THREAD

**Issue by tkdrob** [moralmunky/Home-Assistant-Mail-And-Packages#363]
**Describe the bug**
Introduced in 0.3.0-b38, gif image only generates ones a day. For me, it generates in the evening. This either needs to be time zone sensitive or made to only generate the gif once after the reception of a new mail delivery digest email.

**Environment (please complete the following information):**
 - OS: Debian Buster
 - Type of device: NUC
 - Home Assistant version: 2021.2.1
 - Docker
 - Component version: 0.3.0-b41

**Comment by tkdrob** [comment]
Today, the gif generated correctly in the morning. A restart of home assistant then left it at no mail.

**Comment by firstof9** [comment]
The image generates each go, the filename is the only part that used to change the content was always the same. I have found that the camera automation doesn't fire on restart to 'update' the image, this is likely what you run  into right now.

Try restart HA, then manually fire the camera update automation, i bet you the image updates properly then.

**Comment by tkdrob** [comment]
I was not using a camera entity until this moment. I'll be back later with my experience.

**Comment by moralmunky** [comment]
Camera path getting updated after restart is address in this forum post.

https://community.home-assistant.io/t/mail-and-packages-custom-component-for-ups-fedex-and-usps/118081/1286?u=moralmunky

**Comment by moralmunky** [comment]
@tkdrob What were you using before to display the image?

**Comment by tkdrob** [comment]
Turns out I was not using a yaml config camera. I am now and things are working. Thanks
