### ISSUE TITLE
Missing Image Link

### ISSUE THREAD

**Issue by aron7676** [moralmunky/Home-Assistant-Mail-And-Packages#364]
The generated image link is missing.

**Environment (please complete the following information):**
 - OS: Home Assistant Core, Docker
 - Type of device: Unraid
 - Home Assistant version: core-2021.2.2
 - Home Assistant Container
 - Component version: 0.3.0

**Logs**
None showing

**Screenshots**
![image](https://user-images.githubusercontent.com/34799229/107449838-824a9f80-6b01-11eb-9612-cdf0658d9adf.png)
![image](https://user-images.githubusercontent.com/34799229/107450088-e1101900-6b01-11eb-9239-fd08fc33ef48.png)

**Additional context**
Fresh install. 

Image is accessible from:
http://192.168.0.xxx:8123/local/mail_and_packages/1c3445fa-09b3-49db-a29e-2d226781761d.gif

Could be user error here, but I think I installed it correctly.

**Comment by moralmunky** [comment]
Do you have internal_url or external_url in your configuration?

**Comment by aron7676** [comment]
Might be user error, but I don't think so. I can't find that setting in the
UI, and it's not in the base config yaml.

**Comment by aron7676** [comment]
To be clear, I installed a brand new image and went through the setup. I am new to HASS, so very possibly my fault, but I was not asked to set that up. 

That being said, adding the following lines to configuration.yaml fixed the error. 

homeassistant:
    internal_url: "http://192.168.0.140:8123"
    
I do not have it externally accessible, so this fixed my issue.
