### ISSUE TITLE
[Feature Request] Track package exceptions

### ISSUE THREAD

**Issue by FuzzyMistborn** [moralmunky/Home-Assistant-Mail-And-Packages#369]
**Is your feature request related to a problem? Please describe.**
Due to the weather today, a package that was out for delivery by USPS was not delivered.  I got a "Delivery Exception" email (I'll put the content below).  Seems like it'd be possible to track this

**Describe the solution you'd like**
Create a sensor for package exceptions so I can send a notification that a package is going to be delayed.

**Describe alternatives you've considered**
None

**Additional context**
Honestly I don't know 1) if this is a common enough thing to warrant handling and 2) no idea if FedEx/UPS do something similar.

Here's the email:

![image](https://user-images.githubusercontent.com/16689090/108456367-26d58b80-723e-11eb-8e6c-8e213d34b686.png)

**Comment by firstof9** [comment]
Could be something we track in 0.3.1

**Comment by firstof9** [comment]
Would you be able to send the email, after sanitized for personal info, for testing?

**Comment by firstof9** [comment]
Screenshots of the new sensors:
![image](https://user-images.githubusercontent.com/1105672/109428123-d33c0e00-79b2-11eb-9271-879cb300bf83.png)
![image](https://user-images.githubusercontent.com/1105672/109428135-e058fd00-79b2-11eb-995b-00e28e0786ee.png)

**Comment by FuzzyMistborn** [comment]
> Would you be able to send the email, after sanitized for personal info, for testing?

Sure.  Where to send?

**Comment by firstof9** [comment]
firstof9@gmail.com

**Comment by FuzzyMistborn** [comment]
Sent.  Let me know if that doesn't work for you, it's a forward of a forward.

**Comment by firstof9** [comment]
I was able to find one from 2019 in my email.
Should have a beta for you to play with shortly.

**Comment by firstof9** [comment]
There you go 0.3.2-b0

**Comment by FuzzyMistborn** [comment]
Thanks. Not likely gonna have time to test anytime soon. Rebuilt my server and need most sleep
