### ISSUE TITLE
[Feature Request] Muambator integration 

### ISSUE THREAD

**Issue by hudsonbrendon** [moralmunky/Home-Assistant-Mail-And-Packages#370]
**Is your feature request related to a problem? Please describe.**
None

**Describe the solution you'd like**
I live in Brazil and use a platform called "muambator" to track my packages. It integrates with the post office platform which is the standard integration service in the country. muambator sends emails whenever there is an update in one of my packages, can I create an integration with this platform? Would it be accepted without problems?

**Describe alternatives you've considered**
None

**Additional context**
Here is an example image of the content of the email sent.

![image](https://user-images.githubusercontent.com/5201888/108474964-da567400-726e-11eb-884a-b30f9f5fa666.png)

**Comment by firstof9** [comment]
We could attempt to add this to the list of shippers.

We'd need email examples for the following states: "Out for Delivery" and "Delivered".
