### ISSUE TITLE
ISSUE: Duplicate Forward Slash in Mail Image URL Sensor

### ISSUE THREAD

**Issue by jcgoette** [moralmunky/Home-Assistant-Mail-And-Packages#374]
![image](https://user-images.githubusercontent.com/53531335/108737362-88c51800-7500-11eb-83c5-d363203b996a.png)

Possibly due to lstrip instead of rstrip?

https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/blob/f4a008a411db6d3b7a77c5891188ce3239ef7b8c/custom_components/mail_and_packages/sensor.py#L162
https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/blob/f4a008a411db6d3b7a77c5891188ce3239ef7b8c/custom_components/mail_and_packages/sensor.py#L164

**Comment by firstof9** [comment]
Seems like that'd cause an extra `/`, can you confirm if the URL actually works?
I want to say Home Assistant would not allow it to work, but modern browsers do have code to handle stuff like this.

None the less I'll get a fix out.

**Comment by jcgoette** [comment]
Can't test, get a "User input malformed" error when attempting to Allow external image use in the config flow. I can enter separate issue for that if you'd like.

**Comment by firstof9** [comment]
Please do, but also check the Home Assistant log for errors as well.
