### ISSUE TITLE
ISSUE: Config Flow Error - User input malformed

### ISSUE THREAD

**Issue by jcgoette** [moralmunky/Home-Assistant-Mail-And-Packages#375]
**Describe the bug**

`User input malformed` when using config flow setup.

`Logger` set to `warn` and higher populates nothing in error log. Set to `notset` and higher and still nothing.

Let me know how else I can help troubleshoot.

**Screenshots**

![image](https://user-images.githubusercontent.com/53531335/108751796-a9956980-7510-11eb-860a-2109a5876dcb.png)

**Environment**

version | core-2021.2.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.83-v8
arch | aarch64
timezone | America/New_York

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4810
Installed Version | 1.11.3
Stage | running
Available Repositories | 752
Installed Repositories | 13

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.12
-- | --
update_channel | stable
supervisor_version | supervisor-2021.02.11
docker_version | 19.03.13
disk_total | 219.4 GB
disk_used | 91.4 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Autossh (0.3.0), File editor (5.2.0), Mosquitto broker (5.1), Ring Devices (4.3.0), Terminal & SSH (9.0.1), Frigate NVR (1.11), Home Assistant Google Drive Backup (0.103.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 4
views | 1
mode | storage

</details>

**Comment by firstof9** [comment]
To clarify this is when you hit "Options" or when adding the integration?

**Comment by jcgoette** [comment]
When clicking Options and going back through the steps. I had existing setup prior to 0.3.0.

**Comment by firstof9** [comment]
I have a PR in to resolve this, in the meantime, you can set the timeout to 30 (default) and set the amazon fwd list to `""` and that should allow the configuration to go through.

**Comment by jcgoette** [comment]
Seems to still be an issue after PR #376.

Manually changing `Amazon forwarded email addresses` to `""` does still fix it however.

**Comment by firstof9** [comment]
Ooops I missed adding the "", since it's easy to work around for now, I'll fix it but we'll wait for a new release.

Thank you for the feedback.
