### ISSUE TITLE
Mail Gif Never Shows

### ISSUE THREAD

**Issue by mdframe** [moralmunky/Home-Assistant-Mail-And-Packages#377]
I have updated all files to the latest release and I recently re-installed all components for Home-Assistant on a new Debian instance.  I can go look in /config/images/mail_and_packages/mail_today.gif and I see the images however I never get that image in the Lovelace card for Mail and Packages.  It was working previously but I am unable to figure out what I have incorrectly entered to correct.

**Comment by firstof9** [comment]
Please open your issue in the card repo: <https://github.com/moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card>
