### ISSUE TITLE
Only "secure" image filename is produced; no option to not randomize filename

### ISSUE THREAD

**Issue by jwdeville** [moralmunky/Home-Assistant-Mail-And-Packages#378]
This started in version 3.0. The integration only produces a randomized image filename (ie. b332f214-f0ed-402a-9167-0d2ebfe076cf.gif) and there is no option checkbox in the integration configuration to NOT produce this (ie. use the filename mail_today.gif). 

The randomized filename does not work with the companion Lovelace card.

**Comment by firstof9** [comment]
This is by design.

For the Card, please open issues in the Card repo: <https://github.com/moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card>
