### ISSUE TITLE
Integration is not showing up

### ISSUE THREAD

**Issue by gabosom** [moralmunky/Home-Assistant-Mail-And-Packages#383]
Hi, I've installed this integration via HACS but it's not showing up in Configuration -> Integrations. Thoughts?

I looked at the logs and there were no errors for it. 

It's installed and booted:
![image](https://user-images.githubusercontent.com/926425/109329394-5ae91780-780f-11eb-8d2f-fd7a2a247af2.png)

shows up in HACS:
![image](https://user-images.githubusercontent.com/926425/109329430-65a3ac80-780f-11eb-86f8-3893890a9484.png)

nothing in Configuration -> Integration
![image](https://user-images.githubusercontent.com/926425/109329479-781de600-780f-11eb-97db-3a637c8ac7bd.png)

**Comment by firstof9** [comment]
Press F5/Refresh while on the integrations page.

**Comment by gabosom** [comment]
I swear I was doing it and nothing, it's working now after clearing cookies and refreshing. Thx!
