### ISSUE TITLE
[Feature Request] Further Consolidate 

### ISSUE THREAD

**Issue by moralmunky** [moralmunky/Home-Assistant-Mail-And-Packages#401]
**Is your feature request related to a problem? Please describe.**
Thinking out loud here.

- Camera entity becomes the official solution for the mail images in the front end
- The path to the camera entity image **never** changes
  - Could stay where it is now or move it into the integration folder to keep things tidy
  - Stronger case for storing in the integration folder if the integration can create the camera entity automatically
- Change the language of ‘Allow external image use’
  - Something like ‘Create image for companion app notifications’
  - Turning this option on would just create a **copy** of the image in the www folder leaving the camera entity image path the same
- Remove the option of using the www gif in the custom card and hard code the camera entity with a toggle to turn the display of it on or off

So, slimming down configuration options, the main image file path never changes, narrowing the focus in the documentation and secluding the direct gif file to notifications only.

**Comment by firstof9** [comment]
Sounds like a plan.

**Comment by firstof9** [comment]
How about `Create image for notification apps` as the option name?

**Comment by bschatzow** [comment]
Why camera as a default? The image as a default requires no user camera setup (and chance for errors).

**Comment by firstof9** [comment]
> Why camera as a default?

It makes it easier for the companion card I think.

> The image as a default requires no user camera setup (and chance for errors).

The image will still be available.

**Comment by bschatzow** [comment]
Mine works with the companion card with no issue.

**Comment by FuzzyMistborn** [comment]
I was thinking we could use the  `camera.snapshot` feature, but that's not going to work because GIF.

I do like the idea of a camera entity being created by default.  But I think most people care more about getting the mail image in their chat app/notification of choice rather than seeing it in the frontend.  At least in my mind, it's notification first, UI second.  So i'm not sure if it's something we "need" to do.

That being said I know there are a lot of issues getting the camera set up.  Would it be possible to auto create the camera based on the already existing image?  IE automate creating the local_file camera setup?  Instead of going the other way where the camera entity is created and then the user creates the image for notification.  Let me know if that doesn't make sense and I can try to clarify.

**Comment by firstof9** [comment]
> Would it be possible to auto create the camera based on the already existing image? IE automate creating the local_file camera setup?

How about a camera that you don't have to setup at all?

![image](https://user-images.githubusercontent.com/1105672/110857678-63f9d000-8276-11eb-851a-8151979c2848.png)

**Comment by moralmunky** [comment]
I find that both have positives and negatives.

What inclines me to put the camera entity forward as the default is that it rarely, if at all, has image caching issues. There was also a request in the custom card to add a click interaction tot he image to show a larger view and it is super easy with the camera entity. Plus there are many other ways to display a camera entity within Home Assistant and it can also be passed to the companion app through a notification.

Also, with what @firstof9  just shared while I am writing this… if the camera entity is all automated getting people started is so much easier! Zero config.

Reason I still want to keep the gif as an option. I don't like that you have to click a play button in an iOS notification when a camera entity is send. The GIF plays immediately when the notification is opened.

**Comment by FuzzyMistborn** [comment]
> > Would it be possible to auto create the camera based on the already existing image? IE automate creating the local_file camera setup?
> 
> How about a camera that you don't have to setup at all?
> 
> ![image](https://user-images.githubusercontent.com/1105672/110857678-63f9d000-8276-11eb-851a-8151979c2848.png)

That's kinda what I meant, no camera for the user to set up but based on the local image path.  So we get the best of both worlds.

**Comment by firstof9** [comment]
I'm currently testing it on my dev instance. Hopefully the image updates in the morning.

**Comment by firstof9** [comment]
> So we get the best of both worlds.

If this works how I'd like, I could also add a `Mail Amazon Camera` for the Amazon deliveries.

**Comment by firstof9** [comment]
Framework in place:
![image](https://user-images.githubusercontent.com/1105672/111086490-8d666600-84d9-11eb-814e-53fbce421e28.png)

**Comment by firstof9** [comment]
The service for forcing a camera update:
![image](https://user-images.githubusercontent.com/1105672/111243522-7483b080-85be-11eb-958e-6c5042525f07.png)

**Comment by firstof9** [comment]
- [x] The path to the camera entity image never changes
     - [x] Images moved into the integration folder to keep things tidy
- [x] Integration creates its own camera(s)
- [x] Change the language of ‘Allow external image use’
     - [x] Turning this option on would just create a copy of the image in the www folder leaving the camera entity image path the same

@moralmunky I think I have the checklist completed. Just testing it locally before doing a PR.

**Comment by firstof9** [comment]
These changes are in 0.3.2-b3, let me know how it works out.

**Comment by moralmunky** [comment]
Everything is working well. Also been able to reduce the card to just toggle switches since everything except the summary text is included as a standard named sensor.

**Comment by FuzzyMistborn** [comment]
I took the hacky way and just added the images directory in the custom_components folder as a valid external directory.  I don't want no stinking fancy URL/externally accessible image :-D

Everything seems to be working fine.
