### ISSUE TITLE
Mail data is not updating, seeing SEARCH error in the logs.

### ISSUE THREAD

**Issue by gabosom** [moralmunky/Home-Assistant-Mail-And-Packages#405]
2021-03-15 20:41:48 ERROR (SyncWorker_4) [custom_components.mail_and_packages.helpers] Error searching emails: SEARCH command error: BAD [b'Could not parse command']

Don't have much information from the logs. Thoughts on this issue? It used to work before, it suddenly stopped working.

**Comment by moralmunky** [comment]
What version are you running? Are you able to turn on additional debugging for logs?

https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Troubleshooting#enable-debugging

**Comment by gabosom** [comment]
version: 0.3.1

I just turned on additional debugging, will reply with more info in a bit

**Comment by gabosom** [comment]
`2021-03-16 15:55:30 DEBUG (SyncWorker_1) [custom_components.mail_and_packages.helpers] Amazon email search address: "g_xyz_@gmail.com"
2021-03-16 15:55:30 DEBUG (SyncWorker_1) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (FROM ""g_xyz_@gmail.com"" SINCE "13-Mar-2021")
2021-03-16 15:55:30 ERROR (SyncWorker_1) [custom_components.mail_and_packages.helpers] Error searching emails: SEARCH command error: BAD [b'Could not parse command']
2021-03-16 15:55:30 DEBUG (SyncWorker_1) [custom_components.mail_and_packages.helpers] Amazon Count: 0`

**Comment by firstof9** [comment]
So you have an gmail address that fowards Amazon emails to your email account?

**Comment by gabosom** [comment]
I see similar logs that work   like the ones below. Seems like it's adding double "" to my email address

`2021-03-16 16:00:36 DEBUG (SyncWorker_7) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (FROM "thehub@amazon.com" SINCE "16-Mar-2021")`

**Comment by gabosom** [comment]
yes. I created a separate email account to use with this integration and I forward emails to it from my main gmail address.

**Comment by gabosom** [comment]
thx for looking into it, I love the integration! fantastic work.

**Comment by firstof9** [comment]
0.3.2-b2 should fix you up. Let me know if the error persists.

**Comment by gabosom** [comment]
![image](https://user-images.githubusercontent.com/926425/111392722-698b5780-8674-11eb-893d-4e0460692739.png)

working great!

**Comment by gabosom** [comment]
sorry, I hit the close bott

**Comment by gabosom** [comment]
sorry, I hit the close button by mistake.    everything is working great for me now.
