### ISSUE TITLE
Pictures/Images of mail not showing

### ISSUE THREAD

**Issue by xeryax** [moralmunky/Home-Assistant-Mail-And-Packages#408]
I am sure this is something silly that I am just missing -- but a while back, the integration stopped showing me the pictures of my mail in the 'camera' that it manages. I think this correlates to when I migrated to a new physical box, but that shouldnt matter as I am in a docker container running the same command line. (is there a library I am missing?)

Anyways: these are the errors I get that seem to be relevant.
2021-03-19 09:07:35 ERROR (SyncWorker_5) [custom_components.mail_and_packages.helpers] Error searching emails: SEARCH command error: BAD [b'Could not parse command']
Could not read camera mail_usps image from file: /local/mpkg_images/mail_today.gif
Could not read camera mail_usps image from file: /config/www/mpkg_images/316919fb-0dd0-4200-82ad-dc33058c40be.gif

Any ideas/what am I doing wrong?

**Comment by firstof9** [comment]
**Environment (please complete the following information):**
 - OS: [e.g. HassOS/Raspbian/CentOS]
 - Type of device: [e.g. RPi3/NUC/Synology]
 - Home Assistant version: [e.g. 0.105.5]
 - Hassio/Docker/Core? 
 - Component version: [e.g. 0.1.2]

**Comment by xeryax** [comment]
OS: Debian 10 x86_64
Type of device: PC (Intel AtomC2558)
Home Assistant version: [e.g. 0.105.5]  2021.3.4
Hassio/Docker/Core? Docker homeassistant/home-assistant:stable  (core-2021.3.4 (Python 3.8.7))
Component version: [e.g. 0.1.2] 0.3.1 (from HACS, but tried manual install from repo also)

**Comment by firstof9** [comment]
Please [enable debugging](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Troubleshooting#enable-debugging) and post your Home Assistant log.

**Comment by xeryax** [comment]
Log here:
https://pastebin.com/V6uc7cYQ

looks like it is trying to read a .gif when an mp4 is made... but there are a few other things in there that you may be interested in too.

**Comment by firstof9** [comment]
Looks like your automation need to be updated, please see [this link in the wiki](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/USPS-Informed-Delivery-Image#camera-automation) for the updated code.

**Comment by xeryax** [comment]
You're awesome... i actually had old automations in there that were overwriting this... *facepalm*

Thank you!
