### ISSUE TITLE
[Feature Request] Custom "No Mail Today" Image

### ISSUE THREAD

**Issue by D34DC3N73R** [moralmunky/Home-Assistant-Mail-And-Packages#416]
**Is your feature request related to a problem? Please describe.**
I like to use a custom image in place of /config/custom_components/mail_and_packages/mail_none.gif which of course gets replaced with every HA Mail & Packages update.

**Describe the solution you'd like**
I'd really like an option in the integration to supply a custom "no mail today" image to be used in place of the default.

**Describe alternatives you've considered**
My current solution is to replace the mail_none.gif with every HA Mail & Packages update.

**Comment by firstof9** [comment]
I think this is something we could do.

**Comment by moralmunky** [comment]
Not sure the capabilities of the settings input. Maybe a toggle switch to turn it on and then shows the text input field for the image path. I'm thinking some language in the option settings would be good in either sub section or a third step.

I'll draft up language.

**Comment by firstof9** [comment]
The new configuration options:

![image](https://user-images.githubusercontent.com/1105672/121913026-e6ff4c00-cce5-11eb-81dd-0f3a5ec07db8.png)
![image](https://user-images.githubusercontent.com/1105672/121912970-dbac2080-cce5-11eb-8c4a-5dbee1851616.png)

**Comment by firstof9** [comment]
@D34DC3N73R if you'd like to test give 0.3.3-b0 a try

**Comment by D34DC3N73R** [comment]
@firstof9 I've got the beta installed, just waiting for a day without mail.

**Comment by D34DC3N73R** [comment]
@firstof9  I'm having some trouble with this. I reconfigured the integration after installing the beta, and saw the new custom "no image" option (which I would rename "Use custom 'no mail' image"). I set the path in the third step. Which also btw didn't seem to like the /local path. Instead, I set it to /config/www/images/mail_and_packages/no-mail.gif. It then gives me a 'success' message. However, when going back into 'configure' directly after this, the "Use custom 'no image' file?" option is unchecked. It doesn't seem to be saving the configuration for me. The default no mail image is used in the front end.

**Comment by firstof9** [comment]
I'll check it out.

**Comment by firstof9** [comment]
new beta on the way

**Comment by firstof9** [comment]
> Which also btw didn't seem to like the /local path.

correct `/local` isn't valid, it's recommended to use a path not in `www` to store the image ie: `images/your_custom_file.gif`

**Comment by firstof9** [comment]
`0.3.3-b2` released

**Comment by D34DC3N73R** [comment]
I've installed the new beta, 'configured', and was able to save the new 'no image' path `images/no-mail.gif` (which persists when configuring a second time). However, the default image is still used with `custom:mail-and-packages-card`. I'm guessing this is an issue with the card rather than the integration. 
```
      - type: 'custom:mail-and-packages-card'
        name: Mail Summary
        updated: sensor.mail_updated
        details: true
        image: true
        deliveries_message: sensor.mail_deliveries_message
        packages_delivered: sensor.mail_packages_delivered
        packages_in_transit: sensor.mail_packages_in_transit
        fedex_packages: sensor.mail_fedex_packages
        ups_packages: sensor.mail_ups_packages
        usps_packages: sensor.mail_usps_packages
        amazon_packages: sensor.mail_amazon_packages
        usps_mail: sensor.mail_usps_mail
        camera: false
        gif_sensor: sensor.mail_image_url
        camera_entity: camera.mail_usps
```

![image](https://user-images.githubusercontent.com/9123670/122266080-439d6b00-ce8e-11eb-845e-330bc2e12a98.png)

**Comment by firstof9** [comment]
Check the camera entity to see if your custom image is displaying, if it is, I can duplicate the code to the sensor the card uses.

**Comment by D34DC3N73R** [comment]
`camera.mail_usps_camera` is still showing the old default image 
![image](https://user-images.githubusercontent.com/9123670/122274683-ad6e4280-ce97-11eb-9d31-1a3507815fb7.png)

**Comment by firstof9** [comment]
Can you confirm the file_path attribute for `camera.mail_usps_camera` ?

**Comment by firstof9** [comment]
Give b3 a shot.

**Comment by D34DC3N73R** [comment]
Got some weird issues I'm trying to figure out. If I immediately look at the entities after installing, usps camera does show the custom image.
![image](https://user-images.githubusercontent.com/9123670/122304839-bb818a80-ceba-11eb-819b-fe564a0049f1.png)
but even refreshing the entities page makes the camera revert to the old default image.
![image](https://user-images.githubusercontent.com/9123670/122304962-ea97fc00-ceba-11eb-8245-ff6161ac6001.png)

I've deleted the integration, uninstalled it from HACs, restarted, added it to HACs, restarted, and added the integration and the behavior is the same. If I reload the integration, the camera does show the new image, until a page refresh. The amazon camera also displays the new custom image after reloading the integration. `sensor.mail_image_url` remains the old default image even after reloading the integration. In fact, just viewing the sensor.mail_image_url path in a separate tab will make the camera revert to the old default image.

After reloading the integration
![image](https://user-images.githubusercontent.com/9123670/122305346-980b0f80-cebb-11eb-9d34-a8931daaaaad.png)


refreshing the developer-tools/state page
![image](https://user-images.githubusercontent.com/9123670/122305413-b113c080-cebb-11eb-862b-830342999d8d.png)

**Comment by firstof9** [comment]
Try clearing your browser cache, the custom image is supposed to be copied to the one with the random filename. If you enable the debugging and check the log, you'll see it saying that it's copying `images/no-mail.gif` to the random file name.

The initial image is a placeholder to initialize the camera.

**Comment by D34DC3N73R** [comment]
I have cache disabled in chrome dev tools. Also same behavior in incognito mode as well as a different browser (edge). 
I do see this with debug logging (I changed the file name to get updated logs only)
```
$ docker logs home-assistant 2>&1 | grep "no_mail.gif"
2021-06-16 19:00:39 DEBUG (SyncWorker_10) [custom_components.mail_and_packages.helpers] Copying images/no_mail.gif to /config/custom_components/mail_and_packages/images/62d9f080-d317-4a90-9096-34ee4761ff16.gif
```
then a lot of entries like this
```
2021-06-16 19:01:22 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [140223332861744] Sending {"id": 25, "type": "event", "event": {"event_type": "state_changed", "data": {"entity_id": "camera.mail_usps_camera", "old_state": {"entity_id": "camera.mail_usps_camera", "state": "idle", "attributes": {"access_token": "be3f4b090877fb3fe36ef79e2b4f835e37c85f8d2fa08dd38c55200a4d8b49b4", "file_path": "images/no_mail.gif", "host": "imap.gmail.com", "friendly_name": "Mail USPS Camera", "entity_picture": "/api/camera_proxy/camera.mail_usps_camera?token=be3f4b090877fb3fe36ef79e2b4f835e37c85f8d2fa08dd38c55200a4d8b49b4", "supported_features": 0}, "last_changed": "2021-06-17T02:00:52.344823+00:00", "last_updated": "2021-06-17T02:00:52.344823+00:00", "context": {"id": "c260f91064cb6274b58bcd8d8e741f4f", "parent_id": null, "user_id": null}}, "new_state": {"entity_id": "camera.mail_usps_camera", "state": "idle", "attributes": {"access_token": "be3f4b090877fb3fe36ef79e2b4f835e37c85f8d2fa08dd38c55200a4d8b49b4", "file_path": "/config/custom_components/mail_and_packages/images/62d9f080-d317-4a90-9096-34ee4761ff16.gif", "host": "imap.gmail.com", "friendly_name": "Mail USPS Camera", "entity_picture": "/api/camera_proxy/camera.mail_usps_camera?token=be3f4b090877fb3fe36ef79e2b4f835e37c85f8d2fa08dd38c55200a4d8b49b4", "supported_features": 0}, "last_changed": "2021-06-17T02:00:52.344823+00:00", "last_updated": "2021-06-17T02:01:22.368608+00:00", "context": {"id": "ab465ecb8d568192762a16c4bd25ced9", "parent_id": null, "user_id": null}}}, "origin": "LOCAL", "time_fired": "2021-06-17T02:01:22.368608+00:00", "context": {"id": "ab465ecb8d568192762a16c4bd25ced9", "parent_id": null, "user_id": null}}}
```

however, when I actually look at /config/custom_components/mail_and_packages/images/62d9f080-d317-4a90-9096-34ee4761ff16.gif it's the old default image. 

![62d9f080-d317-4a90-9096-34ee4761ff16](https://user-images.githubusercontent.com/9123670/122319930-36a46a00-ced6-11eb-8c37-49b2f2c288cf.gif)

**Comment by D34DC3N73R** [comment]
`sensor.mail_image_url` never seems to be getting the updated image. it's also stored in a different location /local/mail_and_packages/62d9f080-d317-4a90-9096-34ee4761ff16.gif

**Comment by firstof9** [comment]
Yup still poking it to see what's going on, I'll post an update once I have it

**Comment by firstof9** [comment]
I've found where the error is, missed a spot, I'll drop another beta shortly.

**Comment by firstof9** [comment]
beta4 should have it fixed now

**Comment by D34DC3N73R** [comment]
I have it installed. waiting for another day without mail 👍

**Comment by firstof9** [comment]
You should see it in the morning before the USPS email comes in. 👍

**Comment by D34DC3N73R** [comment]
v0.3.3-b4 is working great 👍
![image](https://user-images.githubusercontent.com/9123670/122521020-31741780-cfc9-11eb-8bb9-03a46eb5eaaf.png)
