### ISSUE TITLE
icloud email support

### ISSUE THREAD

**Issue by getsmokes** [moralmunky/Home-Assistant-Mail-And-Packages#418]
Is this platform support?

I get the following error 

custom_components.mail_and_packages] Unexpected error fetching Mail and Packages (imap.mail.me.com) data: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):

**Comment by firstof9** [comment]
A bug report isn't the place to ask questions, please use the [github discussions](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/discussions) sections for Q&A.
