### ISSUE TITLE
image-no-mailpieces700.jpg error

### ISSUE THREAD

**Issue by moralmunky** [moralmunky/Home-Assistant-Mail-And-Packages#42]
The informed delivery function will only copy the image-no-mailpieces700.jpg to the www path if the mail_none.gif does not exist This is true on the first install but not once an informed delivery email comes through that has the need for the image-no-mailpieces700.jpg. The image-no-mailpieces700.jpg file is then removed from the www path when the temporary images are deleted and will return file not found error and the component stops functioning.

I see two options:
1. Remove the image-no-mailpieces700.jpg from the array before we delete the temporary image
2. Reference the mail_none.gif and image-no-mailpieces700.jpg from the custom_component folder when they are needed to create the gif and no longer copying them to the www path.

I think option 2, @firstof9 thoughts? I don't think there is a need for copying those files any longer. And since we only have a need for the gif to be stored in the www file, we could probably do it in in www without creating a subfolder.

**Comment by firstof9** [comment]
The ```www/mail_and_packages``` directory helps keep the mail_today.gif in an organized location, but I'd ask for feedback from the users honestly. If they'd perfer it just in ```www``` that's easy to do as well.

Technically we could keep the gifs in the component directory and not copy them anywhere only the ```mail_today.gif```

**Comment by moralmunky** [comment]
#43 references the files from the custom_component directory when needed. I forgot that the user is given the option where to store the file in the component setup so it's their choice where it goes.
