### ISSUE TITLE
ISSUE: Setup Failed

### ISSUE THREAD

**Issue by GoState** [moralmunky/Home-Assistant-Mail-And-Packages#445]
**Describe the bug**
I'm getting this setup failed for numpy but I have never touched or installed this in the past.  I looked at the links referenced below but am not sure which option, if any would apply as Im not sure how this library is normally installed.

**Environment (please complete the following information):**

version | core-2021.4.3
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 4.19.0-16-amd64
arch | x86_64
timezone | America/New_York

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4820
Installed Version | 1.11.3
Stage | running
Available Repositories | 847
Installed Repositories | 29

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 18

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2021.04.0
docker_version | 20.10.6
disk_total | 181.1 GB
disk_used | 15.2 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.2.0), Mosquitto broker (5.1.1), NGINX Home Assistant SSL proxy (3.0.1), Duck DNS (1.12.5), Samba share (9.3.1), AdGuard Home (4.0.0), MariaDB (2.3.0), WireGuard (0.5.1), Home Assistant Google Drive Backup (0.103.1), AppDaemon 4 (0.6.0), chrony (2.0.2), TasmoBackup (1.04.10), Glances (0.11.2), Visual Studio Code (3.3.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 19
views | 11
mode | storage

</details>

**Logs**
Logger: homeassistant.setup
Source: setup.py:163 
First occurred: 11:59:43 AM (1 occurrences) 
Last logged: 11:59:43 AM

Setup failed for mail_and_packages: Unable to import component: IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE! Importing the numpy C-extensions failed. This error can happen for many reasons, often due to issues with your setup or how NumPy was installed. We have compiled some common reasons and troubleshooting tips at: https://numpy.org/devdocs/user/troubleshooting-importerror.html Please note and check the following: * The Python version is: Python3.8 from "/usr/local/bin/python3" * The NumPy version is: "1.18.5" and make sure that they are the versions you expect. Please carefully study the documentation linked above for further help. Original error was: Error loading shared library libopenblas.so.3: No such file or directory (needed by /usr/local/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so)

**Screenshots**

**Additional context**
This began appearing after updating HA to the April release.

**Comment by firstof9** [comment]
Try restarting Home Assistant (the container not the OS).

**Comment by GoState** [comment]
> Try restarting Home Assistant (the container not the OS).

I stopped the homeassstant container then restarted it (via docker commands) and I still see this error.  I assume that is the container you meant, there are these other containers with the hassio/home assistant as part of the name:
hassio_cli
hassio_audio
hassio_dns
hassio_supervisor

Is there anything else that I could provide that might be helpful?  

I also tried uninstalling the Mail in Packages integration in HACS and in Configuration>>Integrations and commented out the camera  entries in the configuration.yaml file then added it all back but am still getting this error.

**Comment by GoState** [comment]
This shows in the Notifications section after restarting HA:
The following integrations and platforms could not be set up:

mail_and_packages
Please check your config and logs.

The logs is a link and takes you to the error i listed in the first post.

**Comment by firstof9** [comment]
Update to the latest: `core-2021.4.6`

**Comment by GoState** [comment]
upgraded o 2021.4.6 and the issues went away.  Still tracking down an issue with the camera but its generally working now! Thanks!!!
