### ISSUE TITLE
ISSUE: Subscript error when no packages are expected.

### ISSUE THREAD

**Issue by socaljr53** [moralmunky/Home-Assistant-Mail-And-Packages#449]
**Describe the bug**
It looks as though there isn't any data being passed as I'm guessing the package count is 'null' therefore it's assuming there is a 'NoneType' value which by definition, isn't subscriptable.

**Environment (please complete the following information):**
 - OS: HAOS 5.4.109
 - Type of device: [e.g. RPi3/NUC/Synology]
 - Home Assistant version: 2021.4.6
 - Python: 3.8.7

**Logs**
![Logfile](https://user-images.githubusercontent.com/78208603/116566280-7b8b2780-a8bb-11eb-9bb1-bafee8d3161c.png)

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment]
Please in the future do not screenshot logs.
I'll look into this error.

**Comment by firstof9** [comment]
Please [enable debugging](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Troubleshooting#enable-debugging) and post the messages from the Home Assistant log leading up to this error.

**Comment by socaljr53** [comment]
There you go Chris.  Thanks so much for looking into this.


[Logfile.txt](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/files/6402044/Logfile.txt)

**Comment by firstof9** [comment]
`2021-04-29 09:34:36 ERROR (MainThread) [custom_components.mail_and_packages] Timeout fetching Mail and Packages (imap.mail.yahoo.com) data`

Increase the IMAP timeout in the configuration screen.
![image](https://user-images.githubusercontent.com/1105672/116627772-9b920980-a902-11eb-909b-73eb9297a56b.png)
Try 60 seconds, yahoo seems to be the only problematic provider that I've seen reported so far.
