### ISSUE TITLE
ISSUE: not receiving UPS or FedEx delivery notifications in mail and packages 

### ISSUE THREAD

**Issue by benchdog93** [moralmunky/Home-Assistant-Mail-And-Packages#450]
**Describe the bug**
I am seeing my USPS deliveries in mail and packages but not UPS and FedEx. I am getting delivery notifications by email form both UPS and FedEx in the same gmail account. I have never received UPS or FedEx alerts.

thank you for your help

**Environment (please complete the following information):**
 - OS: [current HA OS and Supervisor]
 - Type of device: [Synology/VMM]
 - Home Assistant version: [current]
 - Hassio/Docker/Core? 
 - Component version: [current]

**Comment by firstof9** [comment]
Do you have the sensors enabled for FedEx and UPS?
![image](https://user-images.githubusercontent.com/1105672/116785920-efab0400-aa50-11eb-9986-3fc90a6b1314.png)

**Comment by benchdog93** [comment]
Thank you for the quick response. Yes, I initially enabled the sensors, and when I view them in developer tools, they are available and show 0. In my card, I have them enabled.
![Capture](https://user-images.githubusercontent.com/51010158/116786457-aa94cb00-aa6c-11eb-83d8-432268596fe6.GIF)

**Comment by firstof9** [comment]
[Enable debugging](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Troubleshooting#enable-debugging) and post the Home Assistant log so I can see what's happening.

**Comment by benchdog93** [comment]
I enabled the logging and I have  a UPS package coming Monday. I will upload the log file then.
Thank you

**Comment by benchdog93** [comment]
Wanted to let you know today it worked as expected. Thank you
