### ISSUE TITLE
[Feature Request] Muambator integration

### ISSUE THREAD

**Issue by antunes49** [moralmunky/Home-Assistant-Mail-And-Packages#451]
**Is your feature request related to a problem? Please describe.**
nop

**Describe the solution you'd like**
Add support for muambator emails

**Describe alternatives you've considered**
none?

**Additional context**
Muambator is a platform for tracking packages very famous in brazil, it tracks shipments from Correios, China Post, Aliexpress, Wish and Gearbest 
Attached here is a doc with prints and the content inside the emails we get from muambator when we have any update

[Muambator integration.odt](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/files/6438358/Muambator.integration.odt)

**Comment by firstof9** [comment]
We'd need to have the from address and the subject line for each type of email sent.

**Comment by antunes49** [comment]
all the emails came from: Muambator <muambator@muambator.com.br>
subject for the update: [MUAMBATOR] - Movimentação do pacote LB105236292HK (USB-C)
subject for the out for delivery: [MUAMBATOR] - Movimentação do pacote LE130701680SE (Ram ygor)
subject for delivered: [MUAMBATOR] - Movimentação do pacote LE130701680SE (Ram ygor)

The subject for them are all equal, the only thing that's changed is the number of the item being tracked and the friendly name that come after the tracking number, all the data is in the body of the email.

**Comment by firstof9** [comment]
Unfortunately the email subjects nor the body have enough information for us to use in order to determine shipping status properly. 👎

**Comment by antunes49** [comment]
The body of each email as i sent has a part that is as follows:

Ram ygor (LE130701680SE)
    • 06/05/2021 10:47 - Unidade de Distribuição - Sao Paulo/SP - Objeto saiu para entrega ao destinatário

they all follow the same pattern

*Friendly name* (*Tracking number*)
    • *DD/MM/YYYY* *HH:MM* - *place that generated the update* - *city/state* - *data of the update*

The most important one would be the data of the update, as it's what is telling what's the status, from the example above 
- Objeto saiu para entrega ao destinatário- it would be translated as Out for delivery, as all the data is in Portuguese it would be easier to just copy and paste what's on that area of the body of the email

**Comment by firstof9** [comment]
The problem is they're all stacked into a single email. This makes it much harder to parse out.
