### ISSUE TITLE
ISSUE: Advertisement separator is considered mail image.

### ISSUE THREAD

**Issue by KairuByte** [moralmunky/Home-Assistant-Mail-And-Packages#454]
**Describe the bug**
My daily digest today, included an advert from legoland. Within that advert is an image of a long black line, I assume for aesthetics. However that line is being considered an image of mail by the integration. This adds to the number of expected mail pieces (increased by 1 in this case, from 2 to 3) and also adds the black bar image to the mail image gif. 

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: RPi4
 - Home Assistant version: 2021.5.5
 - Core
 - Component version: 0.3.2

**Logs**
None

**Screenshots**
Can provide on request.

**Additional context**
The HTML of the sections does appear unique enough that you could parse out "only mail". I can provide a slightly sterilized version of the message privately if requested.

**Comment by firstof9** [comment]
Interesting, could you supply an image?
What's the filename associated with the long black line?

**Comment by KairuByte** [comment]
File name is pretty much identical in form to the mail images: email%20(004).mht!cid:1014167724-004.jpg_560755452177843

Image of the line in question:
![image](https://user-images.githubusercontent.com/393806/120543998-8d785280-c3b2-11eb-85f6-56dc7816f163.png)

**Comment by firstof9** [comment]
Very odd, I have that same advertisement in my email but there's an image of inbound mail above it not a black line.

**Comment by firstof9** [comment]
I'm going to error on the side that this _**is**_ a piece of mail that wasn't properly scanned by the USPS sorting machine.

**Comment by KairuByte** [comment]
Mmmm, I'm not sure that would make sense in this context? The line is under "FROM LEGOLAND" but above the legoland image.

I'll cross check what came in and try to figure out if anything didn't get a proper scan.

**Comment by firstof9** [comment]
This is how mine displayed:
![image](https://user-images.githubusercontent.com/1105672/120659091-df64bb00-c43a-11eb-95b8-c666570754b4.png)

**Comment by KairuByte** [comment]
Aaaah, okay, that looks identical in setup, and there was indeed a ValPack that had not been imaged.

I'll go agreed and close this, as far as I am concerned you were spot on about it being a bad scan of a piece of mail.
