### ISSUE TITLE
[Feature Request] All in transit packages

### ISSUE THREAD

**Issue by JOHLC** [moralmunky/Home-Assistant-Mail-And-Packages#456]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Per [this](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Troubleshooting) page
````The integration is only reporting on packages that are in transit to be delivered the current day. It does not report in-transit packaged delivered on a future day.````

I think it would be nice to see all incoming deliveries and their estimated date

**Describe alternatives you've considered**
Manually checking email 

**Additional context**
N/A

**Comment by firstof9** [comment]
This unfortunately isn't feasible utilizing the email method.
