### ISSUE TITLE
GMail Error - 'NoneType' object has no attribute 'group

### ISSUE THREAD

**Issue by paulmorabito** [moralmunky/Home-Assistant-Mail-And-Packages#459]
Hi,

I'm running the latest version of Mail & Packages in latest HassOS and have begun to receive the following error:

```
Error fetching Mail and Packages (imap.gmail.com) data: 'NoneType' object has no attribute 'group'
```

All of the sensors are now unavailable as a result of this. I can definitely access gmail and also re-configured the plugin and got the same error. Any idea what this could be?

Thanks in advance,

**Comment by firstof9** [comment]
Try adjusting the IMAP timeout setting to a higher number.
