### ISSUE TITLE
Failure after adding the Mail and Packages integration

### ISSUE THREAD

**Issue by zarurc** [moralmunky/Home-Assistant-Mail-And-Packages#46]
After clicking on the "Mail and Packages" integration, I get a long loading screen and then it fails and throws me back to the integrations list.
Reproduce: after installing using HACS I go to the integrations page, search for Mail and Packages integration.

> fetch-with-auth.ts:20 POST https://hassio-url.ui.nabu.casa/api/config/config_entries/flow net::ERR_EMPTY_RESPONSE

**Comment by firstof9** [comment]
Where do you see this error message?

**Comment by zarurc** [comment]
I see the error in my console. 
After clicking to add the integration, I get a spinner for about a minute then it fails and I get the error.

**Comment by firstof9** [comment]
This is with version 0.1.1?
Are you using HassIO/Docker?
On a Pi?

**Comment by zarurc** [comment]
yes, version Installed: 0.1.1
Hassio on a RPI3

**Comment by firstof9** [comment]
Should be fixed with 0.1.2.

**Comment by firstof9** [comment]
@zarurc Did the latest version work for you?

**Comment by zarurc** [comment]
Yes it did. thank you!
I had to uninstall and reinstall M&P integration but it is working now.
