### ISSUE TITLE
ISSUE: Possible USPS Package delivery subject change

### ISSUE THREAD

**Issue by FuzzyMistborn** [moralmunky/Home-Assistant-Mail-And-Packages#473]
**Describe the bug**

Not 100% sure if this is actually a change, or related to the fact I got an exception email last night for a failed delivery, but noticed my USPS emails weren't getting filtered to the appropriate folder.  Looks like a subject line change (same sender), so instead of "USPS® Expected Delivery on DATE arriving by 3:15pm TRACKING_#" it's now "USPS® Out for Delivery TRACKING_#"

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Type of device: x86
 - Home Assistant version: 2021.06.5
 - Hassio/Docker/Core? Docker
 - Component version: 0.3.2

**Logs**
Paste your error logs here.

None

**Screenshots**

![image](https://user-images.githubusercontent.com/16689090/124940751-3d576600-dfd8-11eb-8e25-348acf5b1ae6.png)

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment]
Technically it should have still picked up as "in transit" did it not do this?

**Comment by FuzzyMistborn** [comment]
It does not no.  All USPS related sensors (other than mail) are 0.  And even `sensor.mail_packages_in_transit` is 0.

**Comment by firstof9** [comment]
Ah right we're checking the subject AND the body.

**Comment by firstof9** [comment]
Should be fixed in `0.3.3-b5`

**Comment by FuzzyMistborn** [comment]
Ok.  Updating to 2021.7 today so I'll test out b5 while I'm restarting :-)

**Comment by FuzzyMistborn** [comment]
Yep, it's fixed!  Thank you sir!
