### ISSUE TITLE
[Feature Request] Add amazon_it_out_for_delivery.eml

### ISSUE THREAD

**Issue by NdR91** [moralmunky/Home-Assistant-Mail-And-Packages#477]
Please, can you add the "Out for Delivery" recognize for Italian language

Here enclosed you can find the original .eml file for your reference.

[amazon_it_out_for_delivery.eml.eml.zip](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/files/6786443/amazon_it_out_for_delivery.eml.eml.zip)

**Comment by firstof9** [comment]
We don't do an "out for delivery" email with amazon as it's inconsistent.

**Comment by NdR91** [comment]
Ah ok, sorry!

I saw thos one: https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/blob/master/tests/test_emails/amazon_uk_out_for_delivery.eml

And i thought It was tha same as the Italian one!

**Comment by firstof9** [comment]
Ya, unfortunately the don't always send those emails out, especially in the US.
