### ISSUE TITLE
ISSUE: Amazon IT "Shipped" seems not working

### ISSUE THREAD

**Issue by NdR91** [moralmunky/Home-Assistant-Mail-And-Packages#478]
**Describe the bug**
Shipped packages are not displayed on Italian version

**Environment (please complete the following information):**
 - OS: Debian
 - Type of device: NUC
 - Home Assistant version: 2021.7
 - Hassio/Docker/Core? Core
 - Component version: 3.2

**Screenshots**
Delivered Packages are displayed correctly:
![Schermata 2021-07-08 alle 22 08 08](https://user-images.githubusercontent.com/52299148/124984086-1715e280-e039-11eb-8e3b-b6123315ca9a.jpg)

Shipped Paxkages always stay at 0 (currently I have 2 on the way):
![Schermata 2021-07-08 alle 22 08 26](https://user-images.githubusercontent.com/52299148/124984162-2ac14900-e039-11eb-9a7b-4dfbdc36dab8.jpg)

**Comment by firstof9** [comment]
Does your email from `conferma-spedizione@amazon.it` have the `Arriver:` date?

**Comment by NdR91** [comment]
Sure, see the picture below:

![arrival_date](https://user-images.githubusercontent.com/52299148/125031321-c4feac80-e08c-11eb-90dc-df1126f812d1.png)

"09 Luglio" is "09 July" in Italian.

If you need the email, I attach it here.

[Il tuo ordine Amazon.it che include upHere ttmod Sleeved Cable... è stato spedito.zip](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/files/6789121/Il.tuo.ordine.Amazon.it.che.include.upHere.ttmod.Sleeved.Cable.e.stato.spedito.zip)

**Comment by firstof9** [comment]
That could be why it's not working, I _think_ the python libraries only use English, would be nice if they used `YYYY/MM/DD` format.

**Comment by NdR91** [comment]
Do you think there's a workaround?

**Comment by firstof9** [comment]
I'll have to do some reasearch.

**Comment by firstof9** [comment]
I may have found something to fix it, I'll see what I can come up with tomorrow.

**Comment by firstof9** [comment]
Do you have your system's locale set to your language?

**Comment by NdR91** [comment]
Here is the output:

```
LANG=it_IT.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

Do I need to change it?

**Comment by firstof9** [comment]
So as far as I am aware, if you were to adjust the `locale` to `it_IT.UTF-8` it should process the Amazon email for your correctly.

Here's 2 ways you should be able to do this from the SSH prompt:
`sudo localectl set-locale LC_TIME=it_IT.UTF-8`
OR
`sudo update-locale LC_TIME=it_IT.UTF-8`

This will only adjust the time locale which is what is used when processing emails, it _should_ parse in Italian for you this way.

**Comment by NdR91** [comment]
Thank you mate! Will try this today!

**Comment by NdR91** [comment]
Ok, for some reason if I use "locale", my output is still:

```
LANG=it_IT.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

But my file "/etc/default/locale" is corrected:

```
LANG=it_IT.UTF-8
LANGUAGE=en_US:en
LC_ALL=en_US.UTF-8
LC_TIME=it_IT.UTF-8
```

And the date format seems to be ok:

```ndr@NdR-NUC:~$ date
Mon 12 Jul 2021 08:13:50 AM CEST```

But the "packages" entity is still not working...

**Comment by NdR91** [comment]
I understood the issue.

The date format is ok on my machine, but it's not on my Home Assistant container:

```
bash-5.1# cat /etc/timezone
Europe/Rome
bash-5.1# date
Mon Jul 12 08:35:52 CEST 2021
```

**Comment by firstof9** [comment]
> Any idea on how to change it on an Alpine based Container?

Should be the same commands.

**Comment by NdR91** [comment]
Unfortunately no:

```bash-5.1# localectl set-locale LC_TIME=it_IT.UTF-8
bash: localectl: command not found
bash-5.1# update-locale LC_TIME=it_IT.UTF-8
bash: update-locale: command not found```

**Comment by firstof9** [comment]
Try:
```apk --no-cache add musl-locales musl-locales-lang```

**Comment by NdR91** [comment]
>Try:
>apk --no-cache add musl-locales musl-locales-lang

Thank's.
I tried this, but the commands are still not working... Do i need to modify some file?

**Comment by firstof9** [comment]
Ok I'll see if I can do something programmatically then.

**Comment by firstof9** [comment]
Give beta `0.3.3-b6` a go lets see if it'll parse your email properly.

**Comment by firstof9** [comment]
I'll see about adding your provided email to the tests as well.
Thank you for that.

**Comment by NdR91** [comment]
Thank you very much for your job!

I still see "0" on the entity "sensor.mail_amazon_packages", with two packages shipped..

**Comment by firstof9** [comment]
Ok this next one fixes it for sure now.

**Comment by firstof9** [comment]
Give `0.3.3-b7` a try, should work properly now.

**Comment by NdR91** [comment]
> Give `0.3.3-b7` a try, should work properly now.

I receive this error:

 ```
Logger: custom_components.mail_and_packages.helpers
Source: custom_components/mail_and_packages/helpers.py:1226
Integration: Mail and Packages (documentation, issues)
First occurred: 21:16:54 (28 occurrences)
Last logged: 21:16:59
International dates not supported. (time data 'martedì 13 luglio' does not match format '%A %d %B')
```

**Comment by firstof9** [comment]
Try issuing: `apk add musl-locales` from inside the HA container. Then see if it works.

**Comment by NdR91** [comment]
> apk add musl-locales

No =(
Same log

**Comment by firstof9** [comment]
When you execute `locale` in the container do you get something like this:
```
bash-5.1# locale
LANG=C.UTF-8
LC_CTYPE=C.UTF-8
LC_NUMERIC=C.UTF-8
LC_TIME=C.UTF-8
LC_COLLATE=C.UTF-8
LC_MONETARY=C.UTF-8
LC_MESSAGES=C.UTF-8
LC_ALL=
bash-5.1# 
```

**Comment by NdR91** [comment]
Yes, this is the output:

```
bash-5.1# locale
LANG=C.UTF-8
LC_CTYPE=C.UTF-8
LC_NUMERIC=C.UTF-8
LC_TIME=C.UTF-8
LC_COLLATE=C.UTF-8
LC_MONETARY=C.UTF-8
LC_MESSAGES=C.UTF-8
LC_ALL=
```

**Comment by firstof9** [comment]
Does `locale -a | grep it` output `it_IT` as one of the outputs?

**Comment by firstof9** [comment]
As a quick test you can adjust `const.py` line 82 to this:

```python
AMAZON_LANGS = ["it_IT", "it_IT.UTF-8", ""]
```

and test again.

**Comment by NdR91** [comment]
> Does `locale -a | grep it` output `it_IT` as one of the outputs?

Here is the output:
```
bash-5.1# locale -a | grep it
it_CH
it_IT
```

> As a quick test you can adjust `const.py` line 82 to this:
> 
> ```python
> AMAZON_LANGS = ["it_IT", "it_IT.UTF-8", ""]
> ```
> 
> and test again.

Sure, going to test it now!

**Comment by firstof9** [comment]
Give the latest beta a try.

**Comment by NdR91** [comment]
No differences, unfortunately.

I'm on b11 right now.

![image](https://user-images.githubusercontent.com/52299148/125878777-78aaffc4-a0c8-4841-8455-1ff3030154cf.png)

**Comment by firstof9** [comment]
That sucks because the tests pass and they don't throw the warning message.
I'm not really sure.
