### ISSUE TITLE
Still seeing "user input malformed" on config flow in 0.3.2

### ISSUE THREAD

**Issue by mikeygnyc** [moralmunky/Home-Assistant-Mail-And-Packages#483]
This is on an attempt to reconfigure. I added the "" to the amazon forwards field as mentioned in previous issues with no improvement.
<img width="603" alt="Screen Shot 2021-07-13 at 11 28 15 PM" src="https://user-images.githubusercontent.com/37052465/125556803-c9f2355f-c965-4675-ad14-00d1b58e59e1.png">

**Comment by firstof9** [comment]
What version of the integration?

**Comment by mikeygnyc** [comment]
0.3.2

**Comment by firstof9** [comment]
Can you check your HA logs to see what the error is?

**Comment by mikeygnyc** [comment]
There are no related errors showing up in the log.

**Comment by firstof9** [comment]
Oh your scan interval is too low, minimum is `5`.

**Comment by firstof9** [comment]
There is a range check, but I'll look into adding it to the input validation function.
