### ISSUE TITLE
Time Data Does Not Match Format

### ISSUE THREAD

**Issue by ariesboy416** [moralmunky/Home-Assistant-Mail-And-Packages#494]
Until very recently, the integration was working perfectly. Yesterday, all my mail sensors suddenly became unavailable and I've tried several times to uninstall and reconfigure the integration to no avail. Here's the error I'm seeing in the logs:

This error originated from a custom integration.

Logger: custom_components.mail_and_packages
Source: helpers/update_coordinator.py:219
Integration: Mail and Packages (documentation, issues)
First occurred: 9:34:35 AM (1 occurrences)
Last logged: 9:34:35 AM

Error fetching Mail and Packages (outlook.com) data: time data '* Tuesday, Ju' does not match format '%A, %B %d'

I'm thinking Outlook updated something in their time formatting that caused the integration to stop working. Any thoughts?

**Comment by firstof9** [comment]
**Environment (please complete the following information):**
 - OS: [e.g. HassOS/Raspbian/CentOS]
 - Type of device: [e.g. RPi3/NUC/Synology]
 - Home Assistant version: [e.g. 0.105.5]
 - Hassio/Docker/Core? 
 - Component version: [e.g. 0.1.2]

**Comment by ariesboy416** [comment]
OS: HassOS
Type of Device: HP Pavilion Laptop (host machine)
HA Version: 2021.6.6
Hassio on Virtualbox VM
Component version: 0.3.2

**Comment by firstof9** [comment]
Give the latest beta a try it will likely clear that error up.

**Comment by ariesboy416** [comment]
I don't see anything beyond 0.3.2 in HACS, even with "show beta" enabled (would it be master?):

![image](https://user-images.githubusercontent.com/68986118/126512880-f92e30f3-2565-4f09-a1da-b9118f5041bc.png)

**Comment by firstof9** [comment]
> would it be master?

No

I think HACS has throttled down it's refresh time, so you'll need to 'Update Info' for the repo after turning on the "show betas".

![image](https://user-images.githubusercontent.com/1105672/126541125-d220c61d-9511-49c1-b66f-853f63f9590c.png)

**Comment by ariesboy416** [comment]
Tried it (version 0.3.3-b11), it worked for about a minute then my sensors were unavailable again. New errors are showing up now though, the most similar being this:

```
This error originated from a custom integration.

Logger: custom_components.mail_and_packages.helpers
Source: custom_components/mail_and_packages/helpers.py:1229
Integration: Mail and Packages (documentation, issues)
First occurred: 2:43:05 PM (18 occurrences)
Last logged: 2:53:26 PM

International dates not supported. (unconverted data remains: Track)
International dates not supported. (time data '* Tuesday, Jul' does not match format '%A, %B %d')

```

Before that there was an IMAP login error and a timeout but I think those resolved themselves.

**Comment by firstof9** [comment]
Can you [enable debugging](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Troubleshooting#enable-debugging) and post the log so we can get a clearer picture?

**Comment by ariesboy416** [comment]
Okay, I can still post the logs if you'd like me to, but after viewing them, I think I found the source of the problem.

Everything works normal until the integration checks for Amazon packages. The error is a result of the emails that are being forwarded from gmail where the date is shown as "Tue, Jul 20" (see image below). 

![image](https://user-images.githubusercontent.com/68986118/126557070-a8060e3b-1b0c-42cc-acb6-a497eff8880f.png)

I reconfigured the integration and did not include any Amazon sensors and that fixed the issue. However, I had to delete the day-old email that was causing this issue before reconfiguring again and including Amazon package sensors. I'll go ahead and change the email on my Amazon account as this issue seems to be caused by forwarding from Gmail.

What's odd is that when this sensor fails, all of them fail as well. Is there a way to get it so that it only makes the sensor that's throwing the error unavailable?

**Comment by firstof9** [comment]
> Everything works normal until the integration checks for Amazon packages. The error is a result of the emails that are being forwarded from gmail where the date is shown as "Tue, Jul 20" (see image below).

That's not the date that's used when parsing the Amazon emails it's the date after `will arrive:,estimated delivery date is:,guaranteed delivery date is:,Arriving:,Arriverà:` in the email body.



> What's odd is that when this sensor fails, all of them fail as well. Is there a way to get it so that it only makes the sensor that's throwing the error unavailable?

No it's an all or nothing.
