### ISSUE TITLE
ISSUE: not showing all mail images in image roll

### ISSUE THREAD

**Issue by rdgerken** [moralmunky/Home-Assistant-Mail-And-Packages#496]
I'm frequently having the issue where not all the images are showing up for the day with USPS Informed delivery. For example, the email might have 4 pieces of mail with 4 images for the day. The HASS sensor will show the correct number of pieces (4), but the camera roll shows only the first 2 images. I've seen this happen quite often.

I'm running Home Assistant on Docker 2021.7.1, Mail and Packages 0.3.2

Thanks!

**Comment by firstof9** [comment]
Check the email they send, if it's the junk mail flyers they're sending, those images don't get inserted into the image roll.

**Comment by rdgerken** [comment]
Yes, I have confirmed that there are images in the email that are not showing up in the image roll.

**Comment by firstof9** [comment]
If the image file contains the names in this list:
https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/blob/9cb8144d0961b36db032e64408175ba1552af24a/custom_components/mail_and_packages/helpers.py#L550

they are ignored as junk and not added the the image roll.

**Comment by rdgerken** [comment]
Well this is interesting... the raw GIF is actually correct. All the images are in there as they should be. The problem seems to be with the camera component in my home assistant. It cycles the first two images of the gif repeatedly, but then starts over, cutting off the last two images in the GIF, so it appears that they are missing, when in reality, they are there, but the GIF is getting started over.

**Comment by firstof9** [comment]
are you using the built in camera entities?

**Comment by rdgerken** [comment]
Yes, I'm using the built in Picture/Picture Glance lovelace cards. I'm not sure why it is behaving this way, but looks to be a problem on the Home Assistant side, not this component.

**Comment by moralmunky** [comment]
@rdgerken The camera component are designs to refresh about every 10 seconds to grab a new version of a status image file. I believe this was based on how some physical cameras deliver new imagery. The time leanth of the GIF needs to be less than 10 seconds using those love lace cards.  See the note [here in the WIKI](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/USPS-Informed-Delivery-Image#standard-lovelace-cards).

You can reduce the length by lowering the default ‘Image duration’ in the integration’s second page of settings. This will reduce the time each frame in the GIF is displayed. If you regularly get high volume of mail you may have to set it to 1 second or less to cycle through all.

Alternatively you can use the [custom card](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card) which displays the GIF file directly in HTML in the front end.

**Comment by rdgerken** [comment]
Hey guys, thanks for the help on this! I found that by setting the camera view option from "auto" to "live" on the picture entity card, it fixed my problem.  @moralmunky - thanks for the tip on the image duration - that is good to know as well.
