### ISSUE TITLE
ISSUE: IMAP Command error

### ISSUE THREAD

**Issue by boctok** [moralmunky/Home-Assistant-Mail-And-Packages#497]
**Describe the bug**
After reinstallation to enable Amazon, everything is unavailable.

**Environment (please complete the following information):**
 - OS: HassOS 
 - Type of device: ODROID-N2+
 - Home Assistant version: 6.1
 - Hassio/Docker/Core? Hassio
 - Component version: ?

**Logs**
```
This error originated from a custom integration.

Logger: custom_components.mail_and_packages.helpers
Source: custom_components/mail_and_packages/helpers.py:458
Integration: Mail and Packages (documentation, issues)
First occurred: 10:56:48 AM (11 occurrences)
Last logged: 11:51:46 AM

Error fetching emails: FETCH command error: BAD [b'[CLIENTBUG] FETCH Command arguments invalid']
```

**Screenshots**

**Additional context**
The only thing that was done differently was to enable the Amazon sensors.

**Comment by firstof9** [comment]
Please [enable debugging](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Troubleshooting#enable-debugging) and post the logs from the `home-assistant.log` file so we can see what's going on.

**Comment by firstof9** [comment]
Also note, reinstallation isn't required to enable sensors, pressing the `Configure` button allows you to change all the settings.
