### ISSUE TITLE
-1 Packages in transit

### ISSUE THREAD

**Issue by moralmunky** [moralmunky/Home-Assistant-Mail-And-Packages#5]
In Transit shows -1 after deliveries are completed due to a new UPS subject line.

The new, additional, UPS subject line for a package out for delivery that you can view the status on a live map, "UPS Update: Follow Your Delivery on a Live Map".

**Comment by codypet** [comment]
FEDEX is also using "Your package is on its way" when something headed to your house, but not being delivered on that day.  Seems like that would fall under in transit.  I couldn't tell in sensor.py where that should go.

**Comment by moralmunky** [comment]
Yes, this would be added to the class FEDEX_Delivering(Entity)
