### ISSUE TITLE
[Feature Request] Add calendar entities

### ISSUE THREAD

**Issue by stephenjamieson** [moralmunky/Home-Assistant-Mail-And-Packages#503]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Add calendar entities so the [calendar card](https://www.home-assistant.io/lovelace/calendar/) can be utilized

**Describe alternatives you've considered**

**Additional context**

**Comment by firstof9** [comment]
What are you looking to get added?
The integration only tracks the current day's mail/packages.
