### ISSUE TITLE
ISSUE: The camera entities do not support requesting width and height

### ISSUE THREAD

**Issue by yankeejohnboy** [moralmunky/Home-Assistant-Mail-And-Packages#511]
**Describe the bug**
"The camera entity camera.mail_usps_camera does not support requesting width and height, please open an issue with the integration author
The camera entity camera.mail_amazon_delivery_camera does not support requesting width and height, please open an issue with the integration author"

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: RPi4
 - Home Assistant version: 2021.9.5
 - Hassio 
 - Component version: 0.3.3-b15

**Logs**
Logger: homeassistant.components.camera
Source: components/camera/__init__.py:465
Integration: Camera (documentation, issues)
First occurred: 1:41:48 PM (2 occurrences)
Last logged: 1:41:48 PM

The camera entity camera.mail_usps_camera does not support requesting width and height, please open an issue with the integration author
The camera entity camera.mail_amazon_delivery_camera does not support requesting width and height, please open an issue with the integration author

**Comment by firstof9** [comment]
Should be resolved in b16.

**Comment by yankeejohnboy** [comment]
> 
> 
> Should be resolved in b16.

Still getting the same error in b16 unfortunately :-(

**Comment by firstof9** [comment]
Sorry wrong branch on that release, b17 should be proper.

**Comment by yankeejohnboy** [comment]
No more error messages after updating to b17, thanks!
