### ISSUE TITLE
Can't Get it to Work with GMail

### ISSUE THREAD

**Issue by gdreelin** [moralmunky/Home-Assistant-Mail-And-Packages#52]
I got to the integration portion after doing the install from HACS. I put in the Gmail POP server host name, username, pass but it could not connect to that pop.gmail.com. Does this not work with that? I been wanting this to work since most of the other solutions are so so.

**Comment by firstof9** [comment]
You cannot use POP for this use IMAP.
Server: imap.gmail.com

**Comment by gdreelin** [comment]
Ok I tried that but it would not connect either (checked to make sure IMAP was enable too) but it would not. So created an APP Password since I am using 2FA on my GMail but it still would not connect. Keep getting "Unable to connect or login to the mail server. Please check the log for details."

Logs don't show anything that stands out either.

**Comment by firstof9** [comment]
So just to verify you have the following set:
Server: imap.gmail.com
Port: 995
Username: username@gmail.com
Password: YourAppPassword
Folder: Inbox
Gif Duration: 5
Image Path: <the default>

Correct?

**Comment by gdreelin** [comment]
Yes on all and path at /config/www/mail_and_packages.

**Comment by firstof9** [comment]
In Gmail under Forwarding POP/IMAP does it say ```Status: IMAP is enabled``` ?

**Comment by gdreelin** [comment]
Yes

**Comment by firstof9** [comment]
Should be working then.

**Comment by gdreelin** [comment]
I thought maybe it was because POP was enabled too but no luck there... hum well I will keep tinkering until I get it to work. Thanks

I am getting the below log information. I am wondering if there is a conflict with another IMAP in HA.

2020-02-27 22:54:13 ERROR (SyncWorker_0) [custom_components.ups.sensor] Could not connect to UPS My Choice account
2020-02-27 22:54:43 WARNING (MainThread) [homeassistant.components.sensor] Platform imap not ready yet. Retrying in 180 seconds.
2020-02-27 22:57:44 WARNING (MainThread) [homeassistant.components.sensor] Platform imap not ready yet. Retrying in 180 seconds.
2020-02-27 23:00:45 WARNING (MainThread) [homeassistant.components.sensor] Platform imap not ready yet. Retrying in 180 seconds.

**Comment by ikrowni** [comment]
im running into the exact same issue

**Comment by firstof9** [comment]
> 2020-02-27 22:54:13 ERROR (SyncWorker_0) [custom_components.ups.sensor] Could not connect to UPS My Choice account
> 2020-02-27 22:54:43 WARNING (MainThread) [homeassistant.components.sensor] Platform imap not ready yet. Retrying in 180 seconds.
> 2020-02-27 22:57:44 WARNING (MainThread) [homeassistant.components.sensor] Platform imap not ready yet. Retrying in 180 seconds.
> 2020-02-27 23:00:45 WARNING (MainThread) [homeassistant.components.sensor] Platform imap not ready yet. Retrying in 180 seconds.

This isn't the Mail_and_Packages component. Check all your integrations.

**Comment by gdreelin** [comment]
Found the solution!!! Ok if another integration is using IMAP it will not work. Once I killed the IMAP for an older application it worked find. There was two conflicting requests and it would not allow for the completion of the setup...  SOLVED!!
