### ISSUE TITLE
ISSUE: MDI Amazon being removed.

### ISSUE THREAD

**Issue by navet** [moralmunky/Home-Assistant-Mail-And-Packages#521]
Icon mdi:amazon was removed from MDI, please replace this icon with an other icon in your config, it will be removed in version 2021.12.

**Environment (please complete the following information):**
 - OS: Hassio
 - Type of device: NUC
 - Home Assistant version: core-2021.10.0

**Logs**
Icon mdi:amazon was removed from MDI, please replace this icon with an other icon in your config, it will be removed in version 2021.12.

Not sure if moving to mdi:truck-delivery to align with other delivery services.

**Comment by firstof9** [comment]
> where can I get the complete list of icons in use (default and custom icons) in my HA installation?

No idea, sounds like a great question for the HA forums.

**Comment by JOHLC** [comment]
> estion is: where can I get the complete list of icons in use (default and custom icons) in my HA installati

Check out https://pictogrammers.github.io/@mdi/font/6.2.95/
