### ISSUE TITLE
ISSUE: Sensors become unavailable after updating to beta 20

### ISSUE THREAD

**Issue by bschatzow** [moralmunky/Home-Assistant-Mail-And-Packages#525]
**Describe the bug**
I believe I did not see this bug when beta 20 was first released.  I only saw this on 10/12/21. Maybe related to core-2021.10.4?  Not sure?  

**Environment (please complete the following information):**
 - OS: [e.g. HassOS/Raspbian/CentOS]
 - Type of device: [e.g. RPi3/NUC/Synology]
 - Home Assistant version: [e.g. 0.105.5]
 - Hassio/Docker/Core? 
 - Component version: [e.g. 0.1.2]
RPI4, 4G, supervisor-2021.10.0, Debian GNU/Linux 11 (bullseye)

**Logs**
2021-10-12 20:39:13 ERROR (MainThread) [custom_components.mail_and_packages] Error fetching Mail and Packages (smtp.gmail.com) data: list index out of range
2021-10-12 20:39:13 WARNING (MainThread) [homeassistant.config_entries] Config entry 'smpt.gmail.com' for mail_and_packages integration not ready yet: None; Retrying in background

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.
Uninstalled and reinstall, Tried beta 17 and it worked, updated to 20 and it failed again, went to 19 and it worked, updated to 20 and it failed again.  Went back to 19 and it is working. Staying here for now.

**Comment by firstof9** [comment]
Do you happen to have anything in the "Amazon forwarded email addresses" setting?

**Comment by firstof9** [comment]
I was able to pinpoint down the error with the help of the tests, weird that it wasn't erroring out beforehand.

**Comment by bschatzow** [comment]
22 fixes it. Thanks for the quick fix.
