### ISSUE TITLE
ISSUE: Error updating sensor data: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by brandonjones24** [moralmunky/Home-Assistant-Mail-And-Packages#533]
**Describe the bug**

**Environment (please complete the following information):**
 - OS: [e.g. HassOS/Raspbian/CentOS] Home Assistant OS 6.5
 - Type of device: [e.g. RPi3/NUC/Synology] RPi4
 - Home Assistant version: [e.g. 0.105.5] 2021.10.6
 - Hassio/Docker/Core? HASSIO
 - Component version: [e.g. 0.1.2] core-2021.10.6

**Logs**
Paste your error logs here.

This error originated from a custom integration.

Logger: custom_components.mail_and_packages
Source: custom_components/mail_and_packages/__init__.py:100
Integration: Mail and Packages (documentation, issues)
First occurred: 1:36:03 PM (24 occurrences)
Last logged: 1:45:54 PM

Error updating sensor data: 'NoneType' object has no attribute 'split'

**Screenshots**
![image](https://user-images.githubusercontent.com/6091204/138330647-3d491156-4d80-48f6-8f8a-39cad982da6f.png)

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by brandonjones24** [comment]
I should note I resolved the Connection refused based on the URL being incorrect, that allowed me to them progress to the configuration screen.

**Comment by firstof9** [comment]
Could you try disabling the `Mail USPS Mail` and see if that solves it?

**Comment by brandonjones24** [comment]
No luck with that

Logs
https://pastebin.com/Bgs99STn

![image](https://user-images.githubusercontent.com/6091204/138344021-5d9be42f-ee12-4451-b2e7-338aa7d2fa60.png)

**Comment by brandonjones24** [comment]
As soon as I enable Amazon Delivered, it fails. 

I'm wondering if I should just nuke it and start over? Any guidance on that and best way to accomplish it? I installed via HACS.

**Comment by brandonjones24** [comment]
Yea, as expected...no luck.
