### ISSUE TITLE
New USPS email address. Just changed today.

### ISSUE THREAD

**Issue by boctok** [moralmunky/Home-Assistant-Mail-And-Packages#535]
I noticed that my mail card wasn't updating this morning and checked my email. The Informed Delivery email was present, so I started looking through the logs. I didn't see any errors, but I noticed the entries where it had checked for an email from the USPS. I went back to my email and noticed that they have changed the email address. It used to be **uspsinformeddelivery@informeddelivery.usps.com**, but now it is **uspsinformeddelivery@_email_.informeddelivery.usps.com**. I conducted a search for the address in my inbox and confirmed that the changed address was only for today, so far. I don't know if this is a permanent thing or not.

**Comment by firstof9** [comment]
Fixed in #534
