### ISSUE TITLE
ISSUE: 

### ISSUE THREAD

**Issue by bmf7777** [moralmunky/Home-Assistant-Mail-And-Packages#561]
**Describe the bug**
 package not working after installing the latest version ... all sensors unavailable 

**Environment (please complete the following information):**
 - OS: [e.g. HassOS/Raspbian/CentOS] Ubuntu 
 - Type of device: [e.g. RPi3/NUC/Synology] Intel NUC
 - Home Assistant version: [e.g. 0.105.5]  2021.10.7
 - Hassio/Docker/Core? Core
 - Component version: [e.g. 0.1.2] 0.3.4-b5

**Logs**
 Logger: homeassistant.setup
Source: setup.py:178
First occurred: 6:10:08 AM (1 occurrences)
Last logged: 6:10:08 AM
Setup failed for mail_and_packages: Unable to import component: cannot import name 'ENTITY_CATEGORY_DIAGNOSTIC' from 'homeassistant.const' (/srv/homeassistant_3.8/lib/python3.8/site-packages/homeassistant/const.py)

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by bmf7777** [comment]
rolled back to 3.3-2. works fine

**Comment by firstof9** [comment]
Per the b4 release notes:
`Home Assistant version 2021.11.x or higher required due to utilizing Entity Descriptions`
