### ISSUE TITLE
[ISSUE] Amazon Forwarded Email Address

### ISSUE THREAD

**Issue by firstof9** [moralmunky/Home-Assistant-Mail-And-Packages#568]
### Discussed in https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/discussions/567

<div type='discussions-op-text'>

<sup>Originally posted by **0fxyzSa0vj** November 15, 2021</sup>
Hello,

Having issues with the amazon forwarded email address field.  My email address is in the format abc.def.ghi@gmail.com.  If I enter this into the forwarded email field the intergration seems to fail.  If I remove the periods '.', which google doesn't really care about anyway, and enter abcdefghi@gmail.com the intergration loads fine.  However, when forwarding an email it will show as having come from abc.def.ghi@gmail.com still so doesn't really fix the issue.  Are there any work arounds without having to change my amazon account email?

![image](https://user-images.githubusercontent.com/94152294/141846836-f833e3c5-4751-42fd-a081-71e156cb2546.png)
![image](https://user-images.githubusercontent.com/94152294/141846652-f1383673-171e-4312-a72c-5bbcb8e4417b.png)
</div>

**Comment by firstof9** [comment]
@0fxyzSa0vj let me know how the beta runs for you.

**Comment by 0fxyzSa0vj** [comment]
@firstof9  beta 6 seems to have fixed the email issue!  No errors showing in logs and integration appears to be functioning as advertised.  

I can see in the logs it picked up my amazon delivery emails for a delivery I had today but it isn't displaying the image or any details in the integration, not sure if that's normal behaviour as this is my first time using it and that event is now in the past, but will continue to monitor for future deliveries.  Thanks!

**Comment by firstof9** [comment]
It only shows the current day's deliveries. When you get a amazon delivery the image should appear in the amazon camera entity.
