### ISSUE TITLE
ISSUE: New variant of FedEx pending delivery subject line

### ISSUE THREAD

**Issue by angrycatmeowmeow** [moralmunky/Home-Assistant-Mail-And-Packages#587]
**Describe the bug**
There is a new variant of the FedEx pending delivery subject line

**Environment (please complete the following information):**
 - OS: Home Assistant
 - Type of device: HA Blue
 - Home Assistant version: 2021.11.3
 - Hassio/Docker/Core? 
 - Component version: 0.3.3.2
[Gmail - FedEx Shipment 286548614610_ Your packages are now out for delivery today.pdf](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/files/7636037/Gmail.-.FedEx.Shipment.286548614610_.Your.packages.are.now.out.for.delivery.today.pdf)

**Logs**
n/a

**Screenshots**
![image](https://user-images.githubusercontent.com/67968528/144284149-51f56ebd-9403-44ca-be9e-a257ed97915c.png)

**Additional context**
I see in const.py the FedEx section subject line reads as ` "fedex_delivering": { "email": ["TrackingUpdates@fedex.com", "fedexcanada@fedex.com"], "subject": [ "Delivery scheduled for today", "Your package is scheduled for delivery today", "Your package is now out for delivery",`

but my subject line in my email is:
“FedEx Shipment 1234567890: Your packages are now out for delivery today”

**Comment by firstof9** [comment]
The PDF file won't work it has to be the contents of the email itself.

In gmail click the 3 dots next to the email message and click `Show original`:
![image](https://user-images.githubusercontent.com/1105672/143279680-de404c08-f26c-48ef-b1d2-0e7b65269f61.png)

On the next screen click `Download Original` this will download a .eml file you can attach.
![image](https://user-images.githubusercontent.com/1105672/143279769-f5f4dc50-a027-414b-9be5-5ffcc5ea5426.png)

**Comment by angrycatmeowmeow** [comment]
I can't sanitize the .eml file because it just opens in Outlook. Will a pastebin work?

**Comment by firstof9** [comment]
You can right click it and select `Open with` and open it with notepad or vscode to sanitize it, it's just a text document really.

**Comment by angrycatmeowmeow** [comment]
[FedEx Shipment 286548999999.txt](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/files/7636213/FedEx.Shipment.286548999999.txt)

How's this?

**Comment by firstof9** [comment]
perfect thanks!

**Comment by angrycatmeowmeow** [comment]
Here's the email when the packages are delivere
[FedEx Shipment 286548999999_ Your packages have been delivered.txt](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/files/7636632/FedEx.Shipment.286548999999_.Your.packages.have.been.delivered.txt)
d

**Comment by angrycatmeowmeow** [comment]
Here's the email when the packages are delivered:
[FedEx Shipment 286548999999_ Your packages have been delivered.txt](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/files/7636641/FedEx.Shipment.286548999999_.Your.packages.have.been.delivered.txt)

**Comment by firstof9** [comment]
If you install the beta `0.3.4-b10` this should pickup these types of emails now.
I'll add the delivered one in a few.

**Comment by firstof9** [comment]
`0.3.4-b11` should fix you up now.

**Comment by angrycatmeowmeow** [comment]
I installed b10 and it showed 1 in transit, then I installed b11 and it showed 0 in transit and 1 delivered, so it looks to be working just fine. Thank you!
