### ISSUE TITLE
[Feature Request] GLS

### ISSUE THREAD

**Issue by Tntdruid** [moralmunky/Home-Assistant-Mail-And-Packages#595]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
How hard it it to add support for GLS?

**Describe alternatives you've considered**

**Additional context**

**Comment by Tntdruid** [comment]
https://gls-group.eu/ like DHL etc.

**Comment by firstof9** [comment]
Do they send emails like DHL, UPS, and others?

**Comment by Tntdruid** [comment]
They do send mails like UPS and DHL do.

**Comment by firstof9** [comment]
Do you have any examples we can test against?
