### ISSUE TITLE
Amazon "Arriving early" notification not picked up

### ISSUE THREAD

**Issue by angrycatmeowmeow** [moralmunky/Home-Assistant-Mail-And-Packages#596]
**Describe the bug**
Amazon sent an email saying "Shipped: Now arriving early on Friday, December 3". This isn't picked up by `sensor.amazon_packages` I amended line 85 of const.py to include "arriving:" but it still was not picked up. Last time I was messing with the Amazon portion of the integration and made changes, the Amazon emails for the current day weren't picked up after the change, but the next day everything worked.

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: HA Blue
 - Home Assistant version: 2021.11.3
 - Hassio/Docker/Core? 
 - Component version: 0.3.4-b12

**Logs**
n/a

**Screenshots**
n/a
[Shipped_ Now arriving early on Friday, December 3 (#113-9999999-8459426).txt](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/files/7650987/Shipped_.Now.arriving.early.on.Friday.December.3.113-9999999-8459426.txt)

**Additional context**
line 85 const.py `AMAZON_TIME_PATTERN = "will arrive:,estimated delivery date is:,guaranteed delivery date is:,Arriving:,Arriverà:,arriving:"`

**Comment by firstof9** [comment]
`0.3.4-b131` should resolve this now.

**Comment by angrycatmeowmeow** [comment]
Confirmed, it's picking up the email.
