### ISSUE TITLE
ISSUE: Sensor implements device_state_attributes

### ISSUE THREAD

**Issue by TermiNaderTL** [moralmunky/Home-Assistant-Mail-And-Packages#603]
**Describe the bug**
Home Assistant reports this in the logs.  Can't tell yet if I'm impacted...

**Environment (please complete the following information):**
 - OS: HassOS 7.0
 - Type of device: ODroid
 - Home Assistant version: 2021.12.0
 - Hassio
 - Component version: core-2021.12.0

**Logs**
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 9:37:32 AM (46 occurrences)
Last logged: 9:37:46 AM

Entity sensor.mail_usps_packages (<class 'custom_components.mail_and_packages.sensor.PackagesSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.mail_packages_delivered (<class 'custom_components.mail_and_packages.sensor.PackagesSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.mail_packages_in_transit (<class 'custom_components.mail_and_packages.sensor.PackagesSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.mail_image_system_path (<class 'custom_components.mail_and_packages.sensor.ImagePathSensors'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.mail_image_url (<class 'custom_components.mail_and_packages.sensor.ImagePathSensors'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by firstof9** [comment]
Already fixed in the latest beta.

**Comment by TermiNaderTL** [comment]
Thanks 👍
