### ISSUE TITLE
Error searching emails: SEARCH command error: BAD

### ISSUE THREAD

**Issue by vlad36N** [moralmunky/Home-Assistant-Mail-And-Packages#628]
This error originated from a custom integration.

Logger: custom_components.mail_and_packages.helpers
Source: custom_components/mail_and_packages/helpers.py:518
Integration: Mail and Packages (documentation, issues)
First occurred: 7:30:26 AM (12 occurrences)
Last logged: 7:43:04 AM

Error searching emails: SEARCH command error: BAD [b'Command Error. 11']
Error searching emails: SEARCH command error: BAD [b'Could not parse command']

**Environment (please complete the following information):**
System Health

version: core-2022.2.6
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.9.7
os_name: Linux
os_version: 5.10.92-v8
arch: aarch64
host_os: Home Assistant OS 7.4
update_channel: stable
supervisor_version: supervisor-2022.01.1
docker_version: 20.10.9
board: rpi4-64

**Logs**
This error originated from a custom integration.

Logger: custom_components.mail_and_packages.helpers
Source: custom_components/mail_and_packages/helpers.py:518
Integration: Mail and Packages (documentation, issues)
First occurred: 7:30:26 AM (12 occurrences)
Last logged: 7:43:04 AM

Error searching emails: SEARCH command error: BAD [b'Command Error. 11']
Error searching emails: SEARCH command error: BAD [b'Could not parse command']

**Additional context**
I started after yesterday update to version 0.3.4-b19

**Comment by firstof9** [comment]
Need [debug logs](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Troubleshooting#enable-debugging) to see what the problem is.

**Comment by firstof9** [comment]
What email provider are you using?

**Comment by firstof9** [comment]
Safe to ignore for now unless you're in Poland.

**Comment by vlad36N** [comment]
Hi, just updated to latest version. After restart have following:
This error originated from a custom integration.

Logger: custom_components.mail_and_packages.helpers
Source: custom_components/mail_and_packages/helpers.py:523
Integration: Mail and Packages (documentation, issues)
First occurred: 11:56:02 AM (52 occurrences)
Last logged: 11:56:02 AM

Error searching emails: command: SEARCH => socket error: EOF
Error searching emails: socket error: [Errno 32] Broken pipe
Error searching emails: socket error: [SSL: BAD_LENGTH] bad length (_ssl.c:2483)
Error searching emails: socket error: EOF occurred in violation of protocol (_ssl.c:2483)

**Comment by firstof9** [comment]
Need debug logs for information.

**Comment by vlad36N** [comment]
Sure:
[debug_log_for_custom_components.mail_and_packages.txt](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/files/8062893/debug_log_for_custom_components.mail_and_packages.txt)

**Comment by vlad36N** [comment]
Hi, just updated to latest version. No more errors. Issue can be closed.
Thank you
