### ISSUE TITLE
Issues with Amazon.de and noreply@dhl.de

### ISSUE THREAD

**Issue by Mencode-Maennercode** [moralmunky/Home-Assistant-Mail-And-Packages#633]
Hi,
Integrations works, but it finds not exactly everythink from the german market.
Hassio finds the "Amazon - Delivery Mail" after I added  in cost.py:
AMAZON_DELIVERED_SUBJECT = ["Delivered: Your", "Consegna effettuata:", **"Geliefert:"**]
On was delivered today. Thats correct.
![image](https://user-images.githubusercontent.com/80756739/154552412-b203c2a1-188f-498e-a723-396ac3fb24b9.png)

There are a lot of more packets on the way right now. They are not found.
![Amazon](https://user-images.githubusercontent.com/80756739/154553461-ae24e159-b241-47e6-acc1-44f5a4a69f75.jpg)

The DHL Mail is not found.

![DHL1](https://user-images.githubusercontent.com/80756739/154553493-cd1efd5b-cdae-4f92-a66c-33284cdf97ee.jpg)
![DHL2](https://user-images.githubusercontent.com/80756739/154553503-d926376a-3b72-46a4-8948-5afa5e24a550.jpg)

I also added the Email Subject in cost.py with no succes.

Thanks for your great work!!! :)

Kind regards!

**Comment by firstof9** [comment]
That's because for DHL we're looking for "paket kommt heute" did DHL send you that version of the email?

**Comment by Heidenreich89** [comment]
No.
"Paket kommt heute" means "package will come today".
That Mail where I take a screenshot from means "Estimated delivery" with an estimated delivery date in it.

**Comment by firstof9** [comment]
We're not looking for estimated delivery only that it's coming "today".

**Comment by Heidenreich89** [comment]
Oh ok, how you deal with Amazon.de
Same as DHL?

**Comment by firstof9** [comment]
All shippers are only counted for the "today" count. Amazon's a little different since they use multiple shippers.

**Comment by Heidenreich89** [comment]
Whats about that Issue:
Hassio finds the "Amazon - Delivery Mail" after I added  in cost.py:
AMAZON_DELIVERED_SUBJECT = ["Delivered: Your", "Consegna effettuata:", **"Geliefert:"**]
On was delivered today. Thats correct.
![image](https://user-images.githubusercontent.com/80756739/154552412-b203c2a1-188f-498e-a723-396ac3fb24b9.png)

There are a lot of more packets on the way right now. They are not found.
![Amazon](https://user-images.githubusercontent.com/80756739/154553461-ae24e159-b241-47e6-acc1-44f5a4a69f75.jpg)

**Comment by firstof9** [comment]
We don't parse date ranges. The delivered email we can parse, I'll make a PR to add that.

**Comment by firstof9** [comment]
`0.3.4-b22` should resolve or mitigate this.
