### ISSUE TITLE
ISSUE: This error originated from a custom integration

### ISSUE THREAD

**Issue by akhlghatyan** [moralmunky/Home-Assistant-Mail-And-Packages#635]
**Describe the bug**
This error originated from a custom integration.

Logger: custom_components.mail_and_packages
Source: helpers/update_coordinator.py:193
Integration: Mail and Packages (documentation, issues)
First occurred: 6:58:19 PM (3 occurrences)
Last logged: 7:04:52 PM

Timeout fetching Mail and Packages (imap.mail.yahoo.com) data
**Environment (please complete the following information):**
 - OS: 
 - Type of device: Synology
 - Home Assistant version:  2022.2.9
 - Hassio/Docker/Core? Docker
 - Component version:

**Logs**
Paste your error logs here.

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment]
Increase your `IMAP timeout` in the configuration.

**Comment by akhlghatyan** [comment]
Hi
I will change it
You did a great job
Thanks

**Comment by akhlghatyan** [comment]
Ok, thanks.
