### ISSUE TITLE
Add table with links to packages (add to existing card or new card)

### ISSUE THREAD

**Issue by AngellusMortis** [moralmunky/Home-Assistant-Mail-And-Packages#640]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Tracking numbers (USPS, UPS and FedEx) and order numbers (Amazon) are already listed as attributes on the sensors. It would be great if you could construct a table or list to list out all of the packages with links to open the tracking information within the card. 

**Describe alternatives you've considered**
Could do the same with a template + markdown card, but it would be great if it out was out of the box:

```
| Carrier | Tracking Number | Tracking Link |
|--------------|-----------|------------|
{% for trk_number in state_arr('sensor.mail_usps_delivering', 'tracking_#') %}
| USPS | {{ trk_number }} | [Open](https://tools.usps.com/go/TrackConfirmAction?tLabels={{ trk_number }})
{% endfor %}
{% for trk_number in state_arr('sensor.mail_fedex_delivering', 'tracking_#') %}
| FedEx | {{ trk_number }} | [Open](https://www.fedex.com/fedextrack/?trknbr={{ trk_number }})
{% endfor %}
```

| Carrier | Tracking Number | Tracking Link |
|--------------|-----------|------------|
| USPS | 9400100000000000000000 | [Open](https://tools.usps.com/go/TrackConfirmAction?tLabels=9400100000000000000000)
| FedEx | XXXXXXXX | [Open](https://www.fedex.com/fedextrack/?trknbr=XXXXXXXX) |

**Additional context**
N/A

**Comment by moralmunky** [comment]
Transferred the issue here. The card example would be good for the WIKI. I don't currently have plans to build a table in the card.

**Comment by firstof9** [comment]
This can be accomplished already via the [Flex Table Custom Card](https://github.com/custom-cards/flex-table-card)
