### ISSUE TITLE
<minor> ISSUE: Clicking configure>submit>submit without changes throws an error

### ISSUE THREAD

**Issue by leecig** [moralmunky/Home-Assistant-Mail-And-Packages#646]
**Describe the bug**
Clicking configure>submit>submit without changes throws an error unless you edit or retype the 'Amazon forwarded email address' field. (Also just noticed forwarded is misspelled XD, bonus bug report lol)

**Environment (please complete the following information):**
 - OS: HassOS running on 
 - Type of device: ESXi 7.0 vm
 - Home Assistant version: 2022.3.1
 - Hassio/Docker/Core? Home Assistant OS
 - Component version: [e.g. 0.1.2]
 -    core-2022.3.1
 -    supervisor-2022.03.5
 -    Home Assistant OS 7.4
**Logs**
Not sure where to find :/

**Screenshots**
![image](https://user-images.githubusercontent.com/29929844/159133570-dfddc785-ba72-4143-977e-8a44643fca54.png)

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment]
This happens due to the limitations of the Home Assistant configuration UI, at the present you can added `""` to the amazon forwards and it will resolve this.
