### ISSUE TITLE
ISSUE: 

### ISSUE THREAD

**Issue by jrsecor** [moralmunky/Home-Assistant-Mail-And-Packages#652]
**Describe the bug**
Latest versions either don't poll inbox correctly or don't poll at all (gmail)

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: UnRaid VM
 - Home Assistant version: core-2022.4.1
 - core
 - Component version: 0.3.3-1 and 0.3.3-2

**Logs**
Paste your error logs here.

**Screenshots**
For 0.3.3-1 the following shows my inbox after marking all as unread - note that in 0.3.3-2, it wasn't checking every 5 minutes as it is set to do so none of them got marked as read/info pulled

![image](https://user-images.githubusercontent.com/8600057/162489766-ed6fc637-b7ec-4813-b480-3807533db935.png)

**Additional context**
It appears with the two latest versions I can pull in HACS that FedEx packages are not grabbed (0.3.3-1) or emails are not accessed at all on the 5 minute interval that is set (0.3.3-2). I updated this morning (I don't recall from what version) and since then, the integration is not working as expected.

**Comment by firstof9** [comment]
Try the latest beta.

**Comment by jrsecor** [comment]
Appears to work in the latest beta. I had tried rolling back and a few
other things but the newest beta was the only fix.
