### ISSUE TITLE
ISSUE: Log filled with "No mail found" messages

### ISSUE THREAD

**Issue by kbickar** [moralmunky/Home-Assistant-Mail-And-Packages#654]
**Describe the bug**
The integration is filling the logs with the message posted every 10 minutes:
`[custom_components.mail_and_packages.helpers] No mail found.` or 
`[custom_components.mail_and_packages.helpers] Mail image generated.`

Suggest changing the log level to DEBUG, integrations should not be logging on regular updates

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Type of device: NUC
 - Home Assistant version: 2022.4.0
 - Docker
 - Component version: 0.3.3-2

**Logs**
2022-04-12 12:03:13 INFO (SyncWorker_6) [custom_components.mail_and_packages.helpers] No mail found.
2022-04-12 12:13:19 INFO (SyncWorker_7) [custom_components.mail_and_packages.helpers] No mail found.
2022-04-12 12:23:24 INFO (SyncWorker_6) [custom_components.mail_and_packages.helpers] No mail found.

**Comment by firstof9** [comment]
You have your default logging set to info level? Kinda chatty but if that's your bag, here's an easy fix:

```yaml
logger:
  default: info
  logs:
    custom_components.mail_and_packages: error
```
