### ISSUE TITLE
Automatically hide the camera.mail_amazon_delivery_camera image from the dashboard card when sensor.mail_amazon_packages is 0

### ISSUE THREAD

**Issue by benwicks** [moralmunky/Home-Assistant-Mail-And-Packages#660]
**Is your feature request related to a problem? Please describe.**
I would prefer if the dashboard card would not show the `camera.mail_amazon_delivery_camera` image when `sensor.mail_amazon_packages` is 0.

**Describe the solution you'd like**
I am trying to create a custom card in the UI for what I want, but I'm new to this and I don't know where to find where this custom card is defined. If it's easier, could you point me to where the dashboard card is defined so I can reference it?

**Describe alternatives you've considered**
I already created a virtual binary sensor to completely hide the card when all of the sensors are reporting zero but it would be nice to have more granular control in the case when there are no Amazon packages coming.

**Comment by firstof9** [comment]
This should be in the card repo: https://github.com/moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card
