### ISSUE TITLE
ISSUE: Order displayed as multiple packages on delivery

### ISSUE THREAD

**Issue by combative-american** [moralmunky/Home-Assistant-Mail-And-Packages#664]
An Amazon order was divided into two packages. Both packages were under the same order ID (XXX-XXXXXXX-XXXX253). sensor.mail_amazon_packages correctly expected 1 order. The entity sensor.mail_amazon_packages_delivered showed two deliveries. However, there is still only one order number listed (XXX-XXXXXXX-XXXX253). I expected that regardless of how they were packaged, both sensor states would be 1.

 - Home Assistant version: 2022.5.3
 - Hassio/Docker/Core? 2022.5.1
 - Component version: 0.3.4-b24

I used a template to total all of the expected packages minus the delivered packages. So I ended up seeing Expected: -1, Delivered: 2. I suppose it is a weird occurrence because Amazon did send two emails that contained the same photo of the delivery.

**Comment by firstof9** [comment]
Unfortunately not much can be done about this.
Amazon is the odd ball.
