### ISSUE TITLE
ISSUE: Amazon Packages state increasing the day after delivery

### ISSUE THREAD

**Issue by GitHubGoody** [moralmunky/Home-Assistant-Mail-And-Packages#665]
**Describe the bug**
My Amazon Packages state increased this morning for a package that was delivered yesterday.

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: RPi3
 - Home Assistant version: 2022.5.4
 - Hassio/Docker/Core? Core
 - Component version:
![image](https://user-images.githubusercontent.com/46235745/168796322-d6d179eb-5d5d-477d-821c-0f412ccbe308.jpeg)

**Logs**
N/A

**Screenshots**
Today is Tuesday...

![image](https://user-images.githubusercontent.com/46235745/168796388-e13ea4c6-5121-453d-b047-b972c2e72c70.jpeg)

**Additional context**
N/A

**Comment by firstof9** [comment]
I don't see anything in there regarding the amazon sensor.

**Comment by GitHubGoody** [comment]
It definitely increased by 1 this morning. What else can I provide?

![image](https://user-images.githubusercontent.com/46235745/168886991-f86a52e8-0400-4af4-bbc5-070f0ae781f3.png)

**Comment by firstof9** [comment]
I'd need the full debug output from mail and packages to see what's going on.

**Comment by GitHubGoody** [comment]
I tried to filter in the top-right by Mail and Packages, but it's not an option. What do I need to do to generate that full debug output after configuring the logging level to debug?

Which of the two Amazon e-mails above (one from Sunday and one from Monday) do you think is causing the count to jump on Tuesday?

**Comment by firstof9** [comment]
The email from Sunday likely has the original delivery date.

**Comment by GitHubGoody** [comment]
That's correct (you can see it in the tracking line at the bottom of the screenshot). I thought only e-mails received on the same date were used? Does Amazon work differently than the rest?

**Comment by firstof9** [comment]
> Does Amazon work differently than the rest?

Yes
