### ISSUE TITLE
[Feature Request] Display mail_updated time in local time

### ISSUE THREAD

**Issue by kaizersoje** [moralmunky/Home-Assistant-Mail-And-Packages#667]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Currently the `sensor.mail_updated` displays the time in UTC. Is it possible to have the time displayed in the local timezone instead?
![image](https://user-images.githubusercontent.com/54566217/169421348-98fcc40d-d460-4cfc-bec7-965a2d002646.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by firstof9** [comment]
No this is how the timestamps in Home Assistant work.

What are you attempting to do that this is causing an issue?

**Comment by kaizersoje** [comment]
I know that is how it stores timestamps.
However, it is displayed in UTC in the frontend as well.

![image](https://user-images.githubusercontent.com/54566217/169434917-026cc2f4-b159-457a-99b5-42871726342e.png)

**Comment by firstof9** [comment]
This is how it displays in a entity card:
![image](https://user-images.githubusercontent.com/1105672/169535206-99e47daf-0e73-4c6d-ac73-fc56423dc234.png)

Is that's the Mail and Packages card you're using?

**Comment by kaizersoje** [comment]
Apologies. I didn't realise I was not using the Mail and Packages card. All good now.
