### ISSUE TITLE
ISSUE: M&P timing out/sensors unavailable frequently

### ISSUE THREAD

**Issue by angrycatmeowmeow** [moralmunky/Home-Assistant-Mail-And-Packages#668]
**Describe the bug**
All sensors show "unavailable" frequently

**Environment (please complete the following information):**
 - OS: [e.g. HassOS/Raspbian/CentOS] HassOS
 - Type of device: [e.g. RPi3/NUC/Synology] ODROID N2+
 - Home Assistant version: [e.g. 0.105.5] 2022/5.0
 - Hassio/Docker/Core? 
 - Component version: [e.g. 0.1.2] 0.3.4 b23

**Logs**
This error originated from a custom integration.

Logger: custom_components.mail_and_packages
Source: helpers/update_coordinator.py:197
Integration: Mail and Packages (documentation, issues)
First occurred: May 19, 2022, 10:57:34 (14 occurrences)
Last logged: 11:09:19

Timeout fetching Mail and Packages (imap.gmail.com) data

This error originated from a custom integration.

Logger: custom_components.mail_and_packages.camera
Source: custom_components/mail_and_packages/camera.py:127
Integration: Mail and Packages (documentation, issues)
First occurred: May 19, 2022, 16:04:43 (2 occurrences)
Last logged: May 19, 2022, 20:26:14

Could not read camera Mail USPS Camera image from file: /config/custom_components/mail_and_packages/images/f8e3f6bb-b330-4016-b8a4-4f67863cfab5.gif

This error originated from a custom integration.

Logger: custom_components.mail_and_packages.camera
Source: custom_components/mail_and_packages/camera.py:137
Integration: Mail and Packages (documentation, issues)
First occurred: May 19, 2022, 11:15:13 (1076 occurrences)
Last logged: 11:20:16

Update to update camera image. Unavailable.

**Screenshots**
![image](https://user-images.githubusercontent.com/67968528/169570531-97ba1f70-34cf-4fb3-9eec-0508849d86c3.png).

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment]
> Timeout fetching Mail and Packages (imap.gmail.com) data

Increase your timeout limit in step 2 of the configuration.

**Comment by angrycatmeowmeow** [comment]
set to 120s. so far so good. thank you.
