### ISSUE TITLE
New email address for USPS informed delivery

### ISSUE THREAD

**Issue by m-milani** [moralmunky/Home-Assistant-Mail-And-Packages#669]
This week, my USPS mail notification stopped working.   I noticed the following new email needs to be added to the array of emails for USPS - USPSInformeddelivery@email.informeddelivery.usps.com in const.py

**Comment by firstof9** [comment]
Already exists in const.py.

https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/blob/dc061f75ce7a478df69b8a589252b53019c60273/custom_components/mail_and_packages/const.py#L147

**Comment by SK360** [comment]
> This week, my USPS mail notification stopped working. I noticed the following new email needs to be added to the array of emails for USPS - [USPSInformeddelivery@email.informeddelivery.usps.com](mailto:USPSInformeddelivery@email.informeddelivery.usps.com) in const.py

Mine stopped working too a few days ago.  Realized that it didn’t actually update to 0.3.4-2 and was on 0.3.4-1 even though it said -2 was the latest release but showed no update.  I reinstalled in HACS picking -2 and my informed delivery works again.

**Comment by firstof9** [comment]
Yes github has done some weird things in the past month, not sure what's going on.
