### ISSUE TITLE
ISSUE: UPS delivery confirmation includes two different tracked packages

### ISSUE THREAD

**Issue by moralmunky** [moralmunky/Home-Assistant-Mail-And-Packages#67]
**Describe the bug**
I wanted to document this before I forgot. I received day of in transit notifications separately for two tracked UPS packages, however, only one delivery notification was sent and the body included both UPS packages for that day.

**Environment (please complete the following information):**
NA
**Logs**
NA

**Screenshots**
![Screen Shot 2020-03-18 at 12 40 25 PM](https://user-images.githubusercontent.com/19318945/76985277-5c7b4180-6916-11ea-9335-58b0d88790ae.png)

**Additional context**

**Comment by firstof9** [comment]
I guess we could count the tracking numbers and use that number as the "delivered" sensor number.

**Comment by firstof9** [comment]
I've resolved this in 0.2.2-b4 still needs more testing but it worked for me on a single UPS email with multiple tracking numbers.

**Comment by firstof9** [comment]
Considering this working.
