### ISSUE TITLE
ISSUE: UTF-8 not supported: Server does not support ENABLE

### ISSUE THREAD

**Issue by bschatzow** [moralmunky/Home-Assistant-Mail-And-Packages#672]
**Describe the bug**
Not sure if this is from the new Beta of HA or the new Beta of Mail and Packages.
Just started seeing this error in the logs
**Environment (please complete the following information):**
 - OS: [e.g. HassOS/Raspbian/CentOS]
 -HAOS 2020-6 Beta 1
 - Type of device: [e.g. RPi3/NUC/Synology]
 RPI4
 - Home Assistant version: [e.g. 0.105.5]
 - Hassio/Docker/Core? 
 - Component version: [e.g. 0.1.2]

**Logs**
This error originated from a custom integration.

Logger: custom_components.mail_and_packages.helpers
Source: custom_components/mail_and_packages/helpers.py:544
Integration: Mail and Packages (documentation, issues)
First occurred: May 25, 2022, 7:46:40 PM (246 occurrences)
Last logged: 6:10:14 AM

UTF-8 not supported: Server does not support ENABLE

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment]
Safe to ignore, it's just a warning.

**Comment by firstof9** [comment]
Likely change it to a debug message next beta.

**Comment by firstof9** [comment]
This has been updated in `0.3.5-b1` to a debug message.
