### ISSUE TITLE
ISSUE: Not finding Daily Digest email from USPS, new from address?

### ISSUE THREAD

**Issue by stogs** [moralmunky/Home-Assistant-Mail-And-Packages#674]
**Describe the bug**
Not finding Daily Digest email from USPS 

**Environment (please complete the following information):**
 HassOS
 - Type of device: 
 Odroid N2
 - Home Assistant version: 2022.6.0b1
 
 - Component version: [e.g. 0.1.2]
0.3.4-2
**Logs**
Paste your error logs here.

Looks like an additional from address may have been added by the USPS, email.informeddelivery.usps.com

**Comment by firstof9** [comment]
This was already fixed, double check your version.

**Comment by stogs** [comment]
My bad.  Sorry about that.  Thought i was current.
