### ISSUE TITLE
[Feature Request] Binary sensor or camera state attribute for "image available"

### ISSUE THREAD

**Issue by kariudo** [moralmunky/Home-Assistant-Mail-And-Packages#682]
**Is your feature request related to a problem? Please describe.**
There is no convenient way that I can find to tell if the image yielded to the `camera` is is the `mail_none` image or not for either mail or packages(amazon).

My specific scenario is when there are packages marked as delivered, but there is no specific image available. Currently I can only decide if the mail image should be shown or not based on if packages have been delivered, but I never want to see the default `mail_none` image and instead want to be able to have my UI react conditionally to "there are packages, but we have no image".

**Describe the solution you'd like**
I would like the ability to conditionally check if the current image being supplied to the camera entity is the default mailnone/nopackages image.

**Describe alternatives you've considered**
I considered modifying the whole execution stack down to https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/blob/dc061f75ce7a478df69b8a589252b53019c60273/custom_components/mail_and_packages/helpers.py#L1035 in order to pass back up when an image was found for a delivery or not. However, I didn't think it would be a good approach if there is something more viable.

**Additional context**
N/A

**Comment by firstof9** [comment]
I'll see what I can whip up, unless you'd like to give it a shot.

**Comment by firstof9** [comment]
Give the latest beta a try once you see it on HACS.

**Comment by firstof9** [comment]
Implemented in latest beta.

**Comment by kariudo** [comment]
Great work @firstof9 , thank you! I would have implemented it myself on your suggestion, but just didn't find the time, you know how it is. I can confirm that the new sensors are present, bonus points to you for covering the regular mail sensor as well. I updated my conditionals last night with the new sensors and we'll see what happens when the next package arrives (probably today hah). But I am going to assume it's working since the USPS one seems to show the correct boolean state from regular mail. Cheers 🍺

**Comment by kariudo** [comment]
I think this binary sensor was broken by a recent change? It no longer appears to function. I assume there was a regression from another change, but I have not had a chance to look at the code/commits.
