### ISSUE TITLE
ISSUE: IMAP Authentication Fails

### ISSUE THREAD

**Issue by benblb** [moralmunky/Home-Assistant-Mail-And-Packages#683]
**Describe the bug**
IMAP authentication failure. I had not edited the configuration, and I confirmed that I'm using:

- imap.gmail.com
- Port: 993
- Correct email
- Correct password (successfully used to login in Chrome)

**Environment (please complete the following information):**
 - OS: Debian 11
 - Type of device: Pretty much a NUC - Intel i5 Chromebox converted to Linux box. 
 - Home Assistant version: 2022.6.5
 - Hassio/Docker/Core? Core. Also supervisor-2022.05.3
 - Component version: Mail & Packages 0.3.4-2

**Logs**
Logger: custom_components.mail_and_packages.helpers
Source: custom_components/mail_and_packages/helpers.py:434 
Integration: Mail and Packages ([documentation](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages), [issues](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues)) 
First occurred: June 13, 2022, 11:14:04 PM (122 occurrences) 
Last logged: 9:19:17 AM

Error logging into IMAP Server: b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'

**Screenshots**

**Additional context**
Error occurred well before it says in log. I rebooted + updated some things.

**Comment by firstof9** [comment]
You need to follow the [GMail directions from the wiki](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Configuration-and-Email-Settings#gmail).

**Comment by benblb** [comment]
@firstof9 sorry if I wasn't clear - this integration was working well for 6+ months and suddenly stopped. I am using an app password already.

**Comment by firstof9** [comment]
Did you also follow the other steps?

![image](https://user-images.githubusercontent.com/1105672/173658101-4ad9a114-796d-46c8-9143-efdeb1357cfa.png)

**Comment by benblb** [comment]
App passwords did it, thank you. Google changed their settings and locked me out of the way I was authenticating.
