### ISSUE TITLE
Configuration Error - Amazon Forwarded Email Addresses

### ISSUE THREAD

**Issue by socaljr53** [moralmunky/Home-Assistant-Mail-And-Packages#689]
After completing step 1 of the configuration, the second screenContinue to receive the following error during the configuration process.

![image](https://user-images.githubusercontent.com/78208603/176045304-2da0b9aa-734a-4a62-959c-65456f08b082.png)

User input malformed: expected str for dictionary value @ data['amazon_fwds']

**Comment by firstof9** [comment]
Change the amazon forwarded email addresses to: `""`

**Comment by emeybee** [comment]
Hi, I actually need to enter Amazon forwarding addresses, two of them. The instructions just say to separate them with a comma. I have tried with the quotes around the whole thing, the quotes around each address, and no quotes. No matter what I do I am getting the same error this person got.

**Comment by coharness** [comment]
@emeybee I don't use a forwarding address but the empty double quotes wouldn't work for me. I had to use single quotes instead. Maybe that's what you need?

**Comment by firstof9** [comment]
Try this format: `'your@email.address.one, your2nd@email.address.one'`

**Comment by coharness** [comment]
Looks like I'm stuck with this error now, too. I don't use forwarded addresses for Amazon.

**Comment by firstof9** [comment]
@coharness if you input `''` thats two `'`s does it let you pass?

**Comment by coharness** [comment]
No, not anymore. I was able to just the one time when I mentioned in my earlier comment.

**Comment by firstof9** [comment]
I'll see about jery rigging something for the config flow.

**Comment by emeybee** [comment]
> Try this format: `'your@email.address.one, your2nd@email.address.one'`

This seems to have worked, I guess it was the one I hadn't tried. Thank you.

**Comment by firstof9** [comment]
@emeybee thanks for the confirmation.

**Comment by awshifts** [comment]
Same issues for me - been going on for about a week for me now.   I have been using it without issues for some time, but now my two email addresses that I use are the same error as the original post.  I have uninstalled, tried several of the betas, as well as trying the "" '' methods but no luck at all.

**Comment by firstof9** [comment]
> now my two email addresses that I use are the same error as the original post.

Have you tried the format `'your@email.address.one, your2nd@email.address.one'` ?

**Comment by awshifts** [comment]
> 

Yup same result.
![Snag_2d93cb81](https://user-images.githubusercontent.com/34609736/179572957-f2212add-0b0b-473b-8480-fa9ca54da372.png)

**Comment by firstof9** [comment]
You don't need those for gmail accounts, can you try just `""` or `''`

**Comment by awshifts** [comment]
Will do that's what I had before.  will let you know.

**Comment by awshifts** [comment]
same issues either way.  

![Snag_2e057519](https://user-images.githubusercontent.com/34609736/179606893-179e2e0e-fc56-450d-81cb-b740b8b21322.png)
![Snag_2e0580e1](https://user-images.githubusercontent.com/34609736/179606900-16e25e3e-b5eb-495f-9247-5d7bcba7886a.png)

**Comment by firstof9** [comment]
Your quotes look weird in this image, almost like `'""'`

It should look similar to this:
![image](https://user-images.githubusercontent.com/1105672/179612738-f4501641-99f4-4d01-b402-a611fe8fa9a1.png)

This is just two single quotes: `''`

**Comment by awshifts** [comment]
The same thing regardless.  I have deleted it completely and will try again. Just wanted to update you.
![Snag_320f8188](https://user-images.githubusercontent.com/34609736/179780161-22359dc6-a31d-454b-b4e1-8bebd26b63d0.png)

**Comment by awshifts** [comment]
Latest Beta 0.3.5-b4 correct? If that's the one it's the one I am using.

**Comment by firstof9** [comment]
Try leaving it blank as well. I think that only works in initial setup tho.

**Comment by firstof9** [comment]
I'll see if I can make a workaround for the config flow for this.

**Comment by awshifts** [comment]
Was just typing back to you. After I confirmed the regular mail was working I did the following. 

I deleted the repository and went through the setup again. Was having the same issue.  So I did it a third time, this time I did not select any Amazon Sensors. Config went fine.  I went back in, chose Amazon, used '', and saved it.  Now amazon works :)

Just wanted you to be aware, not sure if something in the flow, or config, but after doing that it works.

**Comment by firstof9** [comment]
Thanks for the info.

**Comment by awshifts** [comment]
> Thanks for the info.

apparently, I lied it started again.

**Comment by firstof9** [comment]
This new PR should help.
I'll put up another beta once I am able to test the code locally.

**Comment by firstof9** [comment]
`0.3.5-b5` should pop up shortly with this new fix in place. Instead of using `""` or `''` just enter `(none)`.

**Comment by niemyjski** [comment]
Just ran into this as well

**Comment by sanghviharshit** [comment]
Me too.

**Comment by christophermichaelshaw** [comment]
(none) works for me -- but would like to confirm that the feature still works.
