### ISSUE TITLE
Feature Request: Ability to adjust frequency of calls to email account

### ISSUE THREAD

**Issue by guedeaux** [moralmunky/Home-Assistant-Mail-And-Packages#69]
I request a way to adjust the frequency with which the component checks the email account.

**Comment by moralmunky** [comment]
Please try this beta release for scanning interval configuration

https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/releases/tag/0.1.3-b7

**Comment by guedeaux** [comment]
Worked like a charm. Set it to 10 minutes and it did so.
