### ISSUE TITLE
[Feature Request] New Gmail Support

### ISSUE THREAD

**Issue by LordNex** [moralmunky/Home-Assistant-Mail-And-Packages#690]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I cannot use this service with my gmail account anymore. Since May of 2022 google has shut off thier app passwords feature on many accounts

**Describe the solution you'd like**
A clear and concise description of what you want to happen.  Be able to use gmail account for this service 

**Describe alternatives you've considered**

Trying to move all my mail notifications to a different email provider. Would take a while because the change requires verification of address and also I would have to create a new email address

**Additional context**

**Comment by firstof9** [comment]
App passwords are working fine here.
Make sure you have 2FA enabled.

**Comment by firstof9** [comment]
You must enable 2FA in order to use app passwords.

**Comment by LordNex** [comment]
![image](https://user-images.githubusercontent.com/9270948/176941795-da43c7b3-95fd-47e1-977e-a70600e0908f.jpeg)


Here's how it's set. It's the same as it has always been. I used this for the last year and haven't had any issues until now. I've verified my user Id and pass is correct. 

As far as 2fa being needed for app passwords. When did that change? I've been using it this way for a while and haven't had any issues until May. I have a feeling that even if I enable 2fa it's not going to resolve the issue. Not to mention, how am I going to verify a 2fa every time this integration needs to access the mailbox?

**Comment by LordNex** [comment]
Ok I enabled that and it worked but I ran into another issue

When I get to the end and it wants the location of the image file and has the default location of 

custom_components/mail_and_packages/images/mail_none.gif

I get

![image](https://user-images.githubusercontent.com/9270948/176943883-fcee8ded-5f8d-4019-8643-f3f02a5aa9df.jpeg)

**Comment by LordNex** [comment]
Got it. Had to take the "images" out of the directory path. Might want to check whatever template that's filling that out as there is no "images" folder under that path. The mail_none.gif is in the root folder of the "mail and packages" custom component folder. 

Other than that it's working now. But you may want to update your help file to include those things just to keep others from opening tickets. 

Thanks again for the help and the kick ass software 👍

**Comment by LordNex** [comment]
Ok new error. Want a new ticket?

This error originated from a custom integration.

Logger: custom_components.mail_and_packages.helpers
Source: custom_components/mail_and_packages/helpers.py:552 
Integration: Mail and Packages (documentation, issues) 
First occurred: 12:41:15 PM (31 occurrences) 
Last logged: 12:46:30 PM

Error searching emails: SEARCH command error: BAD [b'Could not parse command']

**Comment by LordNex** [comment]
Had to change inbox folders to inbox. I had it set for All Mail and received the above error. 

But I'm up and running now. Go ahead and close if you want.

**Comment by LordNex** [comment]
Spoke too soon

This error originated from a custom integration.

Logger: custom_components.mail_and_packages
Source: helpers/update_coordinator.py:223 
Integration: Mail and Packages (documentation, issues) 
First occurred: 1:04:21 PM (7 occurrences) 
Last logged: 1:06:04 PM

Error fetching Mail and Packages (imap.Gmail.com) data: 'count'

**Comment by LordNex** [comment]
This error originated from a custom integration.

Logger: custom_components.mail_and_packages.helpers
Source: custom_components/mail_and_packages/helpers.py:552 
Integration: Mail and Packages 
First occurred: 1:04:21 PM (38 occurrences) 
Last logged: 1:06:04 PM

Error searching emails: 'ascii' codec can't encode character '\u201c' in position 7: ordinal not in range(128)
Error searching emails: 'ascii' codec can't encode character '\u201c' in position 20: ordinal not in range(128)

**Comment by firstof9** [comment]
Use the latest beta

**Comment by LordNex** [comment]
I finally got it working. Thanks guys. Close it it you want or use it for whatever purpose you want.
