### ISSUE TITLE
ISSUE: No "Allow external image use" option

### ISSUE THREAD

**Issue by emeybee** [moralmunky/Home-Assistant-Mail-And-Packages#691]
I am trying to add the GIF of mail to my dashboard. I am following the wiki: https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/USPS-Informed-Delivery-Image

I use an external URL for my dashboard, so I need to follow Option 1. It says I need to check the "Allow external image use" box. I do not have that option in my configuration. I only have:

- Create mp4 from images
- Create image for notification apps
- Use custom 'no image' image?

As is, sensor.mail_image_url is not populating and sensor.mail_image_system_path populates but the url just redirects to the main Home Assistant page. I do see the image in my files.

**Comment by firstof9** [comment]
Yes, the wiki needs updating.

Utilize the camera entities that are created.
