### ISSUE TITLE
Error connecting into IMAP Server: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by TermiNaderTL** [moralmunky/Home-Assistant-Mail-And-Packages#692]
After upgrading HA to 2022.7, I get a timeout when trying to login to my mail server.

I tried turning on the detailed logging, but no additional information is provided.

I also tried uninstalling from Integrations, reinstalling in HACS and then re-adding to Integrations but I get the same error.

Is this related to the HA upgrade which included a Python 3.10 upgrade?

From HA Error Log:
Source: custom_components/mail_and_packages/helpers.py:116
Error connecting into IMAP Server: [Errno 104] Connection reset by peer

<img width="435" alt="image" src="https://user-images.githubusercontent.com/71670149/178094185-ace2ef32-099a-4f2d-ad6f-3c3752d1b38e.png">

**Comment by firstof9** [comment]
Check your mail server settings.

**Comment by TermiNaderTL** [comment]
Thanks.  They haven't changed and I have been using this great integration for a long time now.  It's through Spectrum internet service as mail.twc.com with port 993 and my login credentials.  I'll see if something changed at Spectrum, but my e-mail app uses the same settings and works fine as usual.

**Comment by firstof9** [comment]
Well there you go, they're using an old cipher, likely TLS1.1 which is unsecure and no longer supported in python 3.10 which the latest versions of HA use.

**Comment by TermiNaderTL** [comment]
Thanks so much.  Spectrum says they are on SSL 2.0 and TLS 1.0 without a clear upgrade path they can share.
