### ISSUE TITLE
ISSUE: Unavailable - timeout

### ISSUE THREAD

**Issue by Ali229** [moralmunky/Home-Assistant-Mail-And-Packages#694]
**Describe the bug**
When I installed this plugin it worked for a while, now without making any changes, everyday I have to restart it because it says mail unavailable connection time out.

**Environment**
- OS: HassOS
- Type of device: RPi3
- Home Assistant version: Home Assistant 2022.7.2
- Hassio
- Component version: not sure? I do install all updates.

**Logs**
Timeout fetching Mail and Packages (imap.gmail.com) data
11:01:23 AM – (ERROR) Mail and Packages (custom integration) - message first occurred at July 9, 2022 at 4:48:45 AM and shows up 10 times

**Additional context**
Changed timeout setting to 120 as suggested in another issue to increase the timeout. Still, after a while it becomes unavailable.

**Comment by firstof9** [comment]
**Environment (please complete the following information):**
 - OS: [e.g. HassOS/Raspbian/CentOS]
 - Type of device: [e.g. RPi3/NUC/Synology]
 - Home Assistant version: [e.g. 0.105.5]
 - Hassio/Docker/Core? 
 - Component version: [e.g. 0.1.2]

**Comment by Ali229** [comment]
Updated my post, thanks!

**Comment by firstof9** [comment]
Are you running the latest beta?

**Comment by Ali229** [comment]
How do I check?

**Comment by firstof9** [comment]
Check your `update.mail_and_packages_update` entity. It'll tell you what version you're running.

**Comment by Ali229** [comment]
Firmware: 0.3.5-b4

**Comment by firstof9** [comment]
May have to do with the change to python 3.10

**Comment by Ali229** [comment]
Any fix for this? It's making this integration unusable.

**Comment by firstof9** [comment]
Nope, it's not a problem at the integration level.

**Comment by coharness** [comment]
That fixed the issue from the Integration page, but my logs still say it's timing out fetching mail, leaving my sensors as `unavailable`.

**Comment by firstof9** [comment]
What's it saying in the logs? You may need to increase the IMAP timeout setting.

**Comment by Trebacz** [comment]
I think the same issue here - my setup:

OS: HassOS
Type of device: RPI4
Home Assistant version: 2022.07.6
Hassio
Component version: Firmware: 0.3.4-2

**Comment by firstof9** [comment]
> I think the same issue here

Try the latest beta version. Also never post images of text, just copy/paste text (it's bad form for those who have impaired sight).

**Comment by Trebacz** [comment]
> > I think the same issue here
> 
> Try the latest beta version. Also never post images of text, just copy/paste text (it's bad form for those who have impaired sight).

So I tried "Firmware: 0.3.5-b5". I restarted and still the issue. I went into the configuration and change Amazon Forward to (none) and things seem to be working again. The integration seems to be loading, counts are there. New set of errors look like this and no mail images are showing.

Platform mail_and_packages does not generate unique IDs. ID imap.gmail.com_Mail USPS Exception_f46a6b2b7d9b4887dd40b51ae219b6b5 already exists - ignoring sensor.mail_usps_exception
8:53:23 PM – (ERROR) Sensor - message first occurred at 8:52:44 PM and shows up 38 times
Platform mail_and_packages does not generate unique IDs. ID imap.gmail.com_Mail USPS Camera_f46a6b2b7d9b4887dd40b51ae219b6b5 already exists - ignoring camera.mail_usps_camera
8:53:23 PM – (ERROR) Camera - message first occurred at 8:52:44 PM and shows up 4 times
Platform mail_and_packages does not generate unique IDs. ID imap.gmail.com_USPS Image Updated_f46a6b2b7d9b4887dd40b51ae219b6b5 already exists - ignoring binary_sensor.usps_image_updated
8:53:23 PM – (ERROR) Binary sensor - message first occurred at 8:52:44 PM and shows up 4 times
Error updating sensor data: 'count'
8:51:18 PM – (ERROR) Mail and Packages (custom integration) - message first occurred at 8:49:37 PM and shows up 4 times
Error fetching Mail and Packages (imap.gmail.com) data: 'count'
8:51:18 PM – (ERROR) Mail and Packages (custom integration) - message first occurred at 8:49:37 PM and shows up 4 times
Problem updating sensors: 'count'
8:51:18 PM – (ERROR) Mail and Packages (custom integration) - message first occurred at 8:49:37 PM and shows up 4 times
TemplateError('ValueError: Template error: int got invalid input 'unavailable' when rendering template '{# Deliveries Sentence #} {% macro deliveries_sentence() -%} {%- if states("sensor.mail_usps_mail")|int == 0 -%} No {%- else -%} {{states("sensor.mail_usps_mail")|int}} {%- endif -%} {{' '}} {%- if states("sensor.mail_usps_mail")|int <= 1 -%} pieces of mail {%- else -%} pieces of mail {%- endif -%} {{' '}}will be delivered.{{' '}} {%- if states("sensor.mail_usps_delivering")|int == 0 -%} No {%- else -%} {{states("sensor.mail_usps_delivering")|int}} {%- endif -%} {{' '}} {%- if states("sensor.mail_usps_delivering")|int == 1 -%} USPS package is {%- else -%} USPS packages are {%- endif -%} {{' '}}in transit.{{' '}} {%- if states("sensor.mail_fedex_delivering")|int == 0 -%} No {%- else -%} {{states("sensor.mail_fedex_delivering")|int}} {%- endif -%} {{' '}} {%- if states("sensor.mail_fedex_delivering")|int == 1 -%} FedEx package is {%- else -%} Fedex packages are {%- endif -%} {{' '}}in transit.{{' '}} {%- if states("sensor.mail_ups_delivering")|int == 0 -%} No {%- else -%} {{states("sensor.mail_ups_delivering")|int}} {%- endif -%} {{' '}} {%- if states("sensor.mail_ups_delivering")|int == 1 -%} UPS package is {%- else -%} UPS packages are {%- endif -%} {{' '}}in transit.{{' '}} {%- if states("sensor.mail_amazon_packages")|int == 0 -%} No {%- else -%} {{states("sensor.mail_amazon_packages")|int}} {%- endif -%} {{' '}} {%- if states("sensor.mail_amazon_packages")|int == 1 -%} Amazon package is {%- else -%} Amazon packages are {%- endif -%} {{' '}}in transit.{{' '}} {%- endmacro %} {{deliveries_sentence()}}' but no default was specified') while processing template 'Template("{# Deliveries Sentence #} {% macro deliveries_sentence() -%} {%- if states("sensor.mail_usps_mail")|int == 0 -%} No {%- else -%} {{states("sensor.mail_usps_mail")|int}} {%- endif -%} {{' '}} {%- if states("sensor.mail_usps_mail")|int <= 1 -%} pieces of mail {%- else -%} pieces of mail {%- endif -%} {{' '}}will be delivered.{{' '}} {%- if states("sensor.mail_usps_delivering")|int == 0 -%} No {%- else -%} {{states("sensor.mail_usps_delivering")|int}} {%- endif -%} {{' '}} {%- if states("sensor.mail_usps_delivering")|int == 1 -%} USPS package is {%- else -%} USPS packages are {%- endif -%} {{' '}}in transit.{{' '}} {%- if states("sensor.mail_fedex_delivering")|int == 0 -%} No {%- else -%} {{states("sensor.mail_fedex_delivering")|int}} {%- endif -%} {{' '}} {%- if states("sensor.mail_fedex_delivering")|int == 1 -%} FedEx package is {%- else -%} Fedex packages are {%- endif -%} {{' '}}in transit.{{' '}} {%- if states("sensor.mail_ups_delivering")|int == 0 -%} No {%- else -%} {{states("sensor.mail_ups_delivering")|int}} {%- endif -%} {{' '}} {%- if states("sensor.mail_ups_delivering")|int == 1 -%} UPS package is {%- else -%} UPS packages are {%- endif -%} {{' '}}in transit.{{' '}} {%- if states("sensor.mail_amazon_packages")|int == 0 -%} No {%- else -%} {{states("sensor.mail_amazon_packages")|int}} {%- endif -%} {{' '}} {%- if states("sensor.mail_amazon_packages")|int == 1 -%} Amazon package is {%- else -%} Amazon packages are {%- endif -%} {{' '}}in transit.{{' '}} {%- endmacro %} {{deliveries_sentence()}}")' for attribute '_attr_native_value' in entity 'sensor.mail_deliveries_message'
8:49:37 PM – (ERROR) helpers/template_entity.py
Error while processing template: Template("{# Deliveries Sentence #} {% macro deliveries_sentence() -%} {%- if states("sensor.mail_usps_mail")|int == 0 -%} No {%- else -%} {{states("sensor.mail_usps_mail")|int}} {%- endif -%} {{' '}} {%- if states("sensor.mail_usps_mail")|int <= 1 -%} pieces of mail {%- else -%} pieces of mail {%- endif -%} {{' '}}will be delivered.{{' '}} {%- if states("sensor.mail_usps_delivering")|int == 0 -%} No {%- else -%} {{states("sensor.mail_usps_delivering")|int}} {%- endif -%} {{' '}} {%- if states("sensor.mail_usps_delivering")|int == 1 -%} USPS package is {%- else -%} USPS packages are {%- endif -%} {{' '}}in transit.{{' '}} {%- if states("sensor.mail_fedex_delivering")|int == 0 -%} No {%- else -%} {{states("sensor.mail_fedex_delivering")|int}} {%- endif -%} {{' '}} {%- if states("sensor.mail_fedex_delivering")|int == 1 -%} FedEx package is {%- else -%} Fedex packages are {%- endif -%} {{' '}}in transit.{{' '}} {%- if states("sensor.mail_ups_delivering")|int == 0 -%} No {%- else -%} {{states("sensor.mail_ups_delivering")|int}} {%- endif -%} {{' '}} {%- if states("sensor.mail_ups_delivering")|int == 1 -%} UPS package is {%- else -%} UPS packages are {%- endif -%} {{' '}}in transit.{{' '}} {%- if states("sensor.mail_amazon_packages")|int == 0 -%} No {%- else -%} {{states("sensor.mail_amazon_packages")|int}} {%- endif -%} {{' '}} {%- if states("sensor.mail_amazon_packages")|int == 1 -%} Amazon package is {%- else -%} Amazon packages are {%- endif -%} {{' '}}in transit.{{' '}} {%- endmacro %} {{deliveries_sentence()}}")
8:49:37 PM – (ERROR) helpers/template.py

**Comment by firstof9** [comment]
Please [enable debugging](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Troubleshooting#enable-debugging) to get more info.

**Comment by Trebacz** [comment]
I only enabled "debug"ging in my configuration.yaml (thanks for the link). Did a restart of HA (as I always do). And everything seems to work fine so far. The full delivery information is collected and displays on the dashboard as expected. No errors.

**Comment by Ali229** [comment]
This has stopped happening with the latest build of HA

**Comment by niemyjski** [comment]
I'm still seeing this issue with the latest HA

**Comment by niemyjski** [comment]
@firstof9 I was using latest stable and then now using latest beta with same issue, timeout is set to 30 seconds.

**Comment by firstof9** [comment]
What does the HA log say?

**Comment by niemyjski** [comment]
@firstof9 I'm seeing it do a massive number of searches on non us based amazon domains and non-English terms which cannot be helping... Here are the logs, hope this helps:

Seeing this error in the logs but it's going past it.
```
2022-09-09 10:46:38.276 DEBUG (SyncWorker_7) [custom_components.mail_and_packages.helpers] Looking for: A chegar:
account = config[CONF_EMAIL] if config else discovery_info["config"][CONF_EMAIL]
KeyError: 'email'
account = config[CONF_EMAIL] if config else discovery_info["config"][CONF_EMAIL]
KeyError: 'email'
account = config[CONF_EMAIL] if config else discovery_info["config"][CONF_EMAIL]
KeyError: 'email'
account = config[CONF_EMAIL] if config else discovery_info["config"][CONF_EMAIL]
KeyError: 'email'
2022-09-09 10:46:38.457 DEBUG (SyncWorker_7) [custom_components.mail_and_packages.helpers] Email Multipart: True
```

```
2022-09-09 10:47:25.737 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (OR OR FROM "shipment-tracking@amazon.de" FROM "conferma-spedizione@amazon.de" FROM "confirmar-envio@amazon.de" SINCE 06-Sep-2022)
2022-09-09 10:47:25.869 ERROR (MainThread) [custom_components.mail_and_packages] Timeout fetching Mail and Packages (imap.gmail.com) data
2022-09-09 10:47:25.869 DEBUG (MainThread) [custom_components.mail_and_packages] Finished fetching Mail and Packages (imap.gmail.com) data in 30.001 seconds (success: False)
2022-09-09 10:47:25.870 ERROR (MainThread) [custom_components.mail_and_packages] Error updating sensor data:
2022-09-09 10:47:25.993 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] DEBUG email_search value: ('OK', [b''])
```

It looks like it's completing but the sensors are all unavailable and addon is stuck at initializing.

**Comment by firstof9** [comment]
> Finished fetching Mail and Packages (imap.gmail.com) data in 30.001 seconds (success: False)

You're hitting the 30s timeout and it bails out.

**Comment by niemyjski** [comment]
@firstof9 I would think the timeout would be on a per query basis not running all searches... Is there any way to limit my searches to only us amazon domains and English terms? This would cut out 60% or more of the searches.

**Comment by firstof9** [comment]
You could manually modify the `const.py` until I can come up with a better configuration method.

**Comment by niemyjski** [comment]
Thank you
