### ISSUE TITLE
ISSUE: Mail Photos are Public

### ISSUE THREAD

**Issue by KennyStier61** [moralmunky/Home-Assistant-Mail-And-Packages#70]
**Describe the bug**
The mail_today.gif is publicly accessible without Home Assistant login, which is a serious privacy issue.

**Environment (please complete the following information):**
 - OS: Debian 10
 - Type of device: x86
 - Home Assistant version: 0.106.6
 - Docker
 - Component version: 0.1.2

**Additional context**
When I open https://DOMAIN/local/mail_and_packages/mail_today.gif in a private window when I am not logged in, I can see all of my mail.

**Comment by firstof9** [comment]
So configure it not to be in the www directory.

**Comment by firstof9** [comment]
I'll change the default to a ```config/images/mail_and_packages``` folder to alleviate concerns.

**Comment by moralmunky** [comment]
This could also be considered a breaking change. I _think_ the image needs to be publicly accessible for certain notifications if you are delivering the image with it. We should make a note to add that in documentation somewhere if that is the case.

**Comment by firstof9** [comment]
Technically only if you're linking to it via URL methods. Just about every notification has a file option to send the image as an attachment rather than a URL.

**Comment by firstof9** [comment]
> We should make a note to add that in documentation somewhere if that is the case.

I've added a blurb in the README about security concerns.

**Comment by firstof9** [comment]
@moralmunky I think we've caught all the areas, what do you think?

**Comment by moralmunky** [comment]
I assume that most users will use the [companion mobile app for notifications](https://companion.home-assistant.io/docs/notifications/notification-attachments). I have been trying to come up with a solid example notification to provide in the readme.

With dynamic attachments we can leverage cameras, but the image doesn't rotate and is severely distorted. I believe it doesn't stream because it's not an Mjpeg stream camera.

![IMG_0759](https://user-images.githubusercontent.com/19318945/77233984-94d28800-6b81-11ea-9ecb-1451e6bea3de.png)


With standard attachments, url (iOS) and image (android) can be used but the supplied but the image must be accessible from the internet.

I was thinking a way around this may be to create a random file name each time the image is created and store that name as an attribute so we can retrieve it for notifications. In order to continue to support the camera module we could also save the normal mail_today.gif in an internal folder like your hot fix suggests. Thoughts?

**Comment by firstof9** [comment]
> I was thinking a way around this may be to create a random file name each time the image is created and store that name as an attribute so we can retrieve it for notifications.

I like this idea.

**Comment by ttaidapos** [comment]
> > I was thinking a way around this may be to create a random file name each time the image is created and store that name as an attribute so we can retrieve it for notifications.
> 
> I like this idea.
> 
> To expand on it we could use a UUID module to generate random long string file names.

My .02, just include instructions to create a secure directory along with the chown and chmod commands.  Most www folders you still need to know the file name to retrieve artifacts, it's not that you can simply browse.  I agree that images folders should reside in the config directory and not www.

**Comment by moralmunky** [comment]
Are there not existing recommendations for the www directory from Home Assistant? On my instance www.domain.com/local/ nor sub folders are browsable. It returns a 403 error.

By changing the name of the publicly accessible file to a random string each time it is generated we are mitigating risk of a scan simply looking for the standard url path of www.hassdomain.com/local/mail_and_packages/mail_today.gif to steal the image.

We could also have this additional random string image be an option to turn on in the configuration for those that are hyper security conscious.

**Comment by firstof9** [comment]
If anyone would like to give some beta code a shot for the random image filename here's an update:

https://raw.githubusercontent.com/firstof9/Home-Assistant-Mail-And-Packages/random-image-name/custom_components/mail_and_packages/sensor.py

**Comment by KennyStier61** [comment]
I'd be happy to!
Thank you all for getting right to it, I really appreciate your work!

**Comment by firstof9** [comment]
It should update the filename each time the sensor is ran, kinda makes it more secure.

**Comment by ttaidapos** [comment]
Any way we can update the permissions once the mail_today.gif is written? If we can set chown to 640 or remove "anyone" completely, this will also solve this issue.

**Comment by moralmunky** [comment]
For the home assistant companion app, images are passed as a URL for notifications and must be publicly accessible.

**Comment by firstof9** [comment]
That won't fix the issue, since homeassistant would still have access to the file to send it via http(s) requests. The randomized filename and the default location changes are far better. Also an automation could be setup to copy file randomized file name to "mail_today.gif" into the images folder to keep picture cards from breaking.

**Comment by ttaidapos** [comment]
> That won't fix the issue, since homeassistant would still have access to the file to send it via http(s) requests. The randomized filename and the default location changes are far better. Also an automation could be setup to copy file randomized file name to "mail_today.gif" into the images folder to keep picture cards from breaking.

Is this true with username/password + 2FA enabled?  as a temp. solution I 640 all files i was hosting in www (thanks btw, never new it was public) and sent a few urls to friends.  They were not able to open any and hass worked with no issues.

**Comment by firstof9** [comment]
> Is this true with username/password + 2FA enabled?

yes



> as a temp. solution I 640 all files i was hosting in www (thanks btw, never new it was public) and sent a few urls to friends. They were not able to open any and hass worked with no issues.

try accessing images via chrome or whatever browser on your cell phone while on mobile data and they should come right up unless you have them blocked them via a reverse proxy.

**Comment by moralmunky** [comment]
> If anyone would like to give some beta code a shot for the random image filename here's an update:
> 
> https://raw.githubusercontent.com/firstof9/Home-Assistant-Mail-And-Packages/random-image-name/custom_components/mail_and_packages/sensor.py

Getting this error, grabbed the whole repository incase there were changes that were needed outside of the sensor.py

```
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 66, in async_setup_entry
    async_add_entities([MailCheck(data), USPS_Mail(hass, data),
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 181, in __init__
    self.update()
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 213, in update
    self.data.update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 120, in update
    self._image_name = uuid.uuid4() + ".gif"
TypeError: unsupported operand type(s) for +: 'UUID' and 'str'
```

**Comment by firstof9** [comment]
Try changing line 120 to:
```
            self._image_name = str(uuid.uuid4()) + ".gif"
```

**Comment by moralmunky** [comment]
Got a nice long string for the file name with that adjustment!

**Comment by firstof9** [comment]
Here's an automation that should auto update the camera:

```
- alias: 'Update USPS Mail Camera'
  trigger:
    - platform: template
      value_template: "{{ state_attr('sensor.mail_usps_mail','image') }}"

  action:
    - service: local_file.update_file_path
      data_template:
        entity_id: camera.mail_usps
        file_path: /home/homeassistant/.homeassistant/www/mail_and_packages/{{ state_attr('sensor.mail_usps_mail','image') }}
```

**Comment by KennyStier61** [comment]
I tried downloading and using the sensor.py file linked earlier, but didn't notice any file name changes. Just now I cloned the dev branch and now I am getting errors when I start Home Assistant

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/mail_and_packages/sensor.py", line 63, in async_setup_entry
    CONF_IMAGE_SECURITY: entry.data[CONF_IMAGE_SECURITY],
KeyError: 'image_security'
```

**Comment by firstof9** [comment]
@KennyStier61 reconfigure the integration by hitting the cog in the upper right hand corner:

![image](https://user-images.githubusercontent.com/1105672/79073081-54a28900-7c99-11ea-9b1a-36f7ae044c54.png)

That will clear the error and reload the sensors.

**Comment by ttaidapos** [comment]
> Here's an automation that should auto update the camera:
> 
> ```
> - alias: 'Update USPS Mail Camera'
>   trigger:
>     - platform: state
>       entity_id: sensor.mail_usps_mail
> 
>   action:
>     - service: local_file.update_file_path
>       data_template:
>         entity_id: camera.mail_usps
>         file_path: >
>           {% if state_attr('sensor.mail_usps_mail','image') == None  %}
>           /home/homeassistant/.homeassistant/custom_components/mail_and_packages/mail_none.gif
>           {% else %}
>           /home/homeassistant/.homeassistant/www/mail_and_packages/{{ state_attr('sensor.mail_usps_mail','image') }}
>           {% endif %}
> ```

Any ideas on a different trigger?  Seems on some reboots you have to manually invoke the automation trigger/toggle to update the file path.  For the time being on the camera sensor i just put "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/mail_none.gif" since it's static and it will always display an image.  This workaround is ok for now but in some scenarios, there will not be a state change for a least a day or in some instances even longer.

P.S  Documentation needs to be updated, I can see some beginners running into head scratches with the new feature of UUID for the file names.

I'm on hacs/0.1.5

**Comment by moralmunky** [comment]
@ttaidapos UUID is pre-release we are working through the nuances ourselves. Feels free to pitch in and submit a PR for documentation.
