### ISSUE TITLE
[Feature Request] Swap myhermes to new Evri company

### ISSUE THREAD

**Issue by smcnab1** [moralmunky/Home-Assistant-Mail-And-Packages#719]
**Is your feature request related to a problem? Please describe.**
myHermes no longer working in UK, Evri is the new company that replaced myHermes

**Describe the solution you'd like**
Inclusion of Evri into sensors to replace Hermes

**Comment by firstof9** [comment]
Need example emails in order to assess if this would be doable.

**Comment by smcnab1** [comment]
> Need example emails in order to assess if this would be doable.

do-not-reply@evri.com

**Comment by firstof9** [comment]
No the actual emails.

**Comment by smcnab1** [comment]
Do you have an email I can forward them to for you? @firstof9

**Comment by firstof9** [comment]
firstof9 at gmail.com

It's best to save the emails and attach them. If you are using gmail you can view my [previous instructions here](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues/206#issuecomment-699272620) on how to obtain the emails.

**Comment by smcnab1** [comment]
> firstof9 at gmail.com
> 
> It's best to save the emails and attach them. If you are using gmail you can view my [previous instructions here](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues/206#issuecomment-699272620) on how to obtain the emails.

Sent just now.

**Comment by firstof9** [comment]
Please test the beta: `0.3.5-b14` with the new Evri sensors.
