### ISSUE TITLE
ISSUE: DHL delivery notification address missing

### ISSUE THREAD

**Issue by Jaharmi** [moralmunky/Home-Assistant-Mail-And-Packages#727]
**Describe the bug**
A recent DHL delivery's notifications were sent from the following address that is not currently in the `const.py` file:

`DHL Customer Support <support@dhl.com>`

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: ESXi HA VM
 - Home Assistant version: Home Assistant 2022.9.7
 - Hassio
 - Component version: 0.3.4-2

**Logs**
No error logs.

**Screenshots**
n/a

**Additional context**
I subscribed to notifications for a specific DHL package at myDHL. (I didn't see a way to get general notifications for my address, as with some other shippers.)

Subject:
`DHL Shipment Notification : `

Email source: redacted and attached.
[DHL-shipment-notification-20221003.txt](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/files/9701090/DHL-shipment-notification-20221003.txt)

**Comment by firstof9** [comment]
This format doesn't match any of their previous formats.

From address is different, subject is different, and so is the body message.

**Comment by Jaharmi** [comment]
If it is as simple as adding an email address, subject, and body text string to `const.py`, I can do a PR shortly. I'm waiting for the actual delivery to confirm the text in that email message.

**Comment by firstof9** [comment]
Yes that's basically the only mod to be done, update the `const.py` data and append the address, subject and body messages.

**Comment by firstof9** [comment]
Please make sure to modify the `dev` branch not `master`

**Comment by Jaharmi** [comment]
Will do, thanks!
