### ISSUE TITLE
ISSUE: 15,000 image files accumulated

### ISSUE THREAD

**Issue by astranberg** [moralmunky/Home-Assistant-Mail-And-Packages#728]
**Describe the bug**
Over 15k image files have been accumulated under the /images/amazon/ folder.

**Environment (please complete the following information):**
 - OS:hassio
 - Type of device: rpi4
 - Home Assistant version: 2022.9.7
 - Hassio
 - Component version: v0.3.4-2
 
**Additional context**
It seems to not be deleting any old files.

**Comment by firstof9** [comment]
Please provide the following information:

- Component version:

**Comment by ledhed-jgh** [comment]
I have a similar issue.

Home Assistant Version: 2022.9.4
Component Version: 0.3.5-b15

**Comment by firstof9** [comment]
Sounds like a permissions issue, any errors in `home-assistant.log` ?

**Comment by ledhed-jgh** [comment]
The only thing in the logs is a Warning
`2022-10-20 11:49:23.742 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.`

In the meantime, I've written a script that manually deletes images that are over a week old and schedule it to run at midnight.

**Comment by firstof9** [comment]
The integration cleans up the images on it's own as long as the directory permissions are fine.

**Comment by ledhed-jgh** [comment]
What should the directory permissions be?

**Comment by firstof9** [comment]
`750` should be fine and the owner should be whatever user owns `.storage` as well.

**Comment by ledhed-jgh** [comment]
Its HA OS, so root owns everything.  Permissions are 755
`drwxr-xr-x    2 root    root        258048 Oct 20 00:00 amazon`

**Comment by ledhed-jgh** [comment]
file permissions are root root 644

**Comment by firstof9** [comment]
very odd, I ran in to this only once long ago when there was a bug, since then I haven't had it occur.

**Comment by astranberg** [comment]
> Please provide the following information:
> 
>     * Component version:

updated in OP

**Comment by astranberg** [comment]
> Sounds like a permissions issue, any errors in `home-assistant.log` ?

Nothing useful. Just:

This error originated from a custom integration.

> 
> Logger: custom_components.mail_and_packages
> Source: helpers/update_coordinator.py:182
> Integration: Mail and Packages (documentation, issues)
> First occurred: 1:20:23 PM (1 occurrences)
> Last logged: 1:20:23 PM
> 
> Timeout fetching Mail and Packages (imap.gmail.com) data

But I think that's just a boot-up issue.
