### ISSUE TITLE
[Feature Request] Ability to manually reset counters.

### ISSUE THREAD

**Issue by ledhed-jgh** [moralmunky/Home-Assistant-Mail-And-Packages#732]
**Describe the solution you'd like**
I would like to be able to reset the counters (example: Mail Amazon Packages Delivered) to zero after I've retrieved the package.

**Describe alternatives you've considered**
I suppose I could create an input boolean and whenever the Mail & Package counters are greater than 0 I could set it to true. Then when the package is received, I could reset to false. 

**Additional context**
Being that the add-on already resets the counter at a specific time, it shouldn't be hard to implement a service to reset the counters manually, though maybe a bit tedious to create a reset service for each counter.

**Comment by firstof9** [comment]
What's the use case?

The counts are determined by the emails sent for the day so the reset at midnight.

**Comment by ledhed-jgh** [comment]
One use case would be for mail in a mailbox. For example, my mail is in a community mailbox down the street, on my drive home I stop by the mailbox and get the mail.  Mail and Packages w/ the USPS integration will let me know there's mail in the mailbox, and I can see that on my way home. However, I cannot see if someone has already gone to the mailbox and picked up the mail.  If I could reset the counter, then I could spare myself a trip to an empty mailbox. I could even alert myself using geofencing only when there's mail to be picked up.

Another use case is that it would be helpful to know that a package has been picked up. For example, if an Amazon package is delivered, a light is set to blue which tells the kids to get the package off the porch. Then they press a button to reset the counter(s) and turns off the blue indicator light. Now I know the package is not sitting on the porch where it can be stolen because the counter is now zero. You could even send a phone notification for "package delivered", and "package received" (when the counter returns to zero).

**Comment by firstof9** [comment]
This really seems out side the scope of the integration, more along the lines of something that could be handled within HA itself.

**Comment by ledhed-jgh** [comment]
I don't see how its outside the scope of the integration, you're already resetting the counters (on a schedule), I'm just asking for a way to trigger that manually.  Alternatively, a method of adjusting the counters value would also work.

I probably can find a way to accomplish the above use cases with HA, but that would involve creating a bunch of duplicate helpers and then write multiple automations/scripts to try and sync them too this integration.

**Comment by moralmunky** [comment]
Couldn't the same thing be accomplished if you moved the email from the folder the integration is checking? The next time the integration polls the email account that provider would be set to 0 since the email wouldn't be returned in the search.

**Comment by ledhed-jgh** [comment]
How would I move the email through a HA automation?

**Comment by moralmunky** [comment]
Through a web or desktop email client.

There is no functionality in the integration or HA to manage emails in an account. The integration is very equivalent to a web scraper for email. It searches the email box for specific list of known senders and subject line contents then counts the results. There is no database or comparison logic between scans which is one reason this request is out of scope.

So the simplest way would to manually move that providers out for delivery and delivered emails to another location in your mail account, or delete them. The next scan will return 0 for that provider. You set the interval of scanning in the integration second settings page.

If you wanted a more complicated solution in HASS. You would create a template sensor and input boolean for each shipping provider you have turned on in the integration. The sensors template logic would be… If input_boolean_A is turned on,  show 0, else show the state of the mail and packages sensor.

For example UPS

{% if is_state("input_boolean.mail_ups_package", "on") -%}
  0
{%- else -%}
  {{states("sensor.mail_ups_packages")}}
{%- endif %}

**Comment by ledhed-jgh** [comment]
Ya, I understand how the integration works. Manually moving the email to reset the counter doesn't really make sense in my use case. I'm not going to have my kids move an email when they grab a package off the porch or get mail from the physical mailbox.

I didn't think a manual reset would be that difficult of an ask, but I guess the fact that it checks mail at an interval and updates the sensors based on the "scraped" data is where the difficulty is.  If a user manually resets, at the next interval/mail check it will just re-update the counters. I also assume that there isn't any variable retained between mail checks so there isn't a way to track the actual numbers and resets.

Building out half a dozen template sensors is more work than it's worth and kind of kludgy IMHO. However, there's more than one way to skin a cat, perhaps I'll take a stab at Object Detection and see if that suits my needs.  I appreciate the consideration.
