### ISSUE TITLE
Error searching emails: SEARCH command error: BAD [b'Could not parse command']

### ISSUE THREAD

**Issue by TermiNaderTL** [moralmunky/Home-Assistant-Mail-And-Packages#738]
I've tried reloading and reconfiguring, but this error message persists.  Is there something else I should try to address it?

I'm using version 0.3.5-b16.

Thanks!
---------

This error originated from a custom integration.

Logger: custom_components.mail_and_packages.helpers
Source: custom_components/mail_and_packages/helpers.py:185
Integration: Mail and Packages (documentation, issues)
First occurred: October 27, 2022 at 7:28:12 AM (2312 occurrences)
Last logged: 9:52:55 AM

Error searching emails: SEARCH command error: BAD [b'Could not parse command']

**Comment by firstof9** [comment]
Please grab the diagnostics file:
![image](https://user-images.githubusercontent.com/1105672/198850052-d6e3ffef-6254-4555-b899-a1c9f783e457.png)

As well as [enabling debugging](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Troubleshooting#enable-debugging) and post the logs.

**Comment by TermiNaderTL** [comment]
This issue happened because I had to enter double quotes around the Amazon forwarding e-mail address so that the configuration form would accept the e-mail address.  I reloaded the integration, did the configuration entries again and the form allowed me to enter the Amazon forwarded e-mail address without the quotes.  Issue went away!
