### ISSUE TITLE
ISSUE: retrying setup: none

### ISSUE THREAD

**Issue by Jezza1232** [moralmunky/Home-Assistant-Mail-And-Packages#746]
**Describe the bug**
After I setup mail and package it went though just fine but after setup it now says retrying setup: none and dose not work. If I delete the one time app password it goes away but everything shows as unnone state

**Environment (please complete the following information):**
 - OS: HassOS 
 - (VM on windows 10 with pip and python installed)
 - Type of device: [microsoft surface pro 5 windows 10(mainOS) Virtual Box install]
 - Home Assistant version: [2022.11.2]
 - HassOS Core with supervisor
 - Component version: [2.3.4-2] newest downloaded version from HACS

**This error originated from a custom integration.

Logger: custom_components.mail_and_packages
Source: helpers/update_coordinator.py:182
Integration: Mail and Packages (documentation, issues)
First occurred: 9:48:15 PM (30 occurrences)
Last logged: 10:27:30 PM

Error fetching Mail and Packages (IMAP.gmail.com) data: 'count'
Timeout fetching Mail and Packages (IMAP.gmail.com) data

**Screenshots**
![Screenshot_20221110_095001_Home Assistant](https://user-images.githubusercontent.com/97153995/200959041-17f01205-09bd-43da-a35f-3316fd457779.jpg)

**Additional context**
There are other logs in log about this they appear at the same time

**Comment by firstof9** [comment]
Please fill in the information requested.

**Comment by Jezza1232** [comment]
I'm new here I filled in as much info as I can (updates just now)

**Comment by firstof9** [comment]
Please use the latest beta release, this should solve many issues.

**Comment by Jezza1232** [comment]
Thank you soon much I will try this right now

**Comment by firstof9** [comment]
Check your `home-assistant.log` file in your `/config` directory for more details.

**Comment by Jezza1232** [comment]
My phone won't let me copy anything anymore 😤 so I can't post the logs. but it's saying timeout in the home-assistant.log and due the that error it can't update the sensor making the second error so my guess is because I set the image timeout to 30 seconds? As there is 2 logs saying something about the component and more the 10 seconds.

Im trying to find a way to post the entries in the home-assistant.log due to HA running on my pc (stupid I know but I can't afford a raspberry pi right now) so this has to do (hasn't crashed once)

**Comment by Jezza1232** [comment]
Update. I have removed python scripting addonand there are only logs from the mail_package add-on the one stated in one of the above posts

**Comment by Jezza1232** [comment]
New update 

I am re installing a new home assistant setup from scratch as there are major problems in my  Custom_component and I can't get rid of them hass won't let me due to not being empty but they appear to be so I'm resetting and let you know how I go with my new hass os setup

**Comment by Jezza1232** [comment]
After a new fresh install of home assistant updated with mail and Packages only and still saying the same thing could it be my app password setup? Google separated the password to 4 different lots, when coping the password it li ks it all together maybe this is the issue? I'm really not sure (not home assistant smart)

**Comment by firstof9** [comment]
These are not logs, look in the `home-assistant.log` file in your `/config` directory.

**Comment by Jezza1232** [comment]
My pc use to crash when using Windows 11 and virtual box at the same time. with the power of Windows 10 I give you the home-assistant.log file (about time I got it lol) I'm so sorry I'm slow guys

![Screenshot_20221113_114039_Log Viewer.jpg](https://user-images.githubusercontent.com/97153995/201500176-42cc5164-942b-4406-af41-2b8683909f04.jpg)

**Comment by Jezza1232** [comment]
No change is there a way I can send you the home-assistant.log file direct? I tried uploading it here but not sure how when I press attach file it gives me ( ) and dose nothing (using github app)

**Comment by Jezza1232** [comment]
I replied to the email on gmail I got from Chris about it on github and sent it there

**Comment by Jezza1232** [comment]
It really worked thank you all so much issue was: connection timeout here in Australia must be set to 60 give the system a reboot and wait till it says connection failed (config not ready) then simply wait and leave it it will update when the system finishes booting and become ready thank you all so much
