### ISSUE TITLE
ISSUE: search bad command

### ISSUE THREAD

**Issue by Jezza1232** [moralmunky/Home-Assistant-Mail-And-Packages#748]
**Describe the bug**
Log entry 

**Environment (please complete the following information):**
 - OS: [HassOS 9.3]
 - Type of device: [windows VM]
 - Home Assistant version: [2022.11.2]
 -supervisor 2022.10.2
 - Component version: [0.3.5-b19]

**Logs**
This error originated from a custom integration.

Logger: custom_components.mail_and_packages.helpers
Source: custom_components/mail_and_packages/helpers.py:187
Integration: Mail and Packages (documentation, issues)
First occurred: 11:42:53 AM (173 occurrences)
Last logged: 12:52:38 PM

Error searching emails: SEARCH command error: BAD [b'Could not parse command']

**Screenshots**
![Screenshot_20221114_130111_Home Assistant](https://user-images.githubusercontent.com/97153995/201559749-312634cc-4d68-46df-b87e-4778b6d1d8cf.jpg)
![Screenshot_20221114_130233_Home Assistant](https://user-images.githubusercontent.com/97153995/201559910-33558f99-7daf-4505-a06c-394ece6246c1.jpg)

**Additional context**
All is running well but have this error in my log can see it in home-assistant.log as well but addon seems perfect though

**Comment by firstof9** [comment]
Set your "Amazon forwards" to `(none)`

**Comment by Jezza1232** [comment]
It's working now thank you

**Comment by bmcclure** [comment]
I'm still having this same issue... Mail & Packages won't work for me at all, and this is seemingly the only useful error in the logs about it. Changing the amazon forwarding address option to "" or (none) seems to have no effect.

**Comment by Jezza1232** [comment]
I got it to work first of all it's the app password when setting up the app
password select "other" then name it Home Assistant, then copy the password
it gives you. Now use the beta version of mail and packages and proceed
with setup. Remember to setup your sensors the very top and both at very
bottom are 100% crucial
