### ISSUE TITLE
ISSUE: No External URL Error With Nabu Casa

### ISSUE THREAD

**Issue by LordNex** [moralmunky/Home-Assistant-Mail-And-Packages#752]
**Describe the bug**
I'm Getting the following error even though I use Nabu Casa as well as DuckDNS for name resolution. Doesn't seem to cause any specific issue with the integration except the error in the Supervisor Log

```
This error originated from a custom integration.

Logger: custom_components.mail_and_packages.sensor
Source: custom_components/mail_and_packages/sensor.py:200
Integration: Mail and Packages (documentation, issues)
First occurred: 12:39:51 AM (1 occurrences)
Last logged: 12:39:51 AM

External URL not set in configuration.
```

Here is my config in System>Network

![Capture](https://user-images.githubusercontent.com/9270948/202375860-3f7745fa-55af-4270-a20f-068c1d97f12c.JPG)

**Environment (please complete the following information):**
 - OS:  HassOS OVA
 - Type of device: Dell PowerEdge R620 Running VMWare ESXi 7,0,3 (40 cores\256g ram\3.2TB SAN)
 - Home Assistant version: 2022.11.3
 - OVA VMware Image running Home Assistant OS (VM Has 8 cores\32 gig of ram\512GB Data Partition)
 - Component version: 0.3.4-2

**Comment by firstof9** [comment]
That's just a warning you can ignore it.
