### ISSUE TITLE
USPS mail reports one item, but multiple exist

### ISSUE THREAD

**Issue by jkfranks9** [moralmunky/Home-Assistant-Mail-And-Packages#761]
USPS informed delivery daily digest contains multiple items, but only one is reported. Images below show the mail entity, the 3 items in the email, and the generated mail image. Also attached are the email document and the integration diagnostics.

![Mail Entity](https://user-images.githubusercontent.com/27896353/204814984-eb670306-f31c-4d8d-941b-150fb7481313.png)
![Mail 1](https://user-images.githubusercontent.com/27896353/204815283-5e596abb-b238-452e-91b8-568e1a192697.png)
![Mail 2](https://user-images.githubusercontent.com/27896353/204815284-4de11eb3-f631-4431-b7f0-fcc814906706.png)
![Mail 3](https://user-images.githubusercontent.com/27896353/204815287-84cc56ef-c912-4164-99a8-ef4e1e08df18.png)

Generated image:
![7570c76c-2e52-4d85-af45-c668b3780f5c](https://user-images.githubusercontent.com/27896353/204817471-7dd32649-2119-43bc-b2eb-ba2d2c488a2d.gif)

[Your Daily Digest for Wed, Nov 30.zip](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/files/10123868/Your.Daily.Digest.for.Wed.Nov.30.zip)
[config_entry-mail_and_packages-e25c1b22d794c37199a7dbb60d9427b7.json.txt](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/files/10123912/config_entry-mail_and_packages-e25c1b22d794c37199a7dbb60d9427b7.json.txt)

**Comment by firstof9** [comment]
Junk mail adverts are filtered out.

**Comment by jkfranks9** [comment]
OK, thanks for that info. Closing.
