### ISSUE TITLE
ISSUE: Not picking up UPS packages.

### ISSUE THREAD

**Issue by TheOneOgre** [moralmunky/Home-Assistant-Mail-And-Packages#765]
**Describe the bug**
I have an email after setting up the integration from UPS with the tracking number and all details, but the integration doesn't pull any information, while it is working for USPS

**Environment (please complete the following information):**
 - OS: Docker
 - Type of device: Docker
 - Home Assistant version: 2023.1.0.dev20221205
 - Docker/HACS
 - Component version: 0.3.5-b20

**Logs**
This error originated from a custom integration.

Logger: custom_components.mail_and_packages.helpers
Source: custom_components/mail_and_packages/helpers.py:187
Integration: Mail and Packages (documentation, issues)
First occurred: 10:18:09 AM (49 occurrences)
Last logged: 10:33:12 AM

Error searching emails: SEARCH command error: BAD [b'Could not parse command']
Unexpected html format found.

This is the only error related to the integration 

**Screenshots**
![IMG_20221207_102920](https://user-images.githubusercontent.com/17228590/206222176-c5384f1a-ed5d-4a10-a8ce-f9b12f1265e6.jpg)

**Additional context**
It seems though USPS is working fine and being picked up, the UPS informed delivery emails are not being parsed correctly.

**Comment by TheOneOgre** [comment]
I'd just like to add I've had numerous extra emails from ups come through with different numbers and statuses. Still same issue. Based on the error seems error parsing their HTML?

**Comment by firstof9** [comment]
> Error searching emails: SEARCH command error: BAD [b'Could not parse command']

This is _usually_ due to the `Amazon Forwards` email being set to something other than `(none)`.

> Unexpected html format found.

This message is for USPS emails, safe to ignore.

There is no bug here, you'll get emails on Friday when/if your package is actually out for delivery, then it'll populate in the sensors.

**Comment by TheOneOgre** [comment]
So this issue is still occuring, even after almost 30+ UPS emails. None of them are populating and even though my Amazon forward address is set to nothing, I'm still getting the same errors. Not sure what is happening or what other logs to provide.

**Comment by firstof9** [comment]
[Enable debug logging](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Troubleshooting#enable-debugging) to see what's going on.

**Comment by trentjw** [comment]
same for me Fedex, USPS, and Amazon seem to be working but UPS is not

**Comment by firstof9** [comment]
Check these lines and see if they match any of your UPS emails:

https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/blob/6abdb93cc06ab5ade630ce5ca797e0283ebb7fe0/custom_components/mail_and_packages/const.py#L153-L174

**Comment by trentjw** [comment]
UPS Email address `mcinfo@ups.com`

my sublect line is 
first notice `UPS Update: Package Scheduled for Delivery Tomorrow`
Second notice `UPS Pre-Arrival: Your Driver is Arriving Soon! Follow on a Live Map.`
Third notice `UPS Update: Package Scheduled for Delivery Today`
Forth Notice `Your UPS Package was delivered`

**Comment by firstof9** [comment]
So your counter should have shown `ups_delivering: 1` on notice 3 and notice 4 would be `ups_delivered: 1`.

**Comment by TheOneOgre** [comment]
After enabling the debug logging, the only error that keeps showing up is the "Unexpected HTML format found" There are no other entries for the integration, only that one.

None of the UPS sensors are showing anything other than 0, or whatever their default is. The USPS/FedEx continues to work fine.

**Comment by firstof9** [comment]
> None of the UPS sensors are showing anything other than 0

This would mean the UPS emails are not coming from `mcinfo@ups.com` and/or the subjects don't match.

**Comment by firstof9** [comment]
Would need to see the debug logs.

**Comment by trentjw** [comment]
> So your counter should have shown `ups_delivering: 1` on notice 3 and notice 4 would be `ups_delivered: 1`.

Nope it never happened

**Comment by trentjw** [comment]
> > > None of the UPS sensors are showing anything other than 0
> > 
> > 
> > This would mean the UPS emails are not coming from `mcinfo@ups.com` and/or the subjects don't match.
> 
> I just checked the email and they are all coming from [mcinfo@ups.com](mailto:mcinfo@ups.com)
> 
> And an example subject is:
> 
> UPS Shipping Notification, Tracking Number 1Zxxxxxxxxxxxxx
> 
> Me and @trentjw seem to have the same exact issue as my 4 notices are all the same and match up with what he is experiencing.
> 
> @trentjw Did you just set up the integration or did you have it working previously before and is now broken? Maybe UPS changed something that broke the parser?

It worked with ups when I first installed it but only the notice that something was delivered

**Comment by TheOneOgre** [comment]
> Would need to see the debug logs.

As I've stated before, the only thing in the debug logs is this single line that keeps happening over and over, nothing else is written in the log

`2022-12-19 18:47:09.454 WARNING (SyncWorker_4) [custom_components.mail_and_packages.helpers] Unexpected html format found.`

**Comment by firstof9** [comment]
Those are not debug logs, please see [this link to enable debug logging](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Troubleshooting#enable-debugging).

**Comment by TheOneOgre** [comment]
> Those are not debug logs, please see [this link to enable debug logging](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Troubleshooting#enable-debugging).

Okay gotcha. I enabled debug logging from the integrations section of HA and the integration didn't produce any debug logs, this way did however there doesn't seem to be anything throwing errors, just everything coming back as 0 for UPS

``

**Comment by TheOneOgre** [comment]
If I'm not mistaken, the issue seems to be that the subject line is looking specifically for "package" but UPS emails send "parcel" 

Could that the discrepancy?

**Comment by firstof9** [comment]
Yes, that's why I asked for you guys to verify the subject lines :wink: 

Is this the full subject line? 
`"Your UPS Parcel was delivered"`

if so what did your "out for delivery" subject line look like?

**Comment by TheOneOgre** [comment]
> Yes, that's why I asked for you guys to verify the subject lines 😉
> 
> Is this the full subject line? `"Your UPS Parcel was delivered"`
> 
> if so what did your "out for delivery" subject line look like?

Ah, a blunder on my part. I read parcel/packages the same way and thus didn't notice the syntax difference. 😂

UPS Update: Parcel Scheduled for Delivery Today

Your UPS Parcel was delivered

UPS Update: New Scheduled Delivery Date and Estimated Delivery Time

UPS Shipping Notification, Tracking Number 1Zxxxxxxxxxxx

Are all subject line examples of what I receive

**Comment by trentjw** [comment]
> Yes, that's why I asked for you guys to verify the subject lines 😉
> 
> Is this the full subject line? `"Your UPS Parcel was delivered"`
> 
> if so what did your "out for delivery" subject line look like?

I copied and pasted my subject lines in a previous post

**Comment by firstof9** [comment]
Should be solved in `0.3.5-b21`.

**Comment by TheOneOgre** [comment]
> Should be solved in `0.3.5-b21`.

Fixed. Thanks!
