### ISSUE TITLE
ISSUE: Error logging into IMAP Server: b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'

### ISSUE THREAD

**Issue by NeoFax75** [moralmunky/Home-Assistant-Mail-And-Packages#770]
**Describe the bug**
Was working fine with an App Password and 2FA until I switched from my RPI4 to a Intel Nuc.  Now all of my Google authentications are not working.

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: Intel Nuc
 - Home Assistant version: 2022.12.7
 - Hassio
 - Component version: [e.g. 0.1.2]

**Logs**
Error logging into IMAP Server: b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'

**Additional Context**
Running inside of PROXMOX.

**Comment by firstof9** [comment]
Your username or password is wrong.

**Comment by NeoFax75** [comment]
I have checked and it is the correct username and password.  However, when I submit and it finally errors out after appx. 30 minutes my old password is back in the submit box.

**Comment by firstof9** [comment]
Gmail?

**Comment by NeoFax75** [comment]
Yes.

**Comment by firstof9** [comment]
So you've entered the correct app password?

**Comment by NeoFax75** [comment]
Yes, I have copied it and saved it in my Bitwarden vault and paste it into
Home Assistant's setup for Mail and Packages.

**Comment by firstof9** [comment]
I don't know what to tell you, I do the same thing and it works fine for me.
Make sure there's no extra spaces or anything at the end.

**Comment by NeoFax75** [comment]
[image: MailNPackagesError1.png]

Here is the error after completely removing the package from Integrations
and HACS.  As you can see there is an error.  I can use the app password to
login, so there is something causing the error.

**Comment by firstof9** [comment]
You cannot send images via email.
