### ISSUE TITLE
ISSUE: Unexpected Html format error

### ISSUE THREAD

**Issue by angrycatmeowmeow** [moralmunky/Home-Assistant-Mail-And-Packages#771]
**Describe the bug**
Error in log

**Environment (please complete the following information):**
 - OS: HAOS
 - Type of device: ODROID N2+
 - Home Assistant version: 9.4/2022.12.7
 - Hassio/Docker/Core? Core
 - Component version: 0.3.5-b20

**Logs**
This error originated from a custom integration.

Logger: custom_components.mail_and_packages.helpers
Source: custom_components/mail_and_packages/helpers.py:187
Integration: Mail and Packages (documentation, issues)
First occurred: 20:59:13 (3 occurrences)
Last logged: 21:10:04

Unexpected html format found.

**Comment by firstof9** [comment]
This is not an error.

**Comment by angrycatmeowmeow** [comment]
ok
