### ISSUE TITLE
ISSUE: everything went to unavailable

### ISSUE THREAD

**Issue by Jezza1232** [moralmunky/Home-Assistant-Mail-And-Packages#773]
**Describe the bug**
After setup it was fine for a long time now everything (all stats are now unavailable and won't come back online

**Environment (please complete the following information): virtual box 
 - OS: [HassOS]
 - Type of device: [virtual box on windows 10]
 - Home Assistant version: [2022.12.8]
 - operating system: 9.4
 - Component version: [0.3.5-b21]

**Logs**
I have download the diagnosis file ready to upload

**Screenshots**
![Screenshot_20221225_193438_Home Assistant](https://user-images.githubusercontent.com/97153995/209461757-d8bd98e4-cb0c-4500-b3a9-f5ed94a10318.jpg)

![Screenshot_20221225_193447_Home Assistant](https://user-images.githubusercontent.com/97153995/209461759-2529fa7f-9069-4601-bc16-4692f59aa8c8.jpg)

**Comment by firstof9** [comment]
Check your `home-assistant.log` file.

**Comment by Jezza1232** [comment]
Ok so the log file keeps saying timed out

**Comment by Jezza1232** [comment]
Updated the timing setting thingy from 30 seconds to 60 and this fixed it thank you
