### ISSUE TITLE
[Feature Request] add amazon.fr to amazon domains

### ISSUE THREAD

**Issue by taKi78540** [moralmunky/Home-Assistant-Mail-And-Packages#774]
Can you kindly add the support for Amazon.fr (France)?

I have just send to you an email on (firstof9@gmail.com) and attached 3 amazon emails in .eml format.

1. When the package is shipped
2. When the package arrives today
3. When the package is delivered

It would be great if you could consider my request !

**Comment by Seidel76** [comment]
Yeah ! That would be cool !

**Comment by firstof9** [comment]
Added to latest release.
