### ISSUE TITLE
Is there a plan for Amazon tracking Integration?[Feature Request] 

### ISSUE THREAD

**Issue by jatgm1** [moralmunky/Home-Assistant-Mail-And-Packages#787]
**Is your feature request related to a problem? Please describe.**
Not particularly 
NA

**Describe the solution you'd like**

A way to integrate one or multiple Amazon accounts with a way of being notified when delivered. Preferably also a way of determining how many stops are left if that is available. Also notification and a variable with a state of the delivery time window.

**Describe alternatives you've considered**

Sometimes Amazon doesn't use a TBA tracking number (tracking by Amazon?) And I can get updates for USPS ups and FedEx which is cool.

**Additional context**

**Comment by firstof9** [comment]
Amazon's already supported.

**Comment by jatgm1** [comment]
Oops. I just read supported shippers and assumed. My apologies

**Comment by firstof9** [comment]
No worries, it's on the wiki [here](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki#amazon).
