### ISSUE TITLE
ISSUE: automation issue

### ISSUE THREAD

**Issue by thisbejonas** [moralmunky/Home-Assistant-Mail-And-Packages#790]
**Describe the bug**
After amazon email is received in the watched folder, M&P will rereport a package as arrived even though it is a previous email that has already been checked .

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: Unraid VM
 - Home Assistant version: 2023.1.4
 - Hassio
 - Component version: 0.3.5-b16

**Logs**
Paste your error logs here.

**Screenshots**

**Additional context**
I have an automation that when a package has been delivered, it increases a counter from "0" to "1". This triggers another automation to let us know when coming home, that a package is on the porch. We then tell Alexa that "we got the package off the porch" and she runs a routine that resets the counter back to zero. This has been working great until a couple weeks ago. Now, for some reason, when the email box receives the email notification that a package has been delivered, it is not flagging it as read or what ever it does, so after a while, it will say another package has been delivered, even though there is not a new email for a delivery.

**Comment by firstof9** [comment]
Counters don't reset until midnight.
