### ISSUE TITLE
Mail & Packages won't Load; stuck on 0.3.4-2

### ISSUE THREAD

**Issue by vmcosco** [moralmunky/Home-Assistant-Mail-And-Packages#794]
Earlier this week I attempted to update from 0.4.4-2 to current (not sure which version it was at the time).  The update would not go through, the "circle" just kept spinning.  I did a restart to apply other updates.  On restart Mail and Packages no longer loads, I still cannot update or download.  I tried to delete the integration but I can delete via the integration menu.  Here are log entries I see:

When HA starts: http://pastie.org/p/2a1XgoV65mU6Y4EsAuZhxP
When I try to delete from integration UI: http://pastie.org/p/3jfa6wn93gtYQ4UoEeUKXB

**Comment by firstof9** [comment]
Download the latest version and put it in your `custom_components` directory

**Comment by vmcosco** [comment]
> Download the latest version and put it in your `custom_components` directory

Thanks, will give that a try after work today.  Should I delete the current folder in the directory and just replace it with the new folder?

**Comment by firstof9** [comment]
Yes that would be the best way.

**Comment by vmcosco** [comment]
This worked.  Thank you
