### ISSUE TITLE
Code Optimization

### ISSUE THREAD

**Issue by firstof9** [moralmunky/Home-Assistant-Mail-And-Packages#80]
## Proposed change

Reduce the entity count to minimal needed/required amounts

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [X] Code quality improvements to existing code or addition of tests

## Additional information

Reduce to 2 entities, one data entity and one sensor entity.

**Comment by firstof9** [comment]
@moralmunky want to give it a glance to see what I've hobbled together? lol

**Comment by moralmunky** [comment]
Sorry, the current state of the country has me busy at work. I look it over and it looks great. Haven't had a chance to upgrade yet.

**Comment by firstof9** [comment]
Put it out as a beta for people to test, likely be faster than the 0.1.x versions.

**Comment by moralmunky** [comment]
I think it will be great, though, I am getting a the following error
Looks like the self._image_nameget left out being passes to get_mails function 

`TypeError: get_mails() missing 1 required positional argument: 'image_name'`

**Comment by firstof9** [comment]
Whoops fixing now.
