### ISSUE TITLE
Email address an email account user name are 2 differnet names

### ISSUE THREAD

**Issue by bdacus01** [moralmunky/Home-Assistant-Mail-And-Packages#803]
Home Assistant 2023.3.3 Supervisor 2023.03.1 Operating System 9.5 Frontend 20230309.0 - latest
**Is your feature request related to a problem? Please describe.**
Not sure it a problem.  I have Mailfence email.

I have a email account username.  Example 
IMAP
Server : imap.mailfence.com
Email address :me@mydomain.net
Username : me@mailfence.com
Password : your password
Secure port : 993
    Security : TLS/SSL
    Authentication : normal (PLAIN or LOGIN)

**Describe the solution you'd like**
I need a place for both entries.  You find this on real IMAP clients.  

Could it be the tls from above I don't see a place for that either.
Secure port : 993
    Security : TLS/SSL
    Authentication : normal (PLAIN or LOGIN)

**Describe alternatives you've considered**
I tried with the username.  I even increased the time out to 90 seconds

Let me know if you need info.

**Comment by bdacus01** [comment]
It seems to pull in the Folders so it must be connecting.

I get all of these errors

2023-03-13 12:30:14.668 ERROR (MainThread) [frontend.js.latest.202303090] :0:0 ResizeObserver loop completed with undelivered notifications.
2023-03-13 12:30:17.114 ERROR (MainThread) [frontend.js.latest.202303090] :0:0 ResizeObserver loop completed with undelivered notifications.
2023-03-13 12:33:32.878 ERROR (MainThread) [custom_components.mail_and_packages] Timeout fetching Mail and Packages (imap.mailfence.com) data
2023-03-13 12:33:32.879 ERROR (MainThread) [custom_components.mail_and_packages] Error updating sensor data: 
2023-03-13 12:33:32.881 WARNING (MainThread) [homeassistant.config_entries] Config entry 'imap.mailfence.com' for mail_and_packages integration not ready yet: None; Retrying in background
2023-03-13 12:34:08.213 ERROR (MainThread) [custom_components.mail_and_packages] Timeout fetching Mail and Packages (imap.mailfence.com) data
2023-03-13 12:34:08.213 ERROR (MainThread) [custom_components.mail_and_packages] Error updating sensor data:

**Comment by firstof9** [comment]
[Enable debugging](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Troubleshooting#enable-debugging) so we can get more info.

**Comment by bdacus01** [comment]
I uninstalled the entire thing and re installed.  Seems ok now.  

I had a Amazon deliver today.  Where would I see that?

but here is the debug log
[home-assistant.log](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/files/10961013/home-assistant.log)

**Comment by bdacus01** [comment]
here are so before uninstall regular logs
[home-assistant_mail_and_packages_2023-03-13T17-44-27.667Z.log](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/files/10961151/home-assistant_mail_and_packages_2023-03-13T17-44-27.667Z.log)
[home-assistant_mail_and_packages_2023-03-13T17-37-55.943Z.log](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/files/10961152/home-assistant_mail_and_packages_2023-03-13T17-37-55.943Z.log)
[home-assistant_mail_and_packages_2023-03-13T14-54-37.693Z.log](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/files/10961153/home-assistant_mail_and_packages_2023-03-13T14-54-37.693Z.log)

**Comment by firstof9** [comment]
> I had a Amazon deliver today. Where would I see that?

In the debug log the amazon email says the delivery was Sunday the 12th.

**Comment by bdacus01** [comment]
Looks like it came today from ups.  Before I installed the integration.  ;) I will watch it a few days but I don't. see a bunch of errors currently.

**Comment by firstof9** [comment]
> Looks like it came today from ups.

Then you'll get a UPS delivery count rather than Amazon. Please see the [Amazon section in the wiki](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki#amazon).
