### ISSUE TITLE
ISSUE: crash when adding integration

### ISSUE THREAD

**Issue by grischard** [moralmunky/Home-Assistant-Mail-And-Packages#804]
**Describe the bug**

Home Assistant crashes when configuring the integration on a new system.

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: RPi4
 - Home Assistant version: 2023.3.3
 - Hassio/Docker/Core? Home Assistant OS 9.5
 - Component version: 0.3.10

**Logs**

GUI says "An unknown error has occured". Nothing in the HA logs. HA restarts.

**Comment by grischard** [comment]
Adding xenophile.stereo.lu by hostname crashes HA; adding it manually with the IPv4 works. I imagine that HA automatically tries to connect to the IPv6 address, which isn't working at the moment. It should fall back to IPv4, not take the whole system down.

**Comment by bdacus01** [comment]
I get you MX as mail.stereo.lu

So do you have a imap A record
Like imap.stereo.lu

if not try 
mail.stereo.lu

**Comment by firstof9** [comment]
Verify your IMAP mail settings with your provider.
