### ISSUE TITLE
ISSUE: will not log back into mail client

### ISSUE THREAD

**Issue by trentjw** [moralmunky/Home-Assistant-Mail-And-Packages#809]
**Describe the bug**
reloaded entity and it will not log onto mail client

**Environment (please complete the following information):**
 - OS: [e.g. HassOS/Raspbian/CentOS]
 - Type of device: [e.g. RPi3/NUC/Synology]
 - Home Assistant version: [e.g. 0.105.5]
 - Hassio/Docker/Core? 
 - Component version: [e.g. 0.1.2]

**Logs**
no error logs entity will not install

**Screenshots**

**Additional context**
probably just going to abandon this anyways it never has worked proper rarely catches any mail and it was hit or miss mostly miss on packages from USPS, ups and fedex spent way more time than I should of on this

**Comment by firstof9** [comment]
[Enable debugging](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Troubleshooting#enable-debugging) and check your `home-assistant.log` file for errors.

**Comment by trentjw** [comment]
> [Enable debugging](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Troubleshooting#enable-debugging) and check your `home-assistant.log` file for errors.
it does not leave anything in the log as it will not even load do to a login failure

**Comment by firstof9** [comment]
Which email provider?

**Comment by trentjw** [comment]
gmail

**Comment by firstof9** [comment]
You've setup an app password?

**Comment by trentjw** [comment]
Yes and it use to work even redid it hoping that was the problem

**Comment by firstof9** [comment]
Can't really help without logs.

**Comment by trentjw** [comment]
That's fine it never really worked very well, just going to  remove the card and forget about trying to use it to automatically control my gate

**Comment by trentjw** [comment]
interesting

**Comment by trentjw** [comment]
still a problem but no help here
