### ISSUE TITLE
Walmart sensors break config

### ISSUE THREAD

**Issue by spezzuti** [moralmunky/Home-Assistant-Mail-And-Packages#810]
Using Gmail as the email provider. Everything has been working fine, but I saw the update for Walmart sensors so I reconfigured, adding them to the list. The integration is no longer able to initialize in HA. Restarted to verify it persists after a restart. Confirmed.

Remove the Walmart sensors and verified the integration is immediately working again. Add them back, cannot initialize and everything reports unknown.

Unable to grab logs now, can add tomorrow if necessary.

**Comment by firstof9** [comment]
Ya I'll need logs, thanks!

**Comment by firstof9** [comment]
Please confirm it's fixed for you in the latest release. Thanks!

**Comment by spezzuti** [comment]
Look at that. No logs and still solved with rapid speed! Fantastic work, confirmed that sensors are added and appearing as expected. Brilliant job, thanks for that
