### ISSUE TITLE
ISSUE: USPS Mail Camera mp4 file is incomplete

### ISSUE THREAD

**Issue by justinmbrock** [moralmunky/Home-Assistant-Mail-And-Packages#819]
**Describe the bug**
I'm trying to send the mp4 file generated from the USPS Mail Camera in a Telegram message. But the mp4 doesn't show all the mail from the gif. If today's mail for example has three mail pieces the gif will show each piece for about 5 seconds, cycling through them. But the mp4 is only 5 seconds long and only displays the first piece. In the last fraction of a second the second piece is visible before the file ends.

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: RPi4 4GB
 - Home Assistant version: 2023.4.6
 - HASS.io
 - Component version: 0.3.13

**Logs**

**Screenshots**

**Additional context**

**Comment by firstof9** [comment]
fixed in `0.3.14`

**Comment by justinmbrock** [comment]
Great, thanks!
