### ISSUE TITLE
ISSUE: Using a Group Email to send delivery notifications rather than email Collecting delivery notifications

### ISSUE THREAD

**Issue by iceman73** [moralmunky/Home-Assistant-Mail-And-Packages#82]
Currently i cannot get the Module to work properly in my situation. I currently utilize a group email address to send the USPS, Fedex, and UPS delivery notifications to. This group name is different than the email address I have tied to Mail and Packages, and it never shows the mail or deliveries for the day. Is it possible that the program is checking that the mail was sent to the same account that is registered with the integration

**Environment (please complete the following information):**
 - OS: Ubuntu in Docker HASSIO
 - Type of device: [e.g. VM on Dell R710
 - Home Assistant version: 107.7
 - Hassio/Docker/Core? HASSIO in DOCKER
 - Component version: 0.1.2-1

**Logs**
No Errors in the log

**Screenshots**
N/A

**Comment by firstof9** [comment]
> Is it possible that the program is checking that the mail was sent to the same account that is registered with the integration

No it searches the folder specified for the emails with specific FROM and SUBJECTS.

**Comment by iceman73** [comment]
They I have a different issue I guess. Do i need to put the folder in quotes or anything?

**Comment by firstof9** [comment]
Give that a try especially if your folder name has spaces.

**Comment by firstof9** [comment]
Also what email provider are you using? Gmail? Yahoo?

**Comment by iceman73** [comment]
Gmail

**Comment by iceman73** [comment]
Looks like the Group Email from gmail is doing something funky with the usps mail

![image](https://user-images.githubusercontent.com/2061265/78995331-204f9100-7b10-11ea-8451-fe1eddf3a40b.png)

**Comment by iceman73** [comment]
I think I fixed it, In google domains I needed to allow the Sender from the web to be the proper reply-to. We will see on next email if this fully fixed it

**Comment by firstof9** [comment]
I assume the subjects stay intact? If so you could mod your local const.py email addresses to "delivery@yourdomain.net"

**Comment by moralmunky** [comment]
When the email is forwarded, I think you are going to have a hard time keeping the original sender (the carriers email address) as the official FROM address in the email forwarded on to your group. Especially when google is involved and SPF, DKIM, and other methods have been deployed to reduce email spoofing.

@firstof9 suggestion to modify the email addresses listed in the cont.py to your group email address that shows up in the FROM field will be your only solution.
