### ISSUE TITLE
Can't login into hotmail.com account

### ISSUE THREAD

**Issue by markaggar** [moralmunky/Home-Assistant-Mail-And-Packages#821]
Getting this message when trying to set up the integration and logging into my hotmail.com account using an app password (because I have a password-less account).

Logger: custom_components.mail_and_packages.helpers
Source: custom_components/mail_and_packages/helpers.py:125
Integration: Mail and Packages ([documentation](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages), [issues](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues))
First occurred: 3:19:35 PM (6 occurrences)
Last logged: 3:37:03 PM

Error logging into IMAP Server: b'LOGIN failed.'

However, according to account.live.com, the login seems to be successful, but it is the sync that is failing.

Protocol: IMAP
IP: 2a01:111:f400:31ba::x
Account alias:
<myaccount>@hotmail.com
Time: 7 minutes ago
Approximate location: Not available
Type: Unsuccessful sync

Protocol: IMAP
IP: 76.147.130.xxx
Account alias:
<myaccount>@hotmail.com
Time: 7 minutes ago
Approximate location: United States
Type: Unsuccessful sync

**Comment by firstof9** [comment]
Says the login failed, check your username.

**Comment by markaggar** [comment]
Username is fine (I removed it from the account.live.com log).  It's logging in, says sync was unsuccessful.

**Comment by firstof9** [comment]
You have the server set to `outlook.office365.com` ?

**Comment by markaggar** [comment]
Yes, per https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-for-outlook-com-d088b986-291d-42b8-9564-9c414e2aa040?ui=en-us&rs=en-us&ad=us

**Comment by markaggar** [comment]
Well what do you know, I created another app password and it logged in.  Sorry for the hassle!

**Comment by Nthompson096** [comment]
Sorry for bumping a dead thread, but how did you create an app password and sign into there? I've read the [azure](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Configuration-and-Email-Settings#office-365-wip) directions and I'd assume it's because my outlook has a otp password I'd need a app password.

**Comment by markaggar** [comment]
https://support.microsoft.com/en-us/account-billing/how-to-get-and-use-app-passwords-5896ed9b-4263-e681-128a-a6f2979a7944

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
