### ISSUE TITLE
ISSUE: Unable to connect GMail account in 'Devices' menu

### ISSUE THREAD

**Issue by PavelAsiyeuski** [moralmunky/Home-Assistant-Mail-And-Packages#824]
**Describe the bug**
I installed 'Mail and Packages' through HACS, then I went ahead to 'Devices' and tried to add integration to my Home Assistant. After filling up all 4 fields with correct gmail information, as well as my email address along with app password that I created for my email, it starts loading for 7-10 minutes meanwhile my whole home assistant gets frozen, unable to navigate anywhere except for my Dashboard with old values displayed. After waiting for pretty long time, I'm getting "Invalid flow specified" error on the same panel where I entered all 4 values with credentials etc.  

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: Windows
 - Home Assistant version: 10.1
 - Hassio
 - Component version: Unknown

**Logs**
Enabled debug mode, no logs found in home-assistant.log

**Screenshots**
![M Perror](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/62081169/dcee37e7-57a2-429a-be3d-f150ff4a5ca9)

**Additional context**
Enabled IMAP in Google account settings. Using Windows machine, under which I'm running VM Virtual box - HassOS. Connection to internet is stable.

**Comment by firstof9** [comment]
Seems like a bad download, uninstall/reinstall from HACS.

**Comment by trentjw** [comment]
same problem been ongoing for a while, author is of no help keeps saying wants log but it does not get to the point of writing a log so he does not help pretty convenient way of getting out of helping
