### ISSUE TITLE
ISSUE: Integration "Retrying setup: None"

### ISSUE THREAD

**Issue by brylee123** [moralmunky/Home-Assistant-Mail-And-Packages#826]
**Describe the bug**
All the sensors are unavailable.

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: RPi4-b
 - Home Assistant version: 2023.4.6
 - Hassio
 - Component version: 0.3.14

**Logs**
This error originated from a custom integration.

Logger: custom_components.mail_and_packages
Source: custom_components/mail_and_packages/__init__.py:103
Integration: Mail and Packages (documentation, issues)
First occurred: 11:30:12 AM (9 occurrences)
Last logged: 11:40:57 AM

============================================
This error originated from a custom integration.
Error updating sensor data:

Logger: custom_components.mail_and_packages
Source: helpers/update_coordinator.py:226
Integration: Mail and Packages (documentation, issues)
First occurred: 11:30:12 AM (8 occurrences)
Last logged: 11:39:06 AM

Timeout fetching Mail and Packages (imap.gmail.com) data

**Screenshots**
![image](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/22011502/ef26f432-5df2-47f7-996d-1817ef4ba9db)

**Additional context**
Please add emails in plain/text format if possible and applicable.

This was working perfectly fine until today. I had no change in my gmail account or password settings.

**Comment by firstof9** [comment]
Need logs from your `home-assistant.log` file.

**Comment by brylee123** [comment]
> > 2023-05-19 11:32:25.489 ERROR (MainThread) [custom_components.mail_and_packages] Timeout fetching Mail and Packages (imap.gmail.com) data
> 
> There's your answer, increase the timeout setting.

Thank you! That did the trick. I'm assuming since I didn't receive mail today (or a USPS informed delivery email), it was searching for a while. I increased timeout from 30 to 120. Thank you again for a speedy response!

**Comment by firstof9** [comment]
Basically the more shippers enabled the longer the email check takes.
