### ISSUE TITLE
ISSUE: Packages for USPS do not get counted

### ISSUE THREAD

**Issue by JvdMaat** [moralmunky/Home-Assistant-Mail-And-Packages#827]
**Describe the bug**
The integration is working for mail from USPS, but packages aren't being recognized.

**Environment (please complete the following information):**
 - OS: docker
 - Type of device: x86
 - Home Assistant version: 2022.05
 - Hassio/Docker/Core? Docker
 - Component version: 0.3.14

**Screenshots**
![image](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/90044149/06632518-a4c4-4a90-b6de-dcd1d0d0b3c0)
![image](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/90044149/5be3d8f2-1b9d-4e4e-8bb7-fa3b605dfebc)

**Additional context**
I can send you the USPS email directly, just don't want to publish it here.

**Comment by firstof9** [comment]
Packages don't get counted from the informed delivery emails, they get counted be the emails they send the day of delivery.

**Comment by theOrakle** [comment]
> Parsing the actual delivery emails is far better.

I guess I don't understand...  If I have a wife and 2 kids and the package could be sent to any of the other 3 at the same address (but using their email), you are stating that it is better to parse the one email address for packages that are just for that user destination over the address destination (an aggregate of users).  In this scenario I miss all their packages.

I do understand the conundrum the software is in, as the package to the informed user may conflict with the details in the package information from informed delivery (address) and there is no way to couple the counts  (removing duplicates) between the 2.

Are you saying that the informed delivery info is just not as good of a data source compared to the direct email to the user?  I have been using your integration for a while now but just started informed delivery and I'm trying to figure out if I need some forwarding magic on the mail side to capture the "whole house".

**Comment by firstof9** [comment]
Informed delivery will send you an email for all packages to your address no matter who's name is on them.

**Comment by skewll** [comment]
> Informed delivery will send you an email for all packages to your address no matter who's name is on them.

Hi. I don't understand either. The mail one the informed delivery email is almost always junk mail or for the wrong address. No big deal. But I only get informed delivery emails for packages, no day before email. So the packages in Informed delivery, regardless of whom the recipient is, is important for me to count, and can only come from the informed delivery email, as that's the only email I get from usps regarding emails. What can be don't to get the sensor to add the packages from informed delivery email? Or how can I get this other email notication about deliveries from USPS that you appear to be referencing?  Thanks!

**Comment by skewll** [comment]
I get more emails now after following all directions in your repository for informed delivery and turning on all the notifications from the settings page on the USPS website. I'm confident it will work as I was expecting now. Thanks for making this!!
[Screenshot_20240320-203031_Chrome.jpg](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/73421224/2e8f5f1b-92d4-4f83-92cd-216e097073e3)
