### ISSUE TITLE
Logo/Icon needed for integration

### ISSUE THREAD

**Issue by rpitera** [moralmunky/Home-Assistant-Mail-And-Packages#83]
Now that 0.108.x supports integration logos/icons would these work for you until someone comes up with something better?

Logo -

![m pLogo@2x](https://user-images.githubusercontent.com/19910294/78996806-5f331600-7b13-11ea-9059-a035a2c27995.png)

Icon -

![icon](https://user-images.githubusercontent.com/19910294/78996809-61957000-7b13-11ea-95b2-fa5a717016eb.png)

**Comment by firstof9** [comment]
Looks good to me, @moralmunky what do you think?

**Comment by rpitera** [comment]
Let me know if you guys approve it and I'll put in a pull request to the HA Brands repo so it shows up in Integrations.

**Comment by moralmunky** [comment]
Sure, it's a good starting point.

**Comment by rpitera** [comment]
I can change anything you don't like; doing so now would be easier than doing it after I upload to the brands registry.

**Comment by firstof9** [comment]
Maybe something simpler eh?

Logo:
![cover](https://user-images.githubusercontent.com/1105672/80117389-fd73a280-853b-11ea-958f-ac647ee9047e.png)

Icon:
![profile](https://user-images.githubusercontent.com/1105672/80117423-06647400-853c-11ea-8af5-dd7e27249397.png)

**Comment by firstof9** [comment]
Alternate:

![cover](https://user-images.githubusercontent.com/1105672/80117700-580cfe80-853c-11ea-9cd9-12302d68bec5.png)

![profile](https://user-images.githubusercontent.com/1105672/80117715-5c391c00-853c-11ea-8e25-40de67283e6a.png)

**Comment by firstof9** [comment]
Could even mix the 2, I'll look into that later today

**Comment by rpitera** [comment]
I think I like the alternate, but I would add a line art package in the same style.  Then it would be perfect.

**Comment by firstof9** [comment]
Maybe combo the package and mail to a single logo?
Like so:

![cover](https://user-images.githubusercontent.com/1105672/80128358-62ce9000-854a-11ea-8fa7-0a5824d65a2c.png)

![profile](https://user-images.githubusercontent.com/1105672/80128370-66621700-854a-11ea-9a5c-a7a65a2ddf8a.png)

**Comment by firstof9** [comment]
@rpitera I have these in SVG format if you'd like I can pass them to you.

**Comment by firstof9** [comment]
Found a line art packages... 
![cover](https://user-images.githubusercontent.com/1105672/80160370-56662980-8582-11ea-90ea-6b6c8fc04a4e.png)

**Comment by rpitera** [comment]
> @rpitera I have these in SVG format if you'd like I can pass them to you.

No need.  This one is it for me, personally.  I love it!

![80128358-62ce9000-854a-11ea-8fa7-0a5824d65a2c](https://user-images.githubusercontent.com/19910294/80213100-ab4b8380-8606-11ea-8d03-a5573c68533a.png)

**Comment by firstof9** [comment]
What do you think @moralmunky ?

**Comment by moralmunky** [comment]
Hey sorry, work has kept me busy with everything going on. I've enjoyed dhow this has progressed from the first version. What is the source of the art? Is there licensing requirements? The box perspective seems a bit wonky. If possible, I think it is the top corner that needs to be brought down a bit. It's like we are seeing too much of the top of the box compared to the front and side. It creates an optical illusion that the side are not straight. 

It is possible to find a font that is not as thick? Looking for more balance between the art and the text. Thickness and the relation in size, the package may be a bit too small.

**Comment by firstof9** [comment]
I used the logo generator from namecheap to generate it. Not much can be done about the icon it self. I can see if there's something a little more symetrical.

**Comment by firstof9** [comment]
Found one more symmetrical, and adjusted the font:

![cover](https://user-images.githubusercontent.com/1105672/80427089-df8ba200-889b-11ea-8b62-56903cb6eb1b.png)

and:

![profile](https://user-images.githubusercontent.com/1105672/80427103-e4505600-889b-11ea-9140-cf055edae291.png)

**Comment by rpitera** [comment]
The only issue with this icon is that it loses the representation of 'mail'.  If the right facing panel had the triangular shape of envelope flaps, I'd be much happier with it.  I could take a stab at it tomorrow.

**Comment by firstof9** [comment]
Here's the SVG to make things easier.
[isolated-monochrome-black.zip](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/files/4542519/isolated-monochrome-black.zip)

**Comment by rpitera** [comment]
Thanks!  I'll see what I can do.  I used to have a PC with Illustrator on it, but that died a while back.  I'll have to grab a FOSS alternative so we can keep it in SVG.  That way it can be used at any size.

**Comment by firstof9** [comment]
I use inkscape when I need to play with SVG files.

**Comment by rpitera** [comment]
I'm afraid I jumped the gun on this one.  I just found out from Ludeeus that while the Integrations section shows placeholders for logos, there's currently no provision for displaying them from Custom Components, only from brand integrations.

I'll continue to work on this as time allows in hopes that they will put in a PR to allow Custom Components to display branding (since other authors have asked as well) but for now, this isn't a high priority since it isn't currently supported anyway.

I'm really sorry for any confusion I might have caused by my misunderstanding.

**Comment by firstof9** [comment]
Not a problem, it sounds like they'll be adding it in the near future, so we are at least ahead of the curve.

**Comment by ttaidapos** [comment]
I'm suggesting the color blue from previous examples vs. brown. I get the significance of brown but doesn't look that great with all other icons. Just my. 02. :)

**Comment by firstof9** [comment]
@rpitera Looks like HACS and a few other integrations icons are getting added. Is there a repo to do a PR against for icons?

**Comment by rpitera** [comment]
Yes: 
https://github.com/home-assistant/brands

Sorry I haven't had a chance to work on it; I've been struggling with my system and then the whole Wink thing blew up and I was migrating my lock.  Things are good now though so I'll try to take a shot at it tomorrow.

**Comment by moralmunky** [comment]
Throwing this version in here. Fixed the perspective on the box and flipped it so it's pointing toward the title. Also read there are icons too.

<img width="744" alt="Screen Shot 2020-05-11 at 7 50 44 PM" src="https://user-images.githubusercontent.com/19318945/81623190-e00a5980-93c0-11ea-8d55-43ce7c9a580c.png">

**Comment by firstof9** [comment]
I do like the blue, gives it a USPS feel.

**Comment by ttaidapos** [comment]
Stunning!!!

**Comment by moralmunky** [comment]
Here you go!

https://shared-assets.adobe.com/link/89da6848-be3b-4b19-6404-31da2d20a48e

**Comment by firstof9** [comment]
The PRs are in, quite a few hoops to jump but they're done.
