### ISSUE TITLE
ISSUE: .mp4 not being created correctly

### ISSUE THREAD

**Issue by jes1417** [moralmunky/Home-Assistant-Mail-And-Packages#830]
**Describe the bug**
Before the change of https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/pull/820 I was getting mp4s in my android notifications but now nothing is showing up. If I try to view the file it's just a black screen for the entire video. 

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: Bare metal server
 - Home Assistant version: 2023.6.0b5
 - Hassio/Docker/Core? Hassio
 - Component version: latest

**Logs**
No log errors

**Screenshots**

**Additional context**
https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/38092747/8beb2d3e-4d04-4b35-8640-99c890a82c81

**Comment by firstof9** [comment]
Fixed in #831
