### ISSUE TITLE
[Feature Request] BuildingLink

### ISSUE THREAD

**Issue by raccettura** [moralmunky/Home-Assistant-Mail-And-Packages#834]
One of the more popular services for buildings with a package room is [BuildingLink](https://www.buildinglink.io/) which sends emails when packages arrive.

They seem to always come from:  notify@buildinglink.com

With the subject: `You have a(n) <shipping provider> package` 

Example subjects:
> You have an Amazon delivery
> You have a UPS package
> You have a FedEx delivery at the front desk
> You have an envelope at the front desk   <--- this is IMHO an edge case

Would be cool to see support.

**Comment by firstof9** [comment]
Do you not get the regular Amazon, UPS, and FedEx emails about your packages?
