### ISSUE TITLE
ISSUE: mail sent to catch-all email address doesn't get counted when recipient different than the imap username 

### ISSUE THREAD

**Issue by AskAlice** [moralmunky/Home-Assistant-Mail-And-Packages#836]
**Describe the bug**

i send my usps notifications to something like `[cityname]@[domain.name]`, then gmail filters it into a specific label which I point imap to read from. Problem is USPS mail doesn't get counted, but amazon (sent to normal email address) does.

**Environment (please complete the following information):**
 - OS: [e.g. HassOS/Raspbian/CentOS] HassOS
 - Type of device: [e.g. RPi3/NUC/Synology] proxmox on amd64 desktop
 - Home Assistant version: 
```
Home Assistant 2023.6.1
Supervisor 2023.06.2
Operating System 10.2
Frontend 20230608.0 - latest
```
 - Component version: 0.3.16

**Logs**
Paste your error logs here.

**Screenshots**

![image](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/1855905/1be70144-b452-48c8-b63c-c2fce499882f)
![image](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/1855905/f504cff1-f465-485b-8c76-3fa5a4ce0517)
![image](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/1855905/60074509-f398-4da3-9088-b78106d85d49)
**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment]
Looks like it's working just fine. The integration only counts the current day's deliveries.
