### ISSUE TITLE
0 Package are show

### ISSUE THREAD

**Issue by Kathou99** [moralmunky/Home-Assistant-Mail-And-Packages#841]
### Discussed in https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/discussions/840

<div type='discussions-op-text'>

<sup>Originally posted by **Kathou99** July 30, 2023</sup>
Hi,

Almost all my email is in french, and the mail intégration cannot find any of theses email. I got 0 for all the packages.The delivery mail in a folder in gmail so I have setup this folder in the config of the mail integration but still nothigs has been show. I have a couple of intelcom email in this folder and amazon's ones.

Did is because my mail is in french?

In the log I see he found the amazon mail.

And too I have to set to 60sec the time mount delay

Thank</div>

**Comment by scantagithub** [comment]
Hi All, I have the same problem. Where I can find the log?

**Comment by scantagithub** [comment]
AH, sorry, I'm Italian so I think the const it's already configured.
I configure to watch entire gmail so i put INBOX in the configuration.

**Comment by scantagithub** [comment]
This is the sensor: 0 package's

![image](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/141415270/002cdaff-e4dc-444c-84ad-71e648e73e5a)

If I click on a sensor, I can see the amazon order so I assume the system can read something from the emails
![image](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/141415270/6c96fb88-4f1a-45cf-b9ac-ad2ff56a8142)


This is the email that I have received:
![image](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/141415270/28a54c74-85bc-43bd-b001-63031616df66)

**Comment by scantagithub** [comment]
> Normally, you can find in the debug log,
> 
> So go to integrations and activate the debug log and dowloading it

![image](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/141415270/fa286307-1873-4b38-89a8-5f14c30707c5)
THis is correct?

**Comment by scantagithub** [comment]
THis is one piece of log file, the system find 3 order so 3 email but the sensor email and packages is 0

![image](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/141415270/ce4dc6c5-2c26-4c4a-a851-787b73c941ca)

**Comment by firstof9** [comment]
Unless it's the date of delivery the count stays 0

**Comment by scantagithub** [comment]
Ah so all the sensors are populated only on the delivery date?
I thought that the PACKAGE sensor indicated that there is an arriving package, the DELIVERING sensor that the package is being delivered and therefore populates on the day of delivery and the DELIVERED sensor received the delivery email from Amazon. Am I doing something wrong?

**Comment by scantagithub** [comment]
I found this in the log:

![image](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/141415270/f80f89ca-e9c9-4cc2-85ee-b94c4683f1ca)

**Comment by scantagithub** [comment]
Can I have support please?

**Comment by firstof9** [comment]
> I thought that the PACKAGE sensor indicated that there is an arriving package, the DELIVERING sensor that the package is being delivered and therefore populates on the day of delivery and the DELIVERED sensor received the delivery email from Amazon. Am I doing something wrong?

Amazon only has 2 sensors, delivering and delivered. 

Delivering means it should be out for delivery to your home or amazon drop-box based on the date in the email (mostly accurate).

**Comment by firstof9** [comment]
> I found this in the log:

Please never post pictures of logs, just copy and paste it makes it a lot easier to implement changes.

**Comment by scantagithub** [comment]
HI
amazon sends many emails for an order:
- Order placed
- Order shipped
- order delivered
So I thought that the PACKAGE sensor read the shipped order emails, the DELIVERING sensor read the delivered emails and the DELIVERED sensor read the delivered emails. Does it work differently?

**Comment by firstof9** [comment]
> * So I thought that the PACKAGE sensor read the shipped order emails, the DELIVERING sensor read the delivered emails and the DELIVERED sensor read the delivered emails. Does it work differently?

https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki#how-it-works

**Comment by LordNex** [comment]
Apparently it's broken and he has decided not to fix it. I'm in the US and have the same issue and was just referred to the wiki and told to basically go fuck myself.

**Comment by LordNex** [comment]
Duplicate #867

**Comment by PsY4** [comment]
Hey o/
You could just use the [dateparser package](https://dateparser.readthedocs.io/en/latest/), it reads perfectly 200 language locales plus numerous formats in a language agnostic fashion, and work perfectly with the french dates in my Amazon emails.
Maybe a simple `dateobj = dateparser.parse(arrive_date).date()` could replace the full `amazon_date_lang` function

**Comment by firstof9** [comment]
> Maybe a simple `dateobj = dateparser.parse(arrive_date).date()` could replace the full `amazon_date_lang` function

Thanks for the suggestion, I'll take a look, cheers!

**Comment by firstof9** [comment]
This should be working in `0.3.20` please let me know if it doesn't solve your issue.

**Comment by Kathou99** [comment]
Hi, I have updated it and I don't see it , has far I work he count still 0, I am on the 0.3.21

**Comment by firstof9** [comment]
You won't have a count until the day of the package delivery, you can also check the debug logs to make sure it's catching the date properly as well.
