### ISSUE TITLE
ISSUE: USPS Packages In Transit Show 0

### ISSUE THREAD

**Issue by teek541** [moralmunky/Home-Assistant-Mail-And-Packages#843]
**Describe the bug**
USPS Packages aren't tracked

**Environment (please complete the following information):**
 - HassOS
 - Home Assistant Yellow
 - 2023.8.3
 - Hassio
 - 0.3.17

**Logs**
Can't get them right this second.

First of all, I think this is the coolest integration probably on HA and thank you for making it.

Here's what's going on.
I got my USPS Informed Delivery.  My mail pieces show up, however, I have a package in route to my house currently expected to be delivered this weekend.  However, the "Mail Packages in Transit" show 0 as does the USPS Packages first number.  It's showing 0>0>0.   The package shows at the bottom of the informed delivery email.

**Comment by firstof9** [comment]
In transit means "out for delivery".

**Comment by teek541** [comment]
There are 3 slots on your dashboard.

_>_>_

I thought it was (In Transit AKA shipped to your house) > (Out for Delivery) > (Delivered)

Is that not the case?

**Comment by firstof9** [comment]
The "In Transit" sensor is a full count of all packages out for delivery today.

**Comment by teek541** [comment]
I may have it wrong, sorry.  There are 3 sensors:

sensor.mail_usps_packages
sensor.mail_usps_delivering
sensor.mail_usps_delivered

Shouldn't the "packages" be the number of packages shipped to your house?  That sensor is showing 0.

**Comment by firstof9** [comment]
"packages" is the total amount of packages, that's delivering + delivered

**Comment by teek541** [comment]
So delivering should adjust along with delivered?  When I've looking in the past my sensors would read:

sensor.mail_usps_packages=0
sensor.mail_usps_delivering=1
sensor.mail_usps_delivered=1

At the end of the day when I had 1 package being delivered that day.
