### ISSUE TITLE
ISSUE: keeps showing wanting to update even though it is not installed

### ISSUE THREAD

**Issue by trentjw** [moralmunky/Home-Assistant-Mail-And-Packages#847]
**Describe the bug**

**Environment (please complete the following information):**
 - OS: [e.g. HassOS/Raspbian/CentOS] hassOS
 - Type of device: [e.g. RPi3/NUC/Synology] PC
 - Home Assistant version: [e.g. 0.105.5] latest
 - Hassio/Docker/Core?  hassio
 - Component version: [e.g. 0.1.2]

**Logs**
Paste your error logs here.

**Screenshots**
![image](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/12220533/ed3719fd-6f4a-407f-bb00-d50a5b285d90)

won't fully remove from my system it quit working a while back so I gave up as there was no help here just want this crap off my system

**Additional context**
Add any other context about the problem here. Deleted all the folders I could find that had mail and packages in the name
Please add emails in plain/text format if possible and applicable.

**Comment by trentjw** [comment]
Thought this was removed from my home assistant a while ago but it keeps persisting https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues/809

**Comment by firstof9** [comment]
this is a HACS bug

**Comment by trentjw** [comment]
> this is a HACS bug

Interesting none of the other integrations I removed stay persistent on updating

**Comment by trentjw** [comment]
not stale and still persistent
