### ISSUE TITLE
ISSUE: Will not connect to the mail server

### ISSUE THREAD

**Issue by benmartucci** [moralmunky/Home-Assistant-Mail-And-Packages#848]
**Describe the bug**

**Environment (please complete the following information):**
 - OS: [e.g. HassOS/Raspbian/CentOS]
 - Type of device: [e.g. RPi3/NUC/Synology]
 - Home Assistant version: [e.g. 0.105.5]
 - Hassio/Docker/Core? 
 - Component version: [e.g. 0.1.2]

**Logs**
Paste your error logs here.
This error originated from a custom integration.

Logger: custom_components.mail_and_packages.helpers
Source: custom_components/mail_and_packages/helpers.py:118
Integration: Mail and Packages (documentation, issues)
First occurred: 9:50:45 PM (2 occurrences)
Last logged: 9:50:56 PM

Error connecting into IMAP Server: [Errno -2] Name does not resolve
**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by benmartucci** [comment]
OS: HASos
Type of device: Odroid N2 HA blue
Home Assistant version: 2023.9.2
Hassio/Docker/Core? Core
Component version: 0.3.18

**Comment by djripcord** [comment]
> Error connecting into IMAP Server: [Errno -2] Name does not resolve

This does not seem to indicate a bug. It screams DNS config issue to me. I also cannot replicate this on my end, as my installation resolves host names fine.

> **Describe the bug**
> A clear and concise description of what the bug is. 

Also, don't forget to fill in this section

**Comment by firstof9** [comment]
`Error connecting into IMAP Server: [Errno -2] Name does not resolve`

This is a DNS issue, not an issue with the integration as @djripcord stated.

**Comment by kylewilliams321** [comment]
FWIW I'm also having issues and use Google.  Just recently it stopped working and so Ive been trying to troubleshoot. I set up new app password and everything and no success.  Will continue troubleshooting but wanted to comment for others in case I find a solution or if someone else already has one. Thanks.

**Comment by firstof9** [comment]
This integration does not send email.

**Comment by cjramseyer** [comment]
> FWIW I'm also having issues and use Google. Just recently it stopped working and so Ive been trying to troubleshoot. I set up new app password and everything and no success. Will continue troubleshooting but wanted to comment for others in case I find a solution or if someone else already has one. Thanks.

Google (for security) doesn't support app password anymore.  I am actually having the same problem, since this puglin doesn't support authentication using a google account.
