### ISSUE TITLE
ISSUE: Gmail no longer works with Google removal of "less secure apps" option.

### ISSUE THREAD

**Issue by pig0r** [moralmunky/Home-Assistant-Mail-And-Packages#849]
**Describe the bug**
Google has removed the option to allow "less secure apps",  see below:
https://support.google.com/accounts/answer/6010255?hl=en

This results in the integration fully not working with Gmail, even after having created an app password.

**Environment (please complete the following information):**
 - OS: Any
 - Type of device: Any
 - Home Assistant version: Latest
 - Component version: Latest

I don't feel that any logs or additional context are required here.

**Comment by firstof9** [comment]
App passwords should still work, what is the error you are getting?

**Comment by pig0r** [comment]
IMAP Server: [Errno -2] Name does not resolve

**Comment by firstof9** [comment]
This is a DNS issue on your network, not a password issue.

**Comment by pig0r** [comment]
imap.google.com is added fine, and the default port (993) is correct.   Do I need to install the IMAP integration first, or something?

I can't imagine how DNS would be screwed up, it's just bone stock HA OS running on a raspi 4.

**Comment by pig0r** [comment]
This can be closed out or deleted, Turned out to be an issue with my phone not receiving google "was this you?" messages to approve the app password.
