### ISSUE TITLE
Feature Request:  Optimize for FedEx SmartPost and UPS SurePost

### ISSUE THREAD

**Issue by jccshmny** [moralmunky/Home-Assistant-Mail-And-Packages#85]
When a SmartPost or SurePost packages is out for delivery, I get a package notification for FedEx/UPS and USPS.  I would like to only receive one notification for USPS (since they are the ones actually delivering it) on delivery day if possible.

**Comment by moralmunky** [comment]
Can you provide details on what information is provided in the notifications to make the connection that they are the same delivery? Do they both provided notifications of the out for delivery and delivered status?

It may be easier to ignore one over the other depending on the subject lines or content of the emails.

**Comment by jccshmny** [comment]
Yes, they both provide updates for out for delivery and delivered statuses for the same package. 
Within the relevant emails, there is (this is direct copy/paste from the email): 

SERVICE TYPE |   | FedEx SmartPost

UPS Service: | UPS SurePost

This isn't one size fits all, though.  UPS will deliver SurePost packages directly to you if you have another Ground or Air delivery that same day.  Also, the delivered emails from UPS may contain multiple packages and SurePost could be one of them.

**Comment by moralmunky** [comment]
@jccshmny Is there anything in the email content that identifies the package being delivered is the same? Same tracking number or something?

Having screen shots or copying and pasting the email from address, subject, and body would be helpful. Remove personal information before posting.

**Comment by jccshmny** [comment]
@moralmunky Yes, they have some information I think you can use.  Here is an example from FedEx SmartPost.  I happen to be getting one today.  The tracking numbers do not match exactly.  The USPS one is prefixed with 92.

FedEx Email
Subject:  FedEx Shipment <Tracking Number>: Your package is scheduled for delivery today
![image](https://user-images.githubusercontent.com/39075458/84148245-b464a880-aa2c-11ea-997b-3276aa72bcc7.png)

USPS Email
Subject:  USPS® Expected Delivery on Tuesday, June 9, 2020 Between 10:00am and 2:00pm <Tracking Number>
![image](https://user-images.githubusercontent.com/39075458/84148348-dd853900-aa2c-11ea-93a1-0cff4051fe72.png)

**Comment by moralmunky** [comment]
This shipping method starts with FedEx and get delivered by USPS? Have they ever started with UPS or DHL?

**Comment by jccshmny** [comment]
I am not familiar with DHL.  UPS does this as well.  It is called "UPS SurePost".

**Comment by firstof9** [comment]
The FedEx SmartPost tracking number and the USPS tracking number line up USPS just adds 92 to the start of the tracking number

**Comment by firstof9** [comment]
Since there is no real way to determine the final delivering carrier, I don't think we'd be able to account for the anomoly that is SurePost/SmartPost.
