### ISSUE TITLE
ISSUE: Uninstalled a long time ago and still getting updates 

### ISSUE THREAD

**Issue by trentjw** [moralmunky/Home-Assistant-Mail-And-Packages#856]
**Describe the bug**
persistent update after uninstalled even after fully redoing Home assistant
going to report this as spam if not corrected 

**Environment (please complete the following information):**
 - OS: [e.g. HassOS/Raspbian/CentOS]
 - Type of device: [e.g. RPi3/NUC/Synology]
 - Home Assistant version: [e.g. 0.105.5]
 - Hassio/Docker/Core? 
 - Component version: [e.g. 0.1.2]

**Logs**
Paste your error logs here.

**Screenshots**
![image](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/12220533/aa7b4847-1ee9-466c-90e9-5ef438918a0a)

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment]
This is an issue with HACS, not this integration.

**Comment by trentjw** [comment]
> This is an issue with HACS, not this integration.

Easy enough to blame something else, yet none of my other hacs integrations has this issue it's amazing that this is the only one that found this bug in have

**Comment by firstof9** [comment]
The entity in your screen shot is generated and controlled by HACS, it has absolutely nothing to do with this integration.

**Comment by trentjw** [comment]
Yup typical blame something else and close the ticket without fixing it, it's your integration in the screen shot and it's obvious that it is not sending HACs the data that it is uninstalled, but lot easier to claim HACs has a bug, it's amazing that this integration is the only one that found that so called bug

**Comment by firstof9** [comment]
You should go research how HACS works and how that entity is created before assuming things.

**Comment by trentjw** [comment]
Maybe you should, so you can have a working integration that can do a clean uninstall by sending the data needed to remove it
