### ISSUE TITLE
[Feature Request] Support for DHL Packstation

### ISSUE THREAD

**Issue by fwmarcel** [moralmunky/Home-Assistant-Mail-And-Packages#861]
**Is your feature request related to a problem? Please describe.**
In Germany, DHL sets up so-called Packstations in many locations. Parcels can also be delivered to these stations. It would be great if this integration supports them.

**Describe the solution you'd like**
I would be happy if these mails are evaluated as well. 
One idea would be either to show them as delivered.
The other idea would be to display them as an extra sensor. Comparable with the Amazon Hub sensor.

If more information is needed, let me know.
Thanks for the effort with the development of the integration.

**Comment by firstof9** [comment]
If you have the subject and from email addresses you can submit a PR on the `dev` branch to add it as a new sensor by adding a few lines to the `consts.py` file.
