### ISSUE TITLE
ISSUE: Amazon Packages or Packages in General not showing up in transit

### ISSUE THREAD

**Issue by LordNex** [moralmunky/Home-Assistant-Mail-And-Packages#867]
**Describe the bug**
Several times I've purchased things online with Amazon and others. I also have USPS scanned mail goto the same mailbox. But I can look at the tracking numbers and they are in transit but nothing of those sensors ever change. Only the day it's actually delivered does it actually show anything. Seeing how many sensors there are that, let's use Amazon for an example, is obviously going through their transit system. But does not show up in those sensors. 

**Environment (please complete the following information):**
 - OS: HAOS running on a VMWare image
 - Type of device: Dell PowerEdge R620 with 40 3ghz processor cores and 256 gigs of ram
 - Home Assistant version: 2023.12.1
 - OVA in VMWare ESXi 7.0.3 with a customized Dell Image.   
 - Component version: [e.g. Latest nonbeta ]

**Logs**
Paste your error logs here.

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment]
Please [review the wiki](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki#how-it-works).

**Comment by LordNex** [comment]
So your basically saying is that the Amazon component is broken and your not going to fix it? I've read the wiki and have everything setup fine. I just had a delivery an hour ago from Amazon with accompanying emails. I'm using the correct app password and I've tested it outside of your integration to verify I had it set right. If you're not going to fix it or make it do what it should be doing then you should remove those sensors from your integration. Telling me to review something I already have in depth and tested is somewhat insulting and just assholeish. If you want to be that way I'll be happy to unstar, leave bad comments regarding the lack of ability with the most essential part of the component which is Amazon the largest shipping chain in the world.

**Comment by LordNex** [comment]
Boy I sure found a lot of other people that have the same issue. Don't just assume everyone doesn't RTFM

**Comment by Pr0mises** [comment]
@LordNex what's even your problem? Stop demanding, if you want something to be fixed, contribute and make a pull request

**Comment by LordNex** [comment]
If I wanted to build one myself I would. The fact that he blew me off and just expected I didn't RTFM pisses me off. Especially when I find a multitude of similar people with the same dam issue. He build the dam thing. He can fix it because it's never worked in the first place. He even says in one post that he's just been lazy and it needs refactored. I would have been cool with that, he could have just linked my ticket with the others. Instead he pissed off a long time user and supporter. So yea I think I have a right to be a little pissed off @Pr0mises

**Comment by firstof9** [comment]
> Only the day it's actually delivered does it actually show anything.

As stated in the wiki this is by design, the day of delivery you get the email stating it's out for delivery (in transit).

> let's use Amazon for an example, is obviously going through their transit system. But does not show up in those sensors.

Again, as stated in the wiki, by design as Amazon does contract out their deliveries as well.

**Comment by Pr0mises** [comment]
@LordNex Firstly you have no right to demand anything or shitpost other issues. Second of all, moralmunky build it. @firstof9 is nice enough to fix things and not letting this integration die. If you send firstof9 money that's fine but if so it was for the current build not further problems. It's overall an open source project where volunteers build and fix things in their free time. Contribute to it or stop using it.

**Comment by LordNex** [comment]
> @LordNex Firstly you have no right to demand anything or shitpost other issues. Second of all, moralmunky build it. @firstof9 is nice enough to fix things and not letting this integration die. If you send firstof9 money that's fine but if so it was for the current build not further problems. It's overall an open source project where volunteers build and fix things in their free time. Contribute to it or stop using it.

Actually @Pr0mises I can say and do whatever I fucking please. It's a way of life in my country. I don't care who maintains this. I'm a network person. I make sure your shit stays together. Making a crappy email scrapper and then blaming me thinking I haven't read and worked on this myself if asinine. Fuck you, fuck you, your cool, and fuck you im out. I'll have fun burning your network to the ground. Time for some Kali Linux and metasploit if you want to make a fucking issue. You know like the old saying before you were born more than likely "reach out and touch someone" 🖕🏻

**Comment by Pr0mises** [comment]
@LordNex have fun doing I'll wait LuL

**Comment by LordNex** [comment]
> @LordNex have fun doing it, I'll wait LuL

Lookie lookie who found a cookie. Tisk tisk you take to much risk. You put it all in your code you dumb motherfucker. 

This is not the day to piss me off and you really better know who your fucking with you you'll be at the wrong end of a laser sight. I hate this time of fucking year and you're pushing the wrong fucking buttons. Shut up before you become a statistic and @Pr0mises of Blow Jobs
