### ISSUE TITLE
ISSUE: Update Stopped Functions

### ISSUE THREAD

**Issue by gdreelin** [moralmunky/Home-Assistant-Mail-And-Packages#87]
After the current update to  0.1.3 stopped all functions of the sensors. I get nothing but "unavailable" on all of them. I did a few reboots to check and I have a current USPS email in the inbox with mail and packages being delivered so it should show up like it has.  For the most part USPS worked great until the update. UPS / FedEx seems to be touch and go on detection from the services they provide. Some days it works and some days its does not detect packages. Not sure if the sensors is detecting the subject line from those two or not.

**Comment by firstof9** [comment]
There were breaking changes posted with the update:

**Breaking changes
You will need to reconfigure the integration to get the sensors to reload after upgrading.**

Click the integration, then click the cog in the upper right corner, and go thru the steps.

**Comment by gdreelin** [comment]
Ok thank you for the help

**Comment by codypet** [comment]
I get this error when I go through the steps to reconfigure.  Any ideas why?
![image](https://user-images.githubusercontent.com/17790157/79262351-2a9ac380-7e5f-11ea-9ccf-feff07e36eae.png)

**Comment by gdreelin** [comment]
You do have to put in a time for it to work. Although I am still getting "unavailable" even after doing the full setup. I created a box for all shipping information to go into and pointed it to that on page 2 of the setup. Rebooted and still nothing.

**Comment by firstof9** [comment]
Check to see if they perhaps got made into "_2" sensors. ie: ```sensor.mail_updated_2```

**Comment by firstof9** [comment]
@codypet 0 isn't a valid scan time, try 5 at a minimum.

**Comment by codypet** [comment]
The 5 minutes and the random image filename checkbox did the trick.

**Comment by gdreelin** [comment]
> 
> 
> Check to see if they perhaps got made into "_2" sensors. ie: `sensor.mail_updated_2`

Thought that too but it did not just shows "unavailable" on each sensors.

**Comment by firstof9** [comment]
Are you getting errors in the log?

**Comment by gdreelin** [comment]
> 
> 
> Are you getting errors in the log?

Only thing I see is this below:

 Log Details (WARNING)

Logger: homeassistant.components.local_file.camera
Source: components/local_file/camera.py:44
Integration: local_file (documentation, issues)
First occurred: 5:38:49 PM (1 occurrences)
Last logged: 5:38:49 PM 

Could not read camera mail_usps image from file: /config/www/mail_and_packages/mail_today.gif

**Comment by firstof9** [comment]
Only thing I can recommend then would be to click the trash can icon in the upper right and re-setup the integration at this point.

**Comment by gdreelin** [comment]
Ok did that and got it to work again but the image file is not pulling up but I will check that tomorrow when a new message comes in. On a side note what is it looking for in terms of UPS & FedEx? Seems to miss those from time to time and all the emails go to the same directory.

**Comment by firstof9** [comment]
You can view the subject lines that are being searched for here:
https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/blob/master/custom_components/mail_and_packages/const.py

**Comment by gdreelin** [comment]
> 
> 
> You can view the subject lines that are being searched for here:
> https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/blob/master/custom_components/mail_and_packages/const.py

Thanks that helped a lot.
