### ISSUE TITLE
ISSUE:  Failed setup / Issues Staying Connected

### ISSUE THREAD

**Issue by j6s33m** [moralmunky/Home-Assistant-Mail-And-Packages#879]
**Describe the bug**
Over the past week since 2024.2.5 and now on 2024.3.1, this Mail and Packages has had issues staying connected. 

When I go to reset it up, I get an error message "expected str"

**Environment (please complete the following information):**
 - Type of device: Synology running Docker
 - Home Assistant version: 2024.3.0
 - Docker
 - Component version: 0.3.22

**Logs**
[home-assistant_2024-03-07T16-07-16.886Z.log](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/files/14526960/home-assistant_2024-03-07T16-07-16.886Z.log)

**Screenshots**
![Screenshot 2024-03-07 100852](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/17929290/022008c8-1d6e-4f88-b735-dfe211013b9c)
![Screenshot 2024-03-07 100922](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/17929290/8c197200-141f-454b-9b59-64d25ca26b26)

**Comment by firstof9** [comment]
Empty the amazon forwards part also, per your log, your IMAP connection is timing out, try increasing the timeout limit.

**Comment by j6s33m** [comment]
> > Empty the amazon forwards part also, per your log, your IMAP connection is timing out, try increasing the timeout limit.
> 
> The original reporter and myself both cannot reconfigure the integration, due to the "expected str" error.

Correct. I have to change this field to be something new each time for the error to go away. There is a bug here. 

I did increase my IMAP timeout limit so we'll see if that part helps as well.

**Comment by firstof9** [comment]
If you guys would like to test replacing the `config_flow.py` file in your `/config/custom_components/mail_and_packages` directory [with this one](https://github.com/firstof9/Home-Assistant-Mail-And-Packages/blob/config-flow-fixes/custom_components/mail_and_packages/config_flow.py), I'd like to see if that resolves the configuration issue for you.

**Comment by j6s33m** [comment]
Just did this and now I receive this error:

![Screenshot 2024-03-07 160948](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/17929290/d6e60434-ce89-42ee-83a9-6dddc2197170)

**Comment by firstof9** [comment]
> Just did this and now I receive this error:
> 
> ![Screenshot 2024-03-07 160948](https://private-user-images.githubusercontent.com/17929290/311051430-d6e60434-ce89-42ee-83a9-6dddc2197170.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NTAzNTEsIm5iZiI6MTcwOTg1MDA1MSwicGF0aCI6Ii8xNzkyOTI5MC8zMTEwNTE0MzAtZDZlNjA0MzQtY2U4OS00MmVlLTgzYTktNmRkZGMyMTk3MTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDIyMjA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyZDczOGY5ZjJlZTVjYWQ1YWE4OTQzN2U5ZmI2MDJkZmIwZjkyYWFjYWFkZDE1OTdiMTAzM2FkYzIxNmUxMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x_PeInpl8VQ_VpdtF9LbopuH7esHMeO8imush3v4L8o)

Does it happen without the `""` in there too?

**Comment by j6s33m** [comment]
> > Just did this and now I receive this error:
> 
> > 
> 
> > ![Screenshot 2024-03-07 160948](https://private-user-images.githubusercontent.com/17929290/311051430-d6e60434-ce89-42ee-83a9-6dddc2197170.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NTAzNTEsIm5iZiI6MTcwOTg1MDA1MSwicGF0aCI6Ii8xNzkyOTI5MC8zMTEwNTE0MzAtZDZlNjA0MzQtY2U4OS00MmVlLTgzYTktNmRkZGMyMTk3MTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDIyMjA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyZDczOGY5ZjJlZTVjYWQ1YWE4OTQzN2U5ZmI2MDJkZmIwZjkyYWFjYWFkZDE1OTdiMTAzM2FkYzIxNmUxMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x_PeInpl8VQ_VpdtF9LbopuH7esHMeO8imush3v4L8o)
> 
> 
> 
> Does it happen without the `""` in there too?

Yes

**Comment by firstof9** [comment]
Enter `(none)` in to the forwards field and that will clear it out.
I'll add that to the text at the top of the configuration screen there.

**Comment by BrandonG777** [comment]
just had this issue come up, trying to reconfigure. uninstalled, reinstalled and still got this expected sring error until I found the (none) solution here. This should just default to "(none)" when the field is blank
