### ISSUE TITLE
[Feature Request] Add extra match for Amazon Locker

### ISSUE THREAD

**Issue by olliegg123** [moralmunky/Home-Assistant-Mail-And-Packages#881]
**Is your feature request related to a problem? Please describe.**
There seems to be a new wmail which locker emails can come from: amazonlockers@amazon.com

**Describe the solution you'd like**
Add this email address into const.py

**Describe alternatives you've considered**
Adding it in myself

**Comment by firstof9** [comment]
Is there a lock code or anything we need to parse out too?

**Comment by olliegg123** [comment]
Old format (thehub@amazon.com) : You have a package to pick up at the Amazon Locker - 301 King Garage - 703057

New Format (amazonlockers@amazon.com): Someone in your unit has a package to pick up at the Amazon Locker - 301 King Garage - 476399

The format is the same, note that the options for the beginning of the subject are still the same "You have" or "Someone in your unit has"

The subject structure looks to be the same though, so existing parsing should work.

**Comment by olliegg123** [comment]
Content of the email is also the same, but I think pulling from subject should be easiest

**Comment by firstof9** [comment]
This has been updated in `0.3.23`
