### ISSUE TITLE
ISSUE: Value should be a string

### ISSUE THREAD

**Issue by Shredder5262** [moralmunky/Home-Assistant-Mail-And-Packages#886]
The screenshot pretty much speaks for itself, I'm not doing anything special here, just checking the boxes and going through the setup and i get this error message. 

**Screenshots**![2024-04-14 13_40_03-Settings – Home Assistant - Vivaldi](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/59770346/02527edc-2f3f-4dc4-bb30-d888bc962036)

**Comment by firstof9** [comment]
Enter `(none)`

**Comment by Shredder5262** [comment]
> Enter `(none)`

Ok, that worked, thank you :)

**Comment by SirGigantor** [comment]
How does one enter "(none)" into a drop down field?

**Comment by firstof9** [comment]
It's not a drop down field.

**Comment by SirGigantor** [comment]
> It's not a drop down field.

care to explain what it is then? and more so how to enter text into it?

![2024-04-24 08_20_50-Settings – Home Assistant and 4 more pages - Personal - Microsoft​ Edge](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/16830558/aba7e5d4-2be5-443b-b051-f885fcca3dc1)

**Comment by firstof9** [comment]
That's the sensors list, you need the box below it.

**Comment by SirGigantor** [comment]
So the error is actually for the Amazon Forwarded Email field and not the sensors, that is definitely confusing with the placement.

also, I have an email in there cause I have my Amazon account with email ID 123@gmail.com and it forwards to HASS@gmail.com as an example, which is where this integrations connects and I’m still getting the string error.

**Comment by firstof9** [comment]
Technically for Gmail you don't need anything in the forwarders field, you can change it to `(none)`.

**Comment by squishyoctopus** [comment]
I think it’s on the UI side. I have my email in the box but if I edit the config I get the error when saving.  I found if I delete and re-add the last character in the box it saves fine.

**Comment by appsfinder2** [comment]
im getting same for shipment-tracking@amazon.co.uk, auto-confirm@amazon.co.uk, no-reply@amazon.co.uk

please advise need help ive ordered from amazon uk got email but no delivery count :( 

![Settings_–_Home_Assistant](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/31155587/77310067-423f-4ddc-8e07-52495aef105a)
![Overview_–_Home_Assistant](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/31155587/f66e2a18-74a0-4ea1-ad33-4205c50b7790)
how do I know if this add-on is getting the information from my iCloud emails?

**Comment by appsfinder2** [comment]
ok got it showing amazon packages using email forward to gmail from my iCloud now shows count:)  but link still goes to amazon.com :( from card please update to use all uk deliveries only shows ups and us postage.

**Comment by firstof9** [comment]
> from card please update to use all uk deliveries only shows ups and us postage

Card issues should be reported to [the card repo](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card).

**Comment by firstof9** [comment]
Please try `0.3.29b0` and see if this resolves your issue.
