### ISSUE TITLE
ISSUE: USPS Informed Delivery digest new layout

### ISSUE THREAD

**Issue by tjhorner** [moralmunky/Home-Assistant-Mail-And-Packages#893]
**Describe the bug**

The USPS Informed Delivery digest has a new email subject and HTML layout starting on May 23, so Mail and Packages no longer detects it. Just posting an issue here as a heads up!

**Environment (please complete the following information):**

 - OS: HAOS
 - Type of device: NUC
 - Home Assistant version: 2024.5.2
 - Hassio/Docker/Core? Hassio
 - Component version: 0.3.25

**Logs**

n/a

**Screenshots**

n/a

**Additional context**

I can provide a raw `.eml` file upon request to assist with implementation. I'm not uploading it here publicly due to the risk of leaking PII.

**Comment by firstof9** [comment]
Technically we don't parse the HTML version of the email, we parse the plain text version.

**Comment by tjhorner** [comment]
Ah you're right, didn't notice that. It also seems the changed subject line should not affect it. After reviewing the source some more it appears the changes USPS made shouldn't affect this integration. Sorry for the noise, then! I'll close this issue now.

**Comment by firstof9** [comment]
> Sorry for the noise

Perfectly fine, you were keeping an eye out and everyone appreciates the vigilance.
