### ISSUE TITLE
German Post DE new Email Subject

### ISSUE THREAD

**Issue by apfelflo89** [moralmunky/Home-Assistant-Mail-And-Packages#894]
**Describe the bug**
German Post DE "Briefankündigungen" never get detected due to a new subject "Ein Brief ist unterwegs zu Ihnen"
It could be an alteration but I can't say for sure
If I add it to const.py the Items get detected 

    "post_de_delivering": {
        "email": [
            "ankuendigung@brief.deutschepost.de",
        ],
        "subject": [
            "Ein Brief kommt in Kürze bei Ihnen an",
            "Ein Brief ist unterwegs zu Ihnen",
        ],

**Screenshots**
<img width="336" alt="image" src="https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/48082211/a8f3c16a-6d01-4939-9c2c-2d7247c19898">

<img width="387" alt="image" src="https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/48082211/a4022bf7-e537-49d3-8d51-2a9729484175">

**Comment by firstof9** [comment]
If you'd like to submit a PR based on your changes that'd be amazing.

**Comment by apfelflo89** [comment]
I don't know how, I'm sorry.

**Comment by firstof9** [comment]
Whoops, forgot the WIP tag.

**Comment by firstof9** [comment]
Should be fixed in the next release. Thanks!
