### ISSUE TITLE
ISSUE: UPS double count when live map offered

### ISSUE THREAD

**Issue by moralmunky** [moralmunky/Home-Assistant-Mail-And-Packages#91]
**Describe the bug**
UPS sent two day of in transit notifications for the same tracking number at two different times of the morning. The integration is matching both subject lines as an in transit for delivery that day adding a duplicate count. I cannot confirm consistency of receiving regular and live notification email for the same tracking number. I do know live map is not always sent for UPS deliveries.

9:15 AM - UPS Update: Follow Your Delivery on a Live Map
9:23 AM - UPS Update: Package Scheduled for Delivery Today

**Comment by firstof9** [comment]
Do both emails have tracking numbers in them? 
If so we could see about adding them to a list and if it exists in the list already don't count it again.

What do you think?

**Comment by moralmunky** [comment]
Both email are identical with the exception of the 'follow my delivery' information. Let's hold for a moment, possibly a larger strategy.

<img width="995" alt="Screen Shot 2020-04-15 at 12 51 43 PM" src="https://user-images.githubusercontent.com/19318945/79365351-8a08da00-7f18-11ea-974c-6664c0e65cb2.png">

**Comment by firstof9** [comment]
Seems like they've stopped sending the duplicate emails and only send the "Live Map" email now, if it's available.

**Comment by firstof9** [comment]
Closing this as it doesn't seem to be happening anymore.
