### ISSUE TITLE
ISSUE: Migration error

### ISSUE THREAD

**Issue by angrycatmeowmeow** [moralmunky/Home-Assistant-Mail-And-Packages#917]
**Describe the bug**
Migration error after updating to HA 2024.6.4

**Environment (please complete the following information):**
 - OS: HAOS
 - Type of device:HA Blue Odroid N2+
 - Home Assistant version:2024.6.4
 - Hassio/Docker/Core? 
 - Component version: 0.3.28

**Logs**
Logger: homeassistant.config_entries
Source: config_entries.py:927
First occurred: June 21, 2024 at 20:07:09 (1 occurrences)
Last logged: June 21, 2024 at 20:07:09

Error migrating entry imap.gmail.com for mail_and_packages
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 927, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mail_and_packages/__init__.py", line 207, in async_migrate_entry
    if updated_config != config_entry.data:
       ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'updated_config' where it is not associated with a value

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by jlmaners** [comment]
+1

**Comment by amera64** [comment]
+1

**Comment by firstof9** [comment]
Please try `0.3.29b0` and see if this resolves your issue.

**Comment by angrycatmeowmeow** [comment]
No errors in logs with the beta. It works.

**Comment by Dhtjf** [comment]
Beta also corrected the issue for me.

**Comment by thrunkmo** [comment]
Same here, upgraded to b1. Thanks!

**Comment by firstof9** [comment]
Fixed in `0.3.29`
