### ISSUE TITLE
ISSUE: In Transit is not reporting correctly

### ISSUE THREAD

**Issue by moralmunky** [moralmunky/Home-Assistant-Mail-And-Packages#93]
**Describe the bug**
Total in-transit is not calculating correctly.

Snap shot of sensor values:
sensor.mail_packages_delivered | 1
sensor.mail_packages_in_transit | 2

sensor.mail_fedex_delivered | 0
sensor.mail_fedex_delivering | 0
sensor.mail_fedex_packages | 0

sensor.mail_ups_delivered | 0
sensor.mail_ups_delivering | 2
sensor.mail_ups_packages | 2

sensor.mail_usps_delivered | 1
sensor.mail_usps_delivering | 1
sensor.mail_usps_packages | 2

Code for in-transit
```
            self._packages_transit = (self._fedex_delivering +
                                      self._ups_delivering +
                                      self._usps_delivering)
```
This should equal 3. Found additional code modifying value later (provided further down) but the delivering code for each carrier is already accounting for a delivered package.
```
self._fedex_delivering = ((get_count(account, FEDEX_Email,
                                                 FEDEX_Delivering_Subject) +
                                      get_count(account, FEDEX_Email,
                                                FEDEX_Delivering_Subject_2)) -
                                      self._fedex_delivered)
```

The code below is adjusting it further, is the code block still needed or was it intended to solve more issues? I think I remember there was a -1 issue at some point? 

**- Possibly use this code block and remove the adjustment from the delivery calculation? 
- Or modify this so that we don't display a negative intransitive?**

```
# Subtract the number of delivered packages from those in transit
            if (self._packages_transit >= self._packages_delivered and
               ((self._packages_transit - self._packages_delivered) > 0)):
                self._packages_transit -= self._packages_delivered
            else:
                self._packages_transit = 0
```
**Environment (please complete the following information):**
 - Component version: 0.1.4

**Comment by firstof9** [comment]
> ```
># Subtract the number of delivered packages from those in transit
>             if (self._packages_transit >= self._packages_delivered and
>                ((self._packages_transit - self._packages_delivered) > 0)):
>                 self._packages_transit -= self._packages_delivered
>             else:
>                 self._packages_transit = 0
>```

This was put in to account in case a "delivering" email was missing so we didn't get a negative number.

**Comment by firstof9** [comment]
I under stand the math error you're pointing out.

**Comment by moralmunky** [comment]
Perfect solution!
