### ISSUE TITLE
ISSUE: Configuring mail and packages with StartTLS crashes Home Assistant

### ISSUE THREAD

**Issue by Casuallynoted** [moralmunky/Home-Assistant-Mail-And-Packages#932]
**Describe the bug**
When entering IMAP info on the latest version of mail and packages, if StartTLS is selected instead of SSL, it simply doesn't move to the next configuration screen and home assistant becomes inaccessible until the machine is restarted entirely.

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: Beelink Mini PC
 - Home Assistant version: 2024.6.4
 - Hassio/Docker/Core?  HassOS
 - Component version: 0.3.29

**Logs**

**Additional context**

**Comment by firstof9** [comment]
What email service are you attempting to use?

**Comment by luke3butler** [comment]
Same here. Also, restarting core using `ha core restart` isn't enough and that command just hangs.
Having trouble finding anything relevant in the logs.

Attempted to sign in with iCloud using startTLS, as recommended by iCloud when SSL doesn't work (it didn't).

**Comment by firstof9** [comment]
Previous startup would be in `home-assistant.log.1`

**Comment by luke3butler** [comment]
I've rebooted a few times now, unfortunately.

And I wouldn't be able to use my iCloud account after all, because of #181

**Comment by geiseri** [comment]
it seems Zoho IMAP has the same issue.   I need to reenable to see the exact error, but it looked like a premature EOF.  I started after a homeassistant update, so maybe an underlying dependency did it.

**Comment by firstof9** [comment]
> it seems Zoho IMAP has the same issue. I need to reenable to see the exact error, but it looked like a premature EOF. I started after a homeassistant update, so maybe an underlying dependency did it.

Zoho says use SSL not TLS:

```
Select the Advanced tab and configure the Settings as follows:
Incoming Server (IMAP): 993
Select SSL from the drop down menu for encrypted connection.
```
Source: https://www.zoho.com/mail/help/outlook-imap-access.html
