### ISSUE TITLE
ISSUE: State of sensor is wrong (sensor Mail Image System Path)

### ISSUE THREAD

**Issue by ngdaihoc** [moralmunky/Home-Assistant-Mail-And-Packages#956]
**Describe the bug**
State of sensor is wrong (sensor Mail Image System Path)

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: PI4
 - Home Assistant Core: 2024.7.3
 - Home Assistant Supervisor: 2024.06.2
 - Component version: Mail-And-Packages 0.3.31

**Logs**
State of sensor [Mail Image System Path] that component Mail-And-Packages auto generate, be lack character "/"

**Screenshots**
![Mail-And-Packages_02](https://github.com/user-attachments/assets/f6bec162-f549-4ba9-bbe0-0b93d5890873)

**Additional context**
although state of sensor is wrong but when component [Mail-And-Packages] write file to storages is right

![Mail-And-Packages_03](https://github.com/user-attachments/assets/6f2d711d-e7d2-4460-aed6-f026779c9df3)

**Comment by firstof9** [comment]
This was fixed in the beta, please try that.
