### ISSUE TITLE
[Feature Request] Amazon.es and Portugal CTT

### ISSUE THREAD

**Issue by jacauc** [moralmunky/Home-Assistant-Mail-And-Packages#963]
I would like to request that Amazon.es, CTT Portugal, and Paack be supported into this integration.

Happy to do pull requests to add it, but would just need some guidance on how this would be achieved (I'm not very well versed in HACS code structure)

Is this repo still being actively maintained?

**Comment by firstof9** [comment]
All code changes should be done on the `dev` branch.
To add additional carriers, you'd modify `const.py`, it's pretty self explanatory once you see the others in the file.

As for Amazon, you only need to setup your amazon domain, unless it's not picking up the email address sending the emails.
