### ISSUE TITLE
ISSUE: Error searching emails: 'ascii' codec can't encode characters

### ISSUE THREAD

**Issue by segdy** [moralmunky/Home-Assistant-Mail-And-Packages#967]
**Describe the bug**

I have searched for this error but was nowhere a clear solution could be found. 

I keep getting errors like

```
Error searching emails: 'ascii' codec can't encode character '\u201c' in position 7: ordinal not in range(128)
Error searching emails: 'ascii' codec can't encode characters in position 70-71: ordinal not in range(128)
Error searching emails: 'ascii' codec can't encode characters in position 43-44: ordinal not in range(128)
```

constantly. I tried removing all my mails from the inbox (thinking it's maybe a malformatted email or subject line?) but it still shows up. It has been showing up for so many different versions that it can't be related to a specific version.

**Environment (please complete the following information):**
 - OS: Home Assistant OS
 - Type of device: Proxmox
 - Home Assistant version: 2024.8.1
 - Hassio/Docker/Core? OS 12.4
 - Component version: 0.4.0 (but issue pops up for a year or more already)

**Logs**

```
This error originated from a custom integration.

Logger: custom_components.mail_and_packages.helpers
Source: custom_components/mail_and_packages/helpers.py:599
integration: Mail and Packages (documentation, issues)
First occurred: August 11, 2024 at 11:37:26 PM (174 occurrences)
Last logged: 2:10:52 AM

Error searching emails: 'ascii' codec can't encode character '\u201c' in position 7: ordinal not in range(128)
Error searching emails: 'ascii' codec can't encode characters in position 70-71: ordinal not in range(128)
Error searching emails: 'ascii' codec can't encode characters in position 43-44: ordinal not in range(128)
```

**Screenshots**

<img width="570" alt="image" src="https://github.com/user-attachments/assets/5e09dd8c-9926-45bb-9b45-1492e8dcf590">

**Comment by firstof9** [comment]
What email provider?

**Comment by segdy** [comment]
My own server; I am running dovecot on Debian.

**Comment by firstof9** [comment]
Please attach debug logs so I can see what's causing the issue. Thanks.
