### ISSUE TITLE
ISSUE: The Mail USPS Package is not updating 

### ISSUE THREAD

**Issue by Royal911** [moralmunky/Home-Assistant-Mail-And-Packages#968]
**Describe the bug**
The Mail USPS Package is not updating just the mail

**Environment (please complete the following information):**
 - Home Assistant version: 2024.8.2
 - Docker
 - Component version: 0.4.0

**Logs**
there is no logs . try to activate the debug but did not generated anything

**Screenshots**
Email receive
![Email](https://github.com/user-attachments/assets/4f7635a6-9a1f-4ed0-92dd-0559dc6ee66a)
Info on HA
![info](https://github.com/user-attachments/assets/88c2259a-e213-46e2-98b6-7be404d7c4ff)

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment]
Packages are not updated from the daily digest. Please review the [USPS configuration in the wiki](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Supported-Shipper-Requirements).
