### ISSUE TITLE
ISSUE: Initialization Hangs - Setup says successful

### ISSUE THREAD

**Issue by AIKS68** [moralmunky/Home-Assistant-Mail-And-Packages#969]
**Describe the bug**

After the configuration shows successful, it hangs on the initialization and then fails.

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: HA Green
 - Home Assistant
 - Core 2024.8.2
 - Supervisor 2024.08.0
 - Operating System 13.1.rc1
 - Frontend 20240809.0

**Logs**

[home-assistant_mail_and_packages_2024-08-20T17-38-50.284Z.log](https://github.com/user-attachments/files/16679807/home-assistant_mail_and_packages_2024-08-20T17-38-50.284Z.log)

**Screenshots**
![Screenshot 2024-08-20 at 12 36 08 PM](https://github.com/user-attachments/assets/caed9b03-41e4-4200-a62b-cc8641e9a937)
![Screenshot 2024-08-20 at 12 37 24 PM](https://github.com/user-attachments/assets/15eb0572-e824-4260-b173-4a11b7b8a013)

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment]
```
2024-08-20 12:37:16.547 ERROR (MainThread) [custom_components.mail_and_packages] Timeout fetching Mail and Packages (imap.gmail.com) data
2024-08-20 12:37:16.547 DEBUG (MainThread) [custom_components.mail_and_packages] Finished fetching Mail and Packages (imap.gmail.com) data in 60.002 seconds (success: False)
```

Increase your IMAP timeout.

**Comment by AIKS68** [comment]
THANKS! Worked.
