### ISSUE TITLE
ISSUE: No more packages updates or USPS mail updates

### ISSUE THREAD

**Issue by tismofied** [moralmunky/Home-Assistant-Mail-And-Packages#972]
I have used this integration with success since last year and probably longer. It worked flawless since then to the point of forgetting that it's a custom integration.
I noticed today I am not showing any updates of packages  weather it's usps or amazon. this issue could have manifested for a while I and I just didn't realize it.
I had 2 packages that showed up today and I received their email from amazon this morning. I also have another package coming tomorrow from Amazon as well as a couple of packages from usps later this week.
I have not touched a thing in this integration since I was busy with other projects
This integration is installed in a bare metal home assistant OS

**Environment (please complete the following information):**
 - OS:  HassOS
 - Type of device: mini PC
 -  Home Assistant version: 
    -  Core   2024.9.0
    - Supervisor  2024.08.0
    - Operating System   13.1
    - Frontend   [20240904.0]
    

[**Logs**](https://pastebin.com/4J8DJDwq)

**Comment by firstof9** [comment]
Please [review the release notes](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/releases/tag/0.4.0) and reconfigure your integration and let me know if that solves your issue.

**Comment by tismofied** [comment]
I should have mentioned that part as well. My apologies. I did know about the breaking change when I updated the integration.
![Design 2 (1)](https://github.com/user-attachments/assets/099b4c24-07a9-4d88-88b4-043b3c331f32)
![Screenshot 2024-09-04 203838](https://github.com/user-attachments/assets/145ce682-09d8-46f3-8b82-3ad1e879f860)
![Design 2](https://github.com/user-attachments/assets/22cb9686-179d-4627-95c7-28175d917440)

Still issue not solved!

**Comment by firstof9** [comment]
Enable debug logging and post the log please.

**Comment by tismofied** [comment]
> Enable debug logging and post the log please.

Here you go sir 
[debug log](https://pastebin.com/R8SaHcqm)

**Comment by firstof9** [comment]
There's no debug data in there to work with. You'd need to lower your scan interval then capture the log while it's doing the email check.

**Comment by tismofied** [comment]
> There's no debug data in there to work with. You'd need to lower your scan interval then capture the log while it's doing the email check.

[How about this log](https://pastebin.com/de01NVBS)

**Comment by firstof9** [comment]
Enter `(none)` into your Amazon forwarded email address setting. You don't need this with using gmail.

**Comment by tismofied** [comment]
> Enter `(none)` into your Amazon forwarded email address setting. You don't need this with using gmail.

- [ ] ~That's what I had before, the when I noticed it wasn't working, I put my other gmail account I use for amazon deliveries.( which is in turn forwarded to my primary email account)
I'll try (none) and see if it works. Otherwise, I'll just start from scratch again.~

**Comment by tismofied** [comment]
I fixed it. My issue was I was forwarding to <myemail>@duck.com which I was using to strip my primary emails of trackers. 
Now I know how to fix it when I get home. I can't access email forwarding settings from mobile. 
Consider this issue closed. 
Thank you @firstof9 for all you do in this integration
