### ISSUE TITLE
ISSUE: Clicking the Amazon Icon doesn't go to the amazon website

### ISSUE THREAD

**Issue by yuckypants** [moralmunky/Home-Assistant-Mail-And-Packages#973]
**Describe the bug**
Clicking the Amazon Icon under the photo for the amazon delivery is supposed to navigate to the amazon website. Instead, it reloads the instance of HA. The other icons, USPS, FedEx, and UPS, all navigate to their respective sites, as expected. The tooltip with contextual help even states that by clicking, it would navigate to the amazon website.  

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: RPI4
 - Home Assistant version: 2024.8.1
 - Hassio/Docker/Core? Hassio
 - Component version: 0.8.0.0

**Logs**
Paste your error logs here.

**Screenshots**
![usps](https://github.com/user-attachments/assets/9f8938ad-41b2-4f25-b203-d8fa0ac72d9a)
![hover_amazon](https://github.com/user-attachments/assets/f11a2e80-d3b9-49cc-8b00-73c70bd20dc4)

hovering over the icon shows the tooltip, but on the bottom left corner, the URL for amazon is incorrect. 

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment]
Wrong repo. Please report this issue here: https://github.com/moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card

**Comment by yuckypants** [comment]
Sorry! Will report in the correct location.
