### ISSUE TITLE
ISSUE: Can't Write to Image Folder

### ISSUE THREAD

**Issue by redxtech** [moralmunky/Home-Assistant-Mail-And-Packages#975]
**Describe the bug**
If you use an immutable OS, and manage home-assistant through the package manager, then the `custom_components/mail_and_packages` directory is going to be set to `readonly`, which causes issues when trying to write to the images folder in `custom_components/mail_and_packages/images`.

**Environment (please complete the following information):**
 - OS: NixOS
 - Type of device: custom build NAS/desktop
 - Home Assistant version: 2024.9.0
 - Core
 - Component version: 0.4.0

**Logs**
```
2024-09-17 11:14:18.551 ERROR (SyncWorker_5) [custom_components.mail_and_packages.helpers] Problem creating: /config/homeassistant/custom_components/mail_and_packages/images/amazon, error returned: [Errno 2] No such file or directory: '/config/homeassistant/custom_components/mail_and_packages/images/amazon'
# repeated for each folder
```

**Additional context**
NixOS is an immutable distro that uses the `nix` package manager, which is also immutable. Packages are generated at build time, and then symlinked into place. So `/config/homeassistant/custom_components/<package-name>` is symlinked to `/nix/store/<package-hash>-<package-name>/`, which cannot be written to, being immutable.

Changing the image location to something more standard, like `.storage/mail_and_packages/images` might make more sense?

I'd be happy to provide testing if you aren't able to!

**Comment by firstof9** [comment]
I can see about making the storage location configurable.

**Comment by firstof9** [comment]
Ok I have a branch created and all my tests are passing, if you'd like to give it a real world/real user test here's the branch:

https://github.com/firstof9/Home-Assistant-Mail-And-Packages/tree/fix-975

**Comment by redxtech** [comment]
I just tested using that branch, and it works great!

Thanks for such a quick turnaround on this!

**Comment by firstof9** [comment]
This is in 0.4.1-b0 now.
Please give it a test, thanks.
