### ISSUE TITLE
[Feature Request] Add support for financial alert emails

### ISSUE THREAD

**Issue by rhollister** [moralmunky/Home-Assistant-Mail-And-Packages#979]
Hi @moralmunky, @firstof9, et al, I would like to make (what is likely to be a radical) feature request for additional template configurations to scan financial emails in addition to mail and packages emails. 

My goal is to display all banking and credit card transactions on my Home Assistant tablet for my wife and I to review for possible fraudulent charges.

My thought was users could turn on email notifications from their credit card and bank institutions, and this add-on could be extended to support parsing those emails. Then a separate custom Lovelace card would display the most recent credit card transactions, bank deposits, bank withdrawals, etc. It'd be great for couples watching their budget or watching for fraudulent charges.

This lines up well with this add-on's wonderful ability to:
1. Log in to an email provider
2. Scan for specific emails
3. Parse the emails based on template configurations
4. Store results for display in Home Assistant

A great advantage to this method of scanning for transaction emails is that it avoids the extremely risky need for banking logins to be saved in Home Assistant configurations. It simply only needs an email login which many users are already happy to configure. 

My specific ask in this submission is: **What is the likelihood of a pull request being accepted if I added sensors in `const.py` and parsers in `helpers.py` to support financial alerts?**

Even more specifically: in `const.py`, adding: `citi_transaction` and `ncr_transaction` sensors, and in `helpers.py` adding: `citi_alert()` and `ncr_alert()` parsers.

I could certainly fork this fantastic repo, but I fear it would be too much to keep up with the great work that's still being done. These changes would certainly increase the thematic scope of this project- but functionally they are minor configuration additions and simply leverage the great core functionality already built.

Thank you for your consideration!

**Comment by firstof9** [comment]
While this seems like a neat idea, it would technically be out of the scope of the integration.
