### ISSUE TITLE
ISSUE: Amazon images are being created multiple times per day

### ISSUE THREAD

**Issue by yuckypants** [moralmunky/Home-Assistant-Mail-And-Packages#985]
**Describe the bug**
Discovered 11k photos of the "NO DELIVERIES AMAZON" in the \config\custom_components\mail_and_packages\images\amazon directory. 

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: [RPi4]
 - Home Assistant version: [2024.10.4]
 - Hassio/Docker/Core? Hassio
 - Component version: [0.4.0]

**Logs**
No error logs

**Screenshots**
unneccessary

**Additional context**
Noticed backup file sizes were enormous, which is how I found over 400mb of image files.

**Comment by firstof9** [comment]
Please test 0.4.1-b1 and see if that helps.
Thanks.

**Comment by tismofied** [comment]
I redownloaded 0.4.1-b2 and it seems to have fixed the image duplication issue. only one image shows under right
**`/custom_components/mail_and_packages/images/amazon/`**
Thank you Chris.

**Comment by firstof9** [comment]
Thanks for confirming.
