### ISSUE TITLE
ISSUE: German DHL Mails detection fails

### ISSUE THREAD

**Issue by apfelflo89** [moralmunky/Home-Assistant-Mail-And-Packages#990]
**Describe the bug**
DHL changed the Subject of their Mails and switched the term "Paket" to "Sendung", so the filter within const.py doesn't match. 
In addition there a line break in the body. 
const.py is looking for "wird Ihnen heute" but the Mail looks like this:

<img width="322" alt="image" src="https://github.com/user-attachments/assets/f4cff3df-c46e-44de-9347-634b00120f3b">

Which looks like this in html:
wird Ihnen&nbsp;</span></p><p style=3D"margin:0;=margin-bottom:11px"><strong>heute zwischen

I was able to fix it locally for me by adding this lines to DHL:

<img width="283" alt="image" src="https://github.com/user-attachments/assets/eaed546b-a49d-4253-b588-319384e471f6">

and for the body I added "heute zwischen" to the filter list. 
<img width="404" alt="image" src="https://github.com/user-attachments/assets/d08b18ce-a410-45bf-b5a1-fac48f0f2347">

After this fixes DHL is now working for me again, could you add this to the regular releases?

Thank you!

**Comment by firstof9** [comment]
PR's are welcome, please base any PRs on the `dev` branch.

**Comment by apfelflo89** [comment]
I'm sorry I still don't know how to do PRs :/

**Comment by firstof9** [comment]
Check #991 to see if those changes match your's please.

**Comment by firstof9** [comment]
Fixed in #991
