### ISSUE TITLE
ISSUE: local file update error

### ISSUE THREAD

**Issue by farberm** [moralmunky/Home-Assistant-Mail-And-Packages#993]
**Describe the bug**
The automation "Update USPS Mail Camera Path on Hass Restart" (automation.update_usps_mail_camera_path_on_hass_restart) has an unknown action: local_file.update_file_path.

This error prevents the automation from running correctly. Maybe this action is no longer available, or perhaps a typo caused it.

**Environment (please complete the following information):**
 - OS: RaspPi4 HA 2024.11.0 Core Sup 2024.11.2, OS 13.2
 - Type of device: RPI4
 
Logger: homeassistant.components.automation.update_usps_mail_camera_path_on_hass_restart
Source: helpers/script.py:2032
integration: Automation ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 12:30:10 PM (1 occurrences)
Last logged: 12:30:10 PM

Update USPS Mail Camera Path on Hass Restart: Error executing script. Service not found for call_service at pos 1: Action local_file.update_file_path not found

**Comment by firstof9** [comment]
Looks like you have some kind of issue with your automation.
This isn't an integration bug.

**Comment by farberm** [comment]
I am pretty sure I based it off the GitHub instructions

**Comment by firstof9** [comment]
I assure you it is not.

**Comment by cchiapusio** [comment]
@farberm I'm here due to the same warning. I installed this... years ago?  I'm going to go over the modern instructions and see what deviations have occurred over time.

**Comment by farberm** [comment]
Is there a link to the "modern instruction" or are you using the ones on this github front page? I installed mine years ago also

**Comment by cchiapusio** [comment]
> Is there a link to the "modern instruction" or are you using the ones on this github front page? I installed mine years ago also

You are correct, I am just looking at the github front page, and possibly doing some googling to find the heritage of the instructions we both followed (since our automation has the exact same name and error)

**Comment by cchiapusio** [comment]
This is part of the associated custom card for displaying the hard work of the Mail and Packages add-on:

https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/USPS-Informed-Delivery-Image

**Comment by cchiapusio** [comment]
@firstof9 FYI The previous link is the first example linked directly from the github home for this project.  Since the action in question is still presented in the Home Assistant documentation (https://www.home-assistant.io/integrations/local_file/)  this does appear to be a core home assistant issue and not related to the add-on.

**Comment by firstof9** [comment]
Those instructions are no longer required as the integration provides camera entities now.
