### ISSUE TITLE
ISSUE: Regression, binary sensor no longer indicates if there is a real image available

### ISSUE THREAD

**Issue by kariudo** [moralmunky/Home-Assistant-Mail-And-Packages#996]
**Describe the bug**

It appears the #682 enhancement suffered a regression and no longer works as expected to determine if the image has been set to a real image.  I depend on having a boolean state for this to determine if the component should be rendered conditionally.

**Environment (please complete the following information):**
 - OS: Docker/linux
 - Type of device: N100
 - Home Assistant version: 2024.11.1
 - Docker
 - Component version: 0.4.0

**Logs**
Paste your error logs here.

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment]
Please try [0.4.2-b0](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/releases/tag/0.4.2-b0) and see if this resolves the issue for you.

**Comment by SeanPM5** [comment]
For me both the Amazon and USPS binary sensor are unavailable now after 0.4.2-b0, I get this in logs:

```
Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:599
integration: Binary sensor (documentation, issues)
First occurred: November 13, 2024 at 11:40:35 PM (4 occurrences)
Last logged: 2:59:50 AM

Error adding entity binary_sensor.usps_image_updated for domain binary_sensor with platform mail_and_packages
Error adding entity binary_sensor.amazon_image_updated for domain binary_sensor with platform mail_and_packages
Traceback (most recent call last):
  File "/config/custom_components/mail_and_packages/helpers.py", line 166, in default_image_path
    storage = config_entry.get(CONF_STORAGE)
              ^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntry' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 599, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 918, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1368, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1069, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1013, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 294, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/mail_and_packages/binary_sensor.py", line 91, in is_on
    path = default_image_path(self.hass, self._config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mail_and_packages/helpers.py", line 168, in default_image_path
    storage = config_entry.data[CONF_STORAGE]
              ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'storage'
```

Reverted back to 0.4.1 which fixes it for me.

**Comment by firstof9** [comment]
I've fixed that keyerror, give [0.4.2-b1](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/releases/tag/0.4.2-b1) a try

**Comment by rpitera** [comment]
Seems to be working here on my end. At least the sensors are now available and show a status of 'up to date'.

TBH, I've never used these sensors before and can't really test them beyond that.

**Comment by firstof9** [comment]
Ya I did a bit more testing and they weren't really working #1002 fixes it however, should be one more beta to test.

**Comment by firstof9** [comment]
> At least the sensors are now available and show a status of 'up to date'.

They should switch to "Update avaiable" if the USPS or Amazon camera image isn't the "no mail" images.

**Comment by firstof9** [comment]
Let me know how [0.4.2-b2](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/releases/tag/0.4.2-b2) works out for you all.

**Comment by firstof9** [comment]
Nevermind it didn't work as expected :disappointed:

**Comment by firstof9** [comment]
I have confirmed [0.4.2-b3](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/releases/tag/0.4.2-b3) resolves the issue for me, please confirm on your end.

Thanks.

**Comment by kariudo** [comment]
It would appear that this is working as expected for me on b5 as the true state is now showing my conditional as before; however, (and I'm not sure how to debug this) I have noticed that (I assume at some refresh state of the camera image it flashes occasionally to the "No Mail" graphic.

**Comment by firstof9** [comment]
> I have noticed that (I assume at some refresh state of the camera image it flashes occasionally to the "No Mail" graphic.

Yes the file name gets rolled and it takes a second for the camera to update.
